### ISSUE TITLE
add history pane to explorer

### ISSUE THREAD

**Issue by howardchung** [odota/web#1101]
Allow user to see what they recently queried and jump back/forth

**Comment by howardchung** [comment]
similarly, use `replaceState` instead of `pushState` so we don't spam the user's browser history (we don't auto-update the UI based on back button clicks anyway)

**Comment by steventsao** [comment]
I can give this one a shot @howardchung

**Comment by howardchung** [comment]
Sure, that'd be great!

**Comment by steventsao** [comment]
@howardchung How should query history be displayed? Should the select statement of each query be displayed or the query string? ie. https://docs.oracle.com/database/121/AEUTL/img/sql_hist.gif

**Comment by howardchung** [comment]
Probably the select statement

**Comment by steventsao** [comment]
The full select statements are so long for showing in the query history pane so I need to look for other examples. The scope of this is larger than I anticipated. If there are other takers please feel free to take this issue, which I'll stay subscribed.

**Comment by howardchung** [comment]
Maybe you can just show a short snippet and ellipsis the rest?

**Comment by howardchung** [comment]
I don't think this feature is necessary, shelving it for now
