### ISSUE TITLE
MMR comparison among Steam friends

### ISSUE THREAD

**Issue by MaxwellLevenson** [odota/web#1118]
It'd be nice to have a tab where you can easily browse your Steam friend's (or "peers") MMRs  compared to yours. All the data should be in the database already, it's just hooking up the data pipeline and adding a container.

**Comment by howardchung** [comment]
Yeah, we could probably do this by looking up MMR for each peer in the /peers API call

**Comment by flankstaek** [comment]
I think I'll have a pull request here & on core w/ this feature later today

**Comment by howardchung** [comment]
I'm guessing this is moot now that ranked medals are out and are public to everyone.
