### ISSUE TITLE
Make log similar to chat

### ISSUE THREAD

**Issue by blukai** [odota/web#1140]

**Comment by Luchanso** [comment]
Can you write more information about it?

**Comment by blukai** [comment]
@Luchanso 
Create the "Message" component and display log events similar to messages on the chat tab, like this:
![image](https://user-images.githubusercontent.com/20866892/32013716-9cf0ba5a-b9c4-11e7-8c5e-039805910a7f.png)
Also maybe make filters (kills, objectives, runes) like on the chat tab

**Comment by DomitriusAnthony** [comment]
Is this still open? Would like to try!

**Comment by Luchanso** [comment]
@DomitriusAnthony Yeah, u can! 👍Maybe just modify this chat?
![image](https://user-images.githubusercontent.com/2098777/38411605-1c6dc3b8-3990-11e8-953e-83e1797cef4b.png)

What you think @howardchung?

**Comment by howardchung** [comment]
Sounds good!  You can probably reuse the same component that chat uses.

**Comment by ChrisMissal** [comment]
I believe this one is complete, the log looks great!

![image](https://user-images.githubusercontent.com/67798/42465021-6eff6b84-8370-11e8-91c4-5aa264d38032.png)
