### ISSUE TITLE
team pages

### ISSUE THREAD

**Issue by howardchung** [odota/web#1142]
Create pages for each team (will require adding new endpoints to odota/core but we have the data)

Things we might want to display:
* Players registered to the team
* Recent games played by the team
* Heroes played by the team

**Comment by denichodev** [comment]
I am very interested in taking this. Need time to learn about the source first, though.

**Comment by howardchung** [comment]
Sure!  This is a larger feature and will require implementing API endpoints in odota/core.  If you know what kinds of data you want to display, I can help with that part

**Comment by howardchung** [comment]
I'm hoping to implement the three endpoints above in the next few days.  Stay tuned!

**Comment by howardchung** [comment]
implementation in:
https://github.com/odota/core/pull/1539

New endpoints are:
/teams/{teamId} for one team's data
/teams/{teamId}/matches for a team's matches
/teams/{teamId}/players for players who have played for that team
/teams/{teamId}/heroes for heroes the team has played

**Comment by denichodev** [comment]
Nice, now I don't have to fetch all team and filter it now.

I will continue working on this, but currently I am busy preparing for a job interview, will do it after this hectic week!

**Comment by howardchung** [comment]
It would be nice to be able to track the Qualifying Points for teams/players as well, but I am not sure if there is an official API for this.

We can scrape from http://www.dota2.com/procircuit but it would be nice to avoid doing that

**Comment by colinfike** [comment]
Hey whats the status of this? Looking for an issue (or part of one) to work on.

**Comment by howardchung** [comment]
I think the APIs are implemented on the backend but not sure what the status is on UI.

@denichodev can you push what you have and make an early PR?

**Comment by denichodev** [comment]
@howardchung Hi, sorry for the delay, just got a new job and I think I can't work on this more. 

@colinfike There's not a lot that I've done, only dynamic /:teamId routes, and a page component. If you want me to make an early PR on this, tell me.

**Comment by colinfike** [comment]
Yeah if you don't mind can you just push your branch and make a PR of what you have thus far? I'll take a look at what you have when I'm checking this out.

**Comment by howardchung** [comment]
Any update on this?

It's also possible to get player images from the dota 2 client, I can pull those and upload to the repo if good to have

**Comment by spudde123** [comment]
Hey, first time contributor here. I'm interested in helping out, I made some initial progress and made a PR.
