### ISSUE TITLE
show age of MMR data

### ISSUE THREAD

**Issue by justmeeee** [odota/web#1183]
I recently had a game with average 2.2k MMR.
When I review the game one player is shown as ~1.6k MMR. I know, that it shows the current MMR not the MMR during the game, but he couldn't have lost 600 MMR in 2 hours...

https://www.opendota.com/matches/3455767578

I had another game where a player is shown as 3k MMR.

Is this an issue with international ranked? If so can both MMR be shown?

**Comment by howardchung** [comment]
This player hasn't had their MMR visible for a year:
https://www.opendota.com/players/164482777/mmr

The value is outdated

**Comment by justmeeee** [comment]
Ah, ok, that explains it. Can we have that information in the overview on mouseover over the person icon (last updated:)?

**Comment by howardchung** [comment]
Yeah, I guess that'd be possible but would require adding some data to the database and pass it down to the UI

**Comment by justmeeee** [comment]
Great! :+1: 
And also on player overview?

**Comment by howardchung** [comment]
Yeah it would be the same data.  The main thing is to add a column to the MMR table tracking when the data was collected.

**Comment by justmeeee** [comment]
I understand. It was just a question if you think that it's a good proposal ;)

**Comment by SomeNiceDude** [comment]
I dont know why they refuse to do it so badly. Please add it.

**Comment by howardchung** [comment]
No one's refusing to do it, but someone has to volunteer to actually write the code :)

**Comment by hntd187** [comment]
I am volunteering to write it. Like I said I just need a bit of guidance about what would be required to do it properly.

**Comment by howardchung** [comment]
Few steps needed:
* Check out https://github.com/odota/core
* Add updated_at columns to solo_competitive_rank and competitive_rank tables (https://github.com/odota/core/blob/master/sql/create_tables.sql#L394)
* Update the insertion function to put the current time in the database (https://github.com/odota/core/blob/master/store/queries.js#L449)
  * It's already available in the row object as row.time, the mmr update service code is here which called insertPlayerRating: https://github.com/odota/core/blob/master/svc/mmr.js

**Comment by howardchung** [comment]
I think this is moot with the new ranked system
