### ISSUE TITLE
Bug in sortFn, in Table

### ISSUE THREAD

**Issue by Luchanso** [odota/web#1261]
I found bug with sort function, in [components/Table/Table.jsx#L148](https://github.com/odota/ui/blob/master/src/components/Table/Table.jsx#L148)

sortFn must be like default sort with two arguments f(a, b)

**Comment by howardchung** [comment]
This is not exactly a bug but I agree the behavior is a bit unintuitive.  Basically each column needs to define a function that returns a value in the sortFn field and the table internally sorts those values.

Passing a compare function (a,b) probably makes more sense but would require refactors to a lot of table columns.  We would also need to figure out how to handle inverted sorts (the table needs to support sorting both ascending and descending as the user clicks headers)

**Comment by Luchanso** [comment]
Yes, you sure, need think about it

**Comment by howardchung** [comment]
Not an issue anymore?

**Comment by Luchanso** [comment]
I just don't know how to resolve it
