### ISSUE TITLE
Progressive Web App (suggestion)

### ISSUE THREAD

**Issue by superoo7** [odota/web#1266]
I would like to suggest a few [progressive web app](https://developers.google.com/web/progressive-web-apps/) approach of making this site.

- [x] Mobile Icon on iOS and Android (Add to Home Screen)

I sent a pull request on this [#1265](https://github.com/odota/ui/pull/1265)

- [x] enable service worker (it was disabled, I want to know why)

pull request on this [#1265](https://github.com/odota/ui/pull/1265)

- [ ] push notification
- [ ] Caching for faster load of the app (require eject of webpack)

- [ ] Faster load speed and App Shell

**Comment by howardchung** [comment]
I had some issues with the site not loading when the service worker was enabled.  It started working again when I added the unregister call, not sure what the problem was

**Comment by superoo7** [comment]
I have hosted the web ([https://superoo7-odota.surge.sh/](https://superoo7-odota.surge.sh/)), tested on chrome, no issue.

Google lighthouse report, [before 64/100](https://odota-result.surge.sh/before.html) and [after 91/100](https://odota-result.surge.sh/after.html)

**Comment by howardchung** [comment]
OK, submit a PR and we can test it on stage

**Comment by superoo7** [comment]
Alright I sent a pull request to re-enable service worker. Should I include package-lock.json?

**Comment by superoo7** [comment]
![22553468_10209895288594094_445158864_o](https://user-images.githubusercontent.com/15358452/31663686-860779f0-b375-11e7-85c9-1387d9b3bfcf.png)![22563883_10209895288434090_931246752_o](https://user-images.githubusercontent.com/15358452/31663690-89b0d998-b375-11e7-8a84-f3e33be9a2c2.png)

Tested on Android with Chrome

**Comment by howardchung** [comment]
Did package-lock change?  This shouldn't require installing any dependencies?

**Comment by superoo7** [comment]
I think I build it then it updates, I did not include package-lock.json in my commit.

**Comment by howardchung** [comment]
Does the service worker handle things properly if the file name changes?  I think previously the issue was that the js bundle name changed (since it has a hash in the file name) and then the service worker was trying to reload the old bundle.

**Comment by superoo7** [comment]
I never publish or tested web that created with create-react-app on service worker. I normally use this [plugin](https://github.com/NekR/offline-plugin) for progressive web app because it caches automatically and created service workers. However, this requires to eject the project out from create-react-app.

**Comment by howardchung** [comment]
It appears that the current version of the code won't load on the first visit after an update because it can't find the older version of the javascript bundle.

According to registerServiceWorker it only loads the latest data in the background during the failed page load, so the initial load won't work.

https://github.com/odota/ui/blob/master/src/registerServiceWorker.js#L6

I don't know if this is a deployment or configuration issues (we use netlify to serve the UI)

**Comment by howardchung** [comment]
The error is an "unexpected token <" error in the javascript console.  It's possible this is due to the netlify configuration that causes it to serve index.html regardless of the path requested (this is to support client side routing).

I'm not sure if the service worker expects a 404 response in order to identify that a file no longer exists/has changed

**Comment by superoo7** [comment]
Sorry for the delay reply, I was busy in the past 3 weeks, now looking through the statement u said on the "unexpected token <", I don't really know what is it on the configuration on netlify, but another approach is to create our own `service-worker.js` where giving up the [default service worker](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app) given by create-react-app, this approach will allow us to make our own cache strategy and more flexibility.

**Comment by howardchung** [comment]
If you know how to patch the worker to get it to work, we can try it out?

**Comment by howardchung** [comment]
I tried making netlify serve 404 for not found errors of the JS bundle, but the problem still occurs, so that's probably not the issue.

If it's an issue with the service worker though, I'd imagine that people would have running into this since create-react-app is quite popular

**Comment by superoo7** [comment]
Not too sure whether is create-react-app issue or not, I think I will create a `service-worker.js` in the public folder, and then enable it in the `src/index.js` file. Will update you once is done

**Comment by superoo7** [comment]
I ejected a project created with `create-react-app` and in the `webpack.config.prod.js` file:

![screen shot 2017-11-20 at 12 48 50 pm](https://user-images.githubusercontent.com/15358452/33002771-3a39c758-cdf1-11e7-86ad-35b93d8e49f3.png)

It uses `SWPrecacheWebpackPlugin` to create `service-worker.js`.
SWPrecache is the Preaccessor of WorkBox, it is stable and older tool, which does not have the latest service worker available tools. I myself use Workbox normally, never tried SWPrecache.

**Comment by superoo7** [comment]
I made a PR on fixing the error ` "unexpected token <"`

[#1344](https://github.com/odota/web/pull/1344)
