### ISSUE TITLE
MMR after battle pass

### ISSUE THREAD

**Issue by artolio** [odota/web#1276]
My mmr does't track after switch with battle pass mmr. 
Expose Public Match Data is enabled .

**Comment by howardchung** [comment]
Have you played a ranked match since?

**Comment by artolio** [comment]
yes, and mmr is visible at my dota profile

**Comment by howardchung** [comment]
Can you provide a link to your profile?

**Comment by artolio** [comment]
ofc
http://steamcommunity.com/id/artolio/

**Comment by howardchung** [comment]
Approximately when did you switch your MMR to battle pass MMR?  Updates aren't necessarily guaranteed after each match, so if you only played one game since it may not have picked up.

**Comment by artolio** [comment]
switched my mmr in september. 
i have been played a lot of matches after swithcing mmr. but data still not updated since september

**Comment by howardchung** [comment]
When was Expose Public Match Data enabled?  Was it just recently enabled or has it been on since September?

**Comment by artolio** [comment]
it was enabled before septermer, and everythings work's fine before switching mmr

**Comment by howardchung** [comment]
I was able to force an update via manually inserting a job into the queue:
`redis-cli lpush mmrQueue "{\"account_id\": 86745300, \"match_id\": 3517226234}"`

It seems like the update code is working properly, but not sure why the MMR values weren't being picked up.
If it continues failing to update after ranked matches, please let me know and I'll investigate further.

**Comment by artolio** [comment]
thank u.
btw, same trouble at dotabuff)

**Comment by howardchung** [comment]
I'm guessing this is moot with the new ranked system
