### ISSUE TITLE
Show Last Hit and Deny stats made during laning stage

### ISSUE THREAD

**Issue by mcetkovsky** [odota/web#1341]
The total number of last hits is quite biased by late game and does not really represent the player skills of last hitting. For example, Death Prophet can get lots of last hits using Crypt Swarms to quickly kill creeps when preparing to attack a tower in late game.

As such I suggest to show Last Hit and Deny stats during the first few minutes of the game and make benchmarks on this early game stats rather than full-game.

Maybe you also find a way how to determine the transition from laning to mid game stage.

**Comment by howardchung** [comment]
We do track the LH@10 stat, although it's currently not benchmarked.

**Comment by mcetkovsky** [comment]
I haven't come across the LH@10 stat anywhere. Where can I find it?

**Comment by howardchung** [comment]
It's on the laning tab

**Comment by howardchung** [comment]
Combining with https://github.com/odota/web/issues/524 since both require the same backend change to add parsed data to benchmarks
