### ISSUE TITLE
Turned off "Expose Public Match Data" for some games and now they don't show

### ISSUE THREAD

**Issue by siXor** [odota/web#1343]
What title says. I turned the option off for 5-10 games and then turned it back on. The latest games that I played are recorded but I'm still missing those that I played with the setting turned off. I pressed the refresh button on my profile and waited one day but nothing has happened.

Player-id: 25597735
Missing games are from Saturday-Sunday. I played some games on Monday and they show, I thought OD would pick up missing games when it found a new game with me but it didn't.
I can't check Valve's API if the games are shown there but they should be.

**Comment by coreymaher** [comment]
@siXor Are the missing games ranked? I think valve got rid of the API opendota uses to grab old ranked games.

**Comment by siXor** [comment]
Yes, those are ranked games. If they removed the API then that sucks. Is there no way to get them into opendota?

**Comment by coreymaher** [comment]
If you know the match ids you can manually request them: https://www.opendota.com/request

**Comment by siXor** [comment]
@coreymaher Thanks. I just did that and all missing games got added. Closing the issue.
