### ISSUE TITLE
Hero recent pro matches shows incorrect win/loss result

### ISSUE THREAD

**Issue by coreymaher** [odota/web#1345]
It looks like the recent matches section on a hero page does not always show the correct outcome of the match.

For example: https://www.opendota.com/heroes/111/recent
This is showing several matches as losses where the oracle player won, and wins where the oracle player lost.

**Comment by howardchung** [comment]
We should replace this column with `radiant_win`
https://github.com/odota/core/blob/master/routes/spec.js#L3367

That way the UI handles the display correctly:
https://github.com/odota/web/blob/a94de8135f5c6154bb24b01d7357de290caf10ca/src/components/Hero/Recent.jsx#L52

**Comment by howardchung** [comment]
Fixed this in core, should be fixed in UI when the web instances update.
