### ISSUE TITLE
add ranked medals to player pages

### ISSUE THREAD

**Issue by howardchung** [odota/web#1351]
medal images added in #1337 

Data is present in the players API call, just need to render the correct image

**Comment by GravityMsc** [comment]
I want to add ranked medals in the div.titleNameButtons, in front of "playerName". Is it ok?

**Comment by GravityMsc** [comment]
![image](https://user-images.githubusercontent.com/17739114/33476783-3433270c-d6be-11e7-96a3-488870cb803f.png)

the location of that red circle

**Comment by howardchung** [comment]
sounds good to me
