### ISSUE TITLE
Add placeholder text for empty tables

### ISSUE THREAD

**Issue by howardchung** [odota/web#1360]
As suggested in #1342, player peers and rankings should show some placeholder text such as "This player has no peers" or "This player is not ranked on any heroes" when the responses have no data.

**Comment by JaydenIvanovic** [comment]
I'd be more than happy to start contributing to this project and tackle this as a first issue.

**Comment by howardchung** [comment]
Go for it!  Ask here or on Discord if you have any questions.

**Comment by JaydenIvanovic** [comment]
Thanks for the quick response! I've started playing with this throughout the day and have one question so far. How should I go about getting the different strings for the different languages for these placeholder messages?

**Comment by howardchung** [comment]
Just add them to en-US.json and the translators will translate it

**Comment by JaydenIvanovic** [comment]
Sorry for the delay on this. I have a branch ready but I am unable to push it to the remote (I get a 403 back). Is there any additional steps I need to follow in order to submit a pull request?

**Comment by howardchung** [comment]
You can either push to your own fork and submit a PR or I can add you as a contributor
