### ISSUE TITLE
Some suggestions on Averages/Maximums tab.

### ISSUE THREAD

**Issue by kxxoling** [odota/web#1371]
This is a example of my Averages/Maximums in last 20 matches.

![image](https://user-images.githubusercontent.com/1227139/33609768-4fb78bd2-da04-11e7-9a1f-9d583088fd51.png)

1. As you could see, my max XPM and GPM are 1.4k and 1.9k, far more than pro players. This is because they are both Turbo modes. 
2. Match link is hard to click, because the hero icon is too small. I think this could be improved by making the max number also be a part of link as they both are related data in same match.
3. All the data in this line are one's best records of a player except *death*. Should this be replaced by *min death*?

**Comment by GravityMsc** [comment]
I don't think min death is useful. Almost everyone's min death is less than 3 times. And as we all know, record means rare data.

**Comment by kxxoling** [comment]
@GravityMsc This is a good point. How about the others? I think Turbo mode games should be separated or even hidden. They are basicly just for fun.

**Comment by GravityMsc** [comment]
@kxxoling I agree. Only normal or ranked matches' records are memorable.
