### ISSUE TITLE
Gold graphs don't end at the right time. 

### ISSUE THREAD

**Issue by previsualconsent** [odota/web#1391]
In a ticketed tournament game, the last 3 minutes have zero GPM. This is a game where one team GG'd to end the game.
https://www.opendota.com/matches/3612852168/graphs

This could be just cosmetic except they GPM score on the analysis tab says the lowest GPM in a 3 minute interval is basically zero.

**Comment by howardchung** [comment]
Yeah I think this is because the replay actually goes on for a few minutes longer.  Could probably be fixed either at the replay parsing level or on the analysis tab.

**Comment by previsualconsent** [comment]
The total match time still looks correct though.

**Comment by howardchung** [comment]
The match time is from the API, but the gold graph is from replay parsing.
