### ISSUE TITLE
how about adding an indicator to show which player had the highest stats?

### ISSUE THREAD

**Issue by rezk2ll** [odota/web#1394]
Hello,

I think it would be good to show which player had the highest Kills/Deaths/Assists/Last Hits/XPM/GPM...

the indicator could be an `underline` or a `star` or something `remarkable`. I know there is a sort functionality in the match table but it would be great to see all the highest stats without the need to sort each one at a time.

thanks.

**Comment by howardchung** [comment]
Sure, I think it would be possible to add this functionality to Table and then enable it in each column definition.
