### ISSUE TITLE
 my steam account with opendota is not linked

### ISSUE THREAD

**Issue by meyard** [odota/web#1399]
I have been on opendota for more than a month, however when I want to see the analysis of my last games it appears that my last departure was 8 months ago.
I would like your support please, in what way can I link to see my games.
regards
Thank you
![asd](https://user-images.githubusercontent.com/34589719/34066465-ff403af6-e1dc-11e7-9675-b961aaaff57a.png)

**Comment by Argn0** [comment]
Make sure you have checked the "Expose Public Match Data" box in the Dota 2 options.
