### ISSUE TITLE
Drop downs scoll past end of page - not sure if material-ui

### ISSUE THREAD

**Issue by jhonnold** [odota/web#1402]
![image](https://user-images.githubusercontent.com/25160789/34081678-e39dbdda-e31e-11e7-8131-5c3e2e4c37ce.png)

As you can see the drop down goes past the page. Along with this on smaller screens when you scroll it will also go past the page, but as you scroll the selection items start to appear on a transparent background.

**Comment by howardchung** [comment]
There's a config option to limit the number of options displayed, perhaps we can use that

**Comment by jhonnold** [comment]
Sounds like a plan

**Comment by chewwybagels** [comment]
I'd like to fix this issue, it's just adding one line to the autocomplete options. This is my first time trying to contribute, how should I go about doing it?
