### ISSUE TITLE
FEATURE REQUEST - Filter based on party size

### ISSUE THREAD

**Issue by jhonnold** [odota/web#1403]
I'm not sure if this is something here or for the core, but being able to filter matches based on party size would a nice additional filter.

**Comment by howardchung** [comment]
Requires a change on both, here for the change to the filter form and in core to support the new query param.

**Comment by howardchung** [comment]
filter implementations are here: https://github.com/odota/core/blob/master/util/filter.js

**Comment by howardchung** [comment]
and probably need to add party_size to the filterDeps object: https://github.com/odota/core/blob/master/util/filterDeps.js

**Comment by jhonnold** [comment]
Alright, i'll get to this as soon as I have time (finals week right now)

**Comment by howardchung** [comment]
This should be pretty quick to do, I'll try to get it done this month.
