### ISSUE TITLE
use skeleton loaders to replace spinners

### ISSUE THREAD

**Issue by rezk2ll** [odota/web#1407]
hello, 
I think for a non-developer, it is quite confusing to see multiple loading indicators on the profile page. The user won't tell which component is loading, and which loading indicator belongs to which component.

![image](https://user-images.githubusercontent.com/6764881/34256280-7298ccca-e64c-11e7-9c38-d090af08131a.png)

I think it would be better to replace it all by a single loading progress indicator, like a bar at the top or a spinner at the center.

thanks.

**Comment by howardchung** [comment]
@blukai @Argn0 @mike-robertson is there a natural way of combining the loading states for all those components into one loading component that renders a single loading indicator?

**Comment by gu3st** [comment]
Other than an if statement that checks for multiple loading states to conditionally render based on that. 

The alternative would be to use a "skeleton" loading animation rather than a spinner which might be more elegant.

**Comment by uncledu** [comment]
it's better to use skeleton screen to replace the loading indicator

**Comment by howardchung** [comment]
Screenshot/example?

**Comment by uncledu** [comment]
refer to this:  https://github.com/dvtng/react-loading-skeleton

**Comment by howardchung** [comment]
Interesting, we could probably skeleton load the tables with rows of gray boxes (to represent table rows?) and maybe something custom for the header.

**Comment by Argn0** [comment]
I know a page that uses those skeleton loaders

https://www.gutefrage.net/frage/welchen-kaese-benutzt-man-in-pizzerien

**Comment by gu3st** [comment]
We wrote a skeleton implementation at work, but I think I wouldn't be allowed to share that.  It was fairly simple though, when loading, return the skeleton out of the component, else return the data component.

**Comment by GravityMsc** [comment]
https://github.com/danilowoz/react-content-loader
maybe this is better?

**Comment by farmasek** [comment]
I like how blueprint implements it

http://blueprintjs.com/docs/#core/components/progress/skeleton

With that, you dont need to create custom svgs for different components, but it might be more complicated to implement.

**Comment by Argn0** [comment]
I had this idea of filling the tables with dummy data while the real data is loading and blurring it out and overlaying it with a loading animation. I've never seen something like this though :D

**Comment by howardchung** [comment]
This is partially completed (match, player pages) in #1555

**Comment by howardchung** [comment]
Remaining:
* Meta page
* Matches page
* Heroes page
* Teams page
* Ranks page
* Records page
* (possibly) login widget
* Table component
