### ISSUE TITLE
Request a parse on Firefox cause the tab to crash

### ISSUE THREAD

**Issue by Odilhao** [odota/web#1408]
When i'm trying to parse one game the tab crash after the start.

I'm using Windows 8.1 and Firefox Nightly, this issue was reproduced on Firefox 57.

![ffcrash](https://user-images.githubusercontent.com/7954663/34275239-8a26818e-e683-11e7-8a53-3d0f93d8b0e2.PNG)

**Comment by howardchung** [comment]
I was not able to repro on Firefox. . . might be because it's an unstable nightly build?  Does it work fine with stable build?

Can anyone repro this?
