### ISSUE TITLE
Switch Request a Parse to modal?

### ISSUE THREAD

**Issue by ItsCEED** [odota/web#1409]
As the title says.

**Comment by howardchung** [comment]
Reasons/advantages to making this change?  Current entry points to the request page are home page and match pages.  Would it open over those pages?

**Comment by ItsCEED** [comment]
A faster access to it with no need to tabout of the Match tab. That would be grat for mobile users. The modal should be only available on Match page. To be honest would be cool to be implemented in to the Home page also.

**Comment by howardchung** [comment]
The other consideration is that sometimes we just want to link a user to opendota.com/request and say "this is how you parse a specific match id".  I'm not sure how we would handle that with a modal.

**Comment by howardchung** [comment]
I think the current model works well enough that this isn't a necessary change. . . it seems to work on mobile?
