### ISSUE TITLE
Aeon Disk isn't displayed in Match Overview

### ISSUE THREAD

**Issue by EXayer** [odota/web#1411]
Match: https://www.opendota.com/matches/3641054086
I played Dark Willow had Aeon Disk at the game end. There isn't Aeon Disk in my items list. 

![20171225194546_1](https://user-images.githubusercontent.com/11613816/34342012-66bd01ba-e9ac-11e7-80a0-4e44a1527e2b.jpg)

**Comment by howardchung** [comment]
For some reason Valve has not uploaded images for these items:
http://cdn.dota2.com/apps/dota2/images/items/aeon_disk_lg.png
http://cdn.dota2.com/apps/dota2/images/items/kaya_lg.png

**Comment by howardchung** [comment]
it seems like they've deprecated the old hero guide builder on the dota2 website?

http://www.dota2.com/workshop/builds
