### ISSUE TITLE
Wraith King deaths with reincarnation show up in story

### ISSUE THREAD

**Issue by TurnTheTideTM** [odota/web#1413]
Examples: https://www.opendota.com/matches/3649397975/story
- First teamfight, it says Wraith King was traded for 2 heroes, but he had ult and after reviving got two kills, not dying a second time. He fed no gold or xp to the enemy, his death counter didn't increase.
- 2nd teamfight after 10 minutes. WK is listed as having died twice, when in fact he died once with ult and once without, only feeding gold and xp once.

Deaths with ult should either not show up at all (like aegis), or it should be mentioned that WK used reincarnation (like "Wraithking used reincarnation once", maybe also "Phantom Assassin used aegis")

**Comment by howardchung** [comment]
Root cause is https://github.com/odota/core/issues/726

The combat log does not distinguish for aegis/reincarnation deaths.
