### ISSUE TITLE
Yasp/OpenDota not refreshing my profile.

### ISSUE THREAD

**Issue by Tartaros1** [odota/web#1415]
As the title says, the site hasn't updated my profile for over 2 months now. https://www.opendota.com/players/74222013 
Refresh button doesn't do anything for my profile. Fix this please.

**Comment by howardchung** [comment]
Did you enable Expose Public Match Data?

**Comment by Tartaros1** [comment]
Yes..

**Comment by Tartaros1** [comment]
That was the problem, ty. I've had it enabled now for 2-3 years. Don't understand why it turned off. TY
