### ISSUE TITLE
Players Record

### ISSUE THREAD

**Issue by BelousAlex** [odota/web#1433]
For example, How to get the match of the player with the most deaths?

**Comment by howardchung** [comment]
e.g. https://www.opendota.com/players/88367253/records/deaths

**Comment by BelousAlex** [comment]
can i get response type json ?

**Comment by howardchung** [comment]
https://api.opendota.com/api/players/88367253/matches?sort=deaths

**Comment by BelousAlex** [comment]
thx)
why https://api.opendota.com/api/explorer?sql=SELECT%20*%20FROM%20matches%20WHERE%20match_id%20=%203616622623 works well
and https://api.opendota.com/api/explorer?sql=SELECT%20*%20FROM%20matches%20WHERE%20match_id%20=%203721865153 does not work?

**Comment by howardchung** [comment]
if the match is not a pro match it will not be in the table.

**Comment by BelousAlex** [comment]
i checked public_matches the same response

**Comment by BelousAlex** [comment]
how can I get the details of a normal match using explorer?

**Comment by howardchung** [comment]
public matches are stored in cassandra which is not accessible via explorer.  Use the regular web API for getting specific public matches
