### ISSUE TITLE
add draft_timings data to UI

### ISSUE THREAD

**Issue by howardchung** [odota/web#1434]
@bobsaget4lyfe added draft timings data in https://github.com/odota/core/pull/1560

We can display that data on pages where:
* the draft_timings field exists
* the picks_bans field does not exist

**Comment by njgingrich** [comment]
Hey, I'm looking at implementing this, but I have a couple questions.

For match 3731587940, I'm getting back the draft data for the ban nominations, but no picks. For professional matches like 3731376121, I also get pick data.

I assume the goal is to provide something similar to dotabuff's "All Pick Nominations" section which shows the nominations and banned heroes, but I don't see any data that shows which heroes were actually banned, only that they were nominated. 

If I could get some insight into what the `active_team` parameter is as well, that may give some help - it is 0 for all the objects on match 3731587940, and either 2 or 3 for 3731376121, which doesn't correlate to radiant/dire because in that game both Radiant and Dire's first picks show an  `active_team` of 2.

**Comment by bobsaget4lyfe** [comment]
Hi mate, it inly gets the picks for captauns draft.

**Comment by bobsaget4lyfe** [comment]
How i remember it the active team is choseb dynamically from the replay. Not with a set order (so it should be able to adjust to new pick ban orders when valve changes it).

**Comment by bobsaget4lyfe** [comment]
The one the professionals play. Ok ill have to look into that.

On 14 Feb. 2018 1:22 pm, "Nathan Gingrich" <notifications@github.com> wrote:

Captain's draft or captain's mode? And even just for CM games the data I
have for that example match doesn't line up as I showed above, so I'm not
sure what's happening there.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/odota/web/issues/1434#issuecomment-365474736>, or mute
the thread

**Comment by bobsaget4lyfe** [comment]
Is that match the "test" game cause that is an old match.

**Comment by njgingrich** [comment]
That's the most recent Evil Geniuses game - https://www.opendota.com/matches/3731376121.

**Comment by bobsaget4lyfe** [comment]
Yeh ok it is getting the active team wrong. Here is the table for reference between the two.

|  picksandbans | | | | drafttimings | |  | |
|:-------|-------:|----:|-----:|-----:|:-----|-----------:|-------:|
|is_pick | hero_id| team| order| order|pick  | active_team| hero_id|
|:-------|-------:|----:|-----:|-----:|:-----|-----------:|-------:|
|FALSE   |      43|    1|     0|     1|FALSE |           2|      43|
|FALSE   |      62|    0|     1|     2|FALSE |           3|      62|
|FALSE   |      38|    1|     2|     3|FALSE |           2|      38|
|FALSE   |      19|    0|     3|     4|FALSE |           3|      19|
|FALSE   |      86|    1|     4|     5|FALSE |           2|      86|
|FALSE   |      57|    0|     5|     6|FALSE |           3|      57|
|TRUE    |      89|    1|     6|     7|TRUE  |           2|      89|
|TRUE    |      91|    0|     7|     8|TRUE  |           2|      91|
|TRUE    |      72|    0|     8|     9|TRUE  |           3|      72|
|TRUE    |      13|    1|     9|    10|TRUE  |           2|      13|
|FALSE   |      87|    0|    10|    11|FALSE |           3|      87|
|FALSE   |      45|    1|    11|    12|FALSE |           2|      45|
|FALSE   |      12|    0|    12|    13|FALSE |           3|      12|
|FALSE   |      77|    1|    13|    14|FALSE |           2|      77|
|TRUE    |       3|    0|    14|    15|TRUE  |           3|       3|
|TRUE    |      64|    1|    15|    16|TRUE  |           2|      64|
|TRUE    |      92|    0|    16|    17|TRUE  |           3|      92|
|TRUE    |      76|    1|    17|    18|TRUE  |           2|      76|
|FALSE   |     109|    0|    18|    19|FALSE |           3|     109|
|FALSE   |      88|    1|    19|    20|FALSE |           3|      88|
|TRUE    |      95|    1|    20|    21|TRUE  |           2|      95|
|TRUE    |      33|    0|    21|    22|TRUE  |           2|      33|

**Comment by howardchung** [comment]
The picks_bans array should be present for CM games and that should be used if available (this is already implemented).

The draft_timings is meant to be used for tracking picks/bans in all pick drafts, but I don't think the picks are being returned right now, only the bans.

@bobsaget4lyfe the parser only extracts the data for CM games right now?  does the same approach work for all pick games?

**Comment by bobsaget4lyfe** [comment]
@howardchung draft_timings only works for CM. The field that returns the bans in All Pick in the parser does not return the picks in All Pick only in CM.

There must be another field that returns picks for All Pick games.

**Comment by njgingrich** [comment]
Thanks guys - to check on the desired behavior, is the ultimate goal to get draft_timings working for All pick games and showing that data there, which will look similar tot he picks_bans implementation for CM games?

**Comment by bobsaget4lyfe** [comment]
draft_timings was only developed with CM in mind. I was thinking it would be fascinating to see how time is used in the drafting time. The only extra information over picks_bans is the time and extra time used for each stage of the draft. We use to store extra time taken in the database but removed it for client side calculation.

To implement draft timings for all pick we would probably have to use an OnMessage and then create a new class to parse that information in core. The fields I use for draft_timings in the parser do not work for all pick games. 

I dont know if Howard will agree but I personally think for CM games we could use this information to have a specific draft page. People can view how the draft unfolded, with heroes picked and banned with time taken for each stage and how much extra time was used up.

**Comment by njgingrich** [comment]
I actually created a mock of a draft page on a local branch, I can develop that more and add a PR in a few days if that seems like a good path to follow.

**Comment by bobsaget4lyfe** [comment]
That sounds good to me. I need to test my update to processDraftTimings.js to see if it is now working as intended. I made a pretty big mistake having the active teams being incorrectly assigned.

**Comment by bobsaget4lyfe** [comment]
Hi mate. If we want to calculate extra time taken we might want to include some of this code. I am removing it from core because we do not need it there.

`for (let j = 0; j < draftTimings.length; j += 1) {
    const pnb = draftTimings[j];
    const team = pnb.active_team;
    let previousorder = 0;
    // find previous pick or ban from that team
    for (let i = 0; i < draftTimings.length; i += 1) {
      const currpick = draftTimings[i];
      if (currpick.order < pnb.order && currpick.order > previousorder &&
          currpick.active_team === team) {
        previousorder = currpick.order;
      }
    }
    // If there are no previous orders for team do
    if (previousorder === 0 && pnb.order === 1) {
      draftTimings[j].extra_time_taken = (130 - pnb.extra_time);
    } else if (previousorder === 0 && pnb.order !== 1) {
      let index2;
      // find the time of the end of the previous order
      for (let i = 0; i < draftTimings.length; i += 1) {
        if (draftTimings[i].order === (pnb.order - 1)) {
          index2 = i;
        }
      }
      // calculate the timings
      draftTimings[j].extra_time_taken = (130 - pnb.extra_time);
    } else {
      let ind;
      // find which row is the previous order
      for (let i = 0; i < draftTimings.length; i += 1) {
        const currpick = draftTimings[i];
        if (currpick.order === previousorder) {
          ind = i;
        }
      }

      // calculate the timings
      // const pastpicks = draftTimings[ind];
      // draftTimings[j].extra_time_taken = (pastpicks.extra_time - pnb.extra_time);
    }
  }`
