### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by mike-robertson** [odota/web#144]
We need to add unit tests since the code base is becoming quite large, and since we all have our own 'domains' that we work on, changes to components across domains can cause subtle bugs (if we don't have unit tests). I think that the #1 priority after completing MVP should be to go back and add useful unit tests for everything since we don't have any dedicated QA contributors or QA process.

**Comment by Roshanjossey** [comment]
@mike-robertson: I'd love to work on this. I'm very much aligned to TDD and unit testing. Do you have a testing framework in mind? I've used mocha, chai and enzyme to test components. I also had a really bad time trying to use Jest.

**Comment by howardchung** [comment]
odota/core uses mocha.  I think it'd be helpful to use the same one on both.

**Comment by mike-robertson** [comment]
I agree that mocha/chai/enzyme is the easiest testing 'stack' to use with react.

**Comment by dartharaknus** [comment]
We also need e2e testing, http://nightwatchjs.org/

**Comment by howardchung** [comment]
https://www.browserstack.com/ is another option.  I've never tried setting this kind of thing up, so feel free to tackle this if you have any experience.

**Comment by Roshanjossey** [comment]
@howardchung: As far as I understand, browserstack is a paid service, do we have enough bandwidth to use it?
@dartharaknus: nightwatchjs looks pretty cool. Have you used it? Looking forward to work with it

**Comment by howardchung** [comment]
They are free for open source projects (need to submit a request):
https://www.browserstack.com/pricing

**Comment by howardchung** [comment]
@Roshanjossey are you still interested in improving test coverage?  @mike-robertson laid out the foundation and wrote a couple of quick tests, but the majority of components still don't have them.

**Comment by masad-frost** [comment]
https://facebook.github.io/jest/ is worth considering

**Comment by Roshanjossey** [comment]
@howardchung, @mike-robertson, I'm sorry I couldn't take a look at this earlier. I'll get started on this.

How should I divide work? I'd like to submit PRs in smaller chunks rather than doing it all at once

**Comment by howardchung** [comment]
Maybe just add one test for one component at a time.

**Comment by masad-frost** [comment]
I wrote on discord, but might be better to say it here. We should probably be using selenium as our web driver now that browserstack is looking to support us https://www.browserstack.com/automate

**Comment by Tb0** [comment]
Hello everyone,
I am a QA engineer Dota2 fan, and I would be happy to help you on automating End to End tests using the selenium webdriver in JS. That would be the easiest way to integrate E2E tests to the current stack of technology. Ping me if you are interested in :)

**Comment by howardchung** [comment]
@Tb0 would love to see E2E tests added!  @masad-frost set up an account for us on BrowserStack, let me know if you need access to that.

Also apparently Chrome 59 has a headless mode which is supposed to make CI testing easier.

**Comment by howardchung** [comment]
Now that the project is a standard `create-react-app` project you can use their testing convention, based on Jest:

https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#running-tests

**Comment by Luchanso** [comment]
I suggest use [puppeteer](https://github.com/GoogleChrome/puppeteer), but it's not unit-test its E2E test. You can compare screenshots like in [Codesandbox](https://hackernoon.com/how-codesandbox-uses-puppeteer-jest-to-test-sandbox-functionality-17068b3bd23b)

**Comment by howardchung** [comment]
I think that's more https://github.com/odota/web/issues/1596

**Comment by howardchung** [comment]
We have a few e2e tests. . . not sure we'll get more than that but happy to accept contributions
