### ISSUE TITLE
add scenarios page

### ISSUE THREAD

**Issue by howardchung** [odota/web#1440]
@Argn0 has implemented the data collection for this feature.

See https://github.com/odota/core/issues/1575 for details.

We should decide how we want to display this data.

I'm thinking:

* A selector to pick the hero that we want to view scenarios for
* Make a web request that returns the scenarios for that hero.
* Have a multi-column display that shows, e.g.
  * One column showing win rates for first blood, lane, etc.
  * One column showing win rates for each item picked up at each interval
  * One column showing win rates for each ping, game duration bucket, chat messages

I am not sure how best to display team scenarios, these seem like values that are the same for each hero, so might just be displayed elsewhere on the page.

**Comment by Argn0** [comment]
Those team scenarios are fun little facts so I thought about displaying them in a similar manner like here https://physioneeds.biz/media/wysiwyg/tennis-elbow-stats.jpg for example
