### ISSUE TITLE
Uncalibrated MMR shows as 0 on MMR graph until being calibrated.

### ISSUE THREAD

**Issue by scritous** [odota/web#1443]
It's not possible to show or track MMR in-game since 7.07 but the MMR of the accounts which showed MMR before the 7.07 is still trackable through dota api. After I calibrated solo MMR, graph was regularly updated but my party mmr recorded as 0 even though it was just uncalibrated. Also it's not possible to have mmr lower than 1. I think hiding MMR if its below 1 should be solution.

![graph](https://user-images.githubusercontent.com/36240681/35933122-b661f48a-0c4a-11e8-9314-844ca36c675c.png)

**Comment by howardchung** [comment]
Thanks for the report!  This should be fixable on the client side.
