### ISSUE TITLE
Search Keyword on Search Bar is missing after refresh

### ISSUE THREAD

**Issue by jojo-tutor** [odota/web#1447]
### Steps to reproduce:
1. Go to https://www.opendota.com/
2. Click on the **Search Bar** and type **"miracle"**
3. After results have been loaded.. **Refresh** the browser.

### Expected result:
Search Bar should retain the **"miracle"** keyword.

### Actual result:
Search Bar has no keyword.

![opendota-2](https://user-images.githubusercontent.com/18729213/36238252-67054bba-123c-11e8-8e06-edc83abc0d98.jpg)

**Comment by howardchung** [comment]
I think it's this line that does this:

**Comment by jojo-tutor** [comment]
@howardchung , It's making the app inconsistent. It's also filtering the search keyword in this case, and in user's perspective, it's weird, since there is no search keyword but the app filters the keyword in the url.

**Comment by howardchung** [comment]
Yeah, I agree, let's remove that exception
