### ISSUE TITLE
Parse bug (replay parsing)

### ISSUE THREAD

**Issue by dennisie123** [odota/web#1449]
I visit the website at least once a day, and on my profile it also says that 'I have visited recently, and all of my replays will be parsed automatically'. It has always done this, but the replays of all my games from today are not parsed for some reason, I had one manually parse but the other manual parses dont seem to follow through either for some reason. I don't know how this has come to be or if it perhaps may be something from my side but I look at my parsed games a lot so I'd love to do that with these games as well :D

**Comment by howardchung** [comment]
The parse queue is backed up right now, I'll keep monitoring and hope it gets resolved soon.

**Comment by justmeeee** [comment]
How much is the queue backed up? I manually wanted to parse this game last thursday and retried it on friday, but still no result: https://www.opendota.com/matches/3659980252

**Comment by howardchung** [comment]
Queue is empty now.  However that match's replay is no longer available (they expire in 10 days)
