### ISSUE TITLE
Suggestion: Add a filter option to the average/maximum

### ISSUE THREAD

**Issue by RaPoZaUm** [odota/web#1461]
Pretty much the title.

Playing a few turbo matches amidst the majority of normal one effs the averages...

**Comment by Argn0** [comment]
Try this button. Do you mean this?

![turbofilter](https://user-images.githubusercontent.com/29599118/36753181-bc832508-1c05-11e8-90e9-d619e0d12835.jpg)

**Comment by RaPoZaUm** [comment]
I feel bad now. Sorry. Closing it. Would delete if I could.
