### ISSUE TITLE
Opendota doesnt see my plays

### ISSUE THREAD

**Issue by ars111** [odota/web#1476]
![image](https://user-images.githubusercontent.com/37217524/37211989-2b5d2c8a-23c7-11e8-8948-a474b22d05fb.png)
I see only my rank

**Comment by coreymaher** [comment]
@ars111 have you enabled "Expose Public Match Data" in the dota settings?

**Comment by ars111** [comment]
thank you)

**Comment by ars111** [comment]
@coreymaher yes

**Comment by ars111** [comment]
@coreymaher but it doesnt work

**Comment by coreymaher** [comment]
Once you enable the "expose public match data" setting in dota, you can hit the "Refresh" button on the page there to load all of your previous matches.
Any matches in the future will be automatically loaded.

**Comment by ars111** [comment]
@coreymaher yes,they are appeared thank you

**Comment by coreymaher** [comment]
Glad I could help.
