### ISSUE TITLE
Ridiculous numbers in combat->kills section (ranked)

### ISSUE THREAD

**Issue by Algebrae** [odota/web#1481]
https://www.opendota.com/matches/3779157609/combat
idk if these numbers will get changed somehow later, but re-parcing haven't helped me; in case that this will be actually have different numbers later, i'm leaving screenshot: https://gyazo.com/f4d86e4a6afc399de573095dfbd9bd8a
that was ranked match, not one with bots

**Comment by coreymaher** [comment]
AM getting 1 kill and dying 4.4k times? Looks correct to me ;)

I've seen the same issue in every match I've looked at since the Dota Plus release.

**Comment by howardchung** [comment]
Yeah, this seems to be happening all over the place, likely something changed in the replay file causing the parser to output way too many kill events.  I'll grab a replay and check

**Comment by howardchung** [comment]
OK, I found the issue.  The combat log now contains a "value" field that has an integer in it.  Currently if that field exists, core will treat it as that value, so the kills are getting incremented by that value.  example line:

```
{"time":345,"type":"DOTA_COMBATLOG_DEATH","value":47,"attackername":"npc_dota_hero_antimage","targetname":"npc_dota_creep_badguys_melee","sourcename":"npc_dota_hero_antimage","targetsourcename":"npc_dota_creep_badguys_melee","attackerhero":true,"targethero":false,"attackerillusion":false,"targetillusion":false,"inflictor":"dota_unknown"}
```

Probably that value means something, but for now the fix is to set that value to 1.

**Comment by howardchung** [comment]
fixed in https://github.com/odota/core/commit/2a1c4089deab38c77637175c0662317fdb5f5571

**Comment by howardchung** [comment]
You can request a reparse of any affected matches to fix the issue once the code is deployed (within 24 hours)
