### ISSUE TITLE
Hero Kills and Unit Kills numbers not showing properly 

### ISSUE THREAD

**Issue by FriskDreemur** [odota/web#1482]
![image](https://user-images.githubusercontent.com/37368940/37399656-3e6d79c0-27bd-11e8-84f4-99a5e4d2aec5.png)

![image](https://user-images.githubusercontent.com/37368940/37399669-49a8c434-27bd-11e8-9ff4-55f206daa83d.png)

**Comment by Argn0** [comment]
Was fixed already. I re-parsed the match and now it shows the correct numbers.

https://www.opendota.com/matches/3779867703/combat
