### ISSUE TITLE
extra match stats wont show up.

### ISSUE THREAD

**Issue by Grumblemench** [odota/web#1483]
I cannot access the wordcloud, wardmap, rankings etc.  I suspect it's because of a corrupted replay or something I was directed to post on here.  I have played games recently, even after creating an account.  Please help I just want to see my word cloud :.....(

**Comment by coreymaher** [comment]
@Grumblemench are you just unable to see your own profile, or are you unable to see anyone's profile?
Also is your account public and is the "Expose Public Match Data" setting enabled in dota?

**Comment by Grumblemench** [comment]
I am able to see my friends profiles.  My account is public and the "Expose Public Match Data" setting is enable.  Thanks for the quick response.

**Comment by coreymaher** [comment]
Hmm that's strange. Can you share your steam id so I can look it up?

**Comment by Grumblemench** [comment]
45061254 is my friend id if thats what you mean

**Comment by Grumblemench** [comment]
Also I can now see info from my most recent games that I played last night.

**Comment by coreymaher** [comment]
opendota can only generate wordcloud, wardmaps, etc for matches that are parsed. It also only parses matches for signed up users.

I assume you signed up recently? Or exposed your public match data recently?
If so then only your new matches will be parsed automatically.

You can go back through your old matches and hit the "Re-parse" button to request a re-parse, although opendota can only re-parse matches that still have a replay. Valve deletes match replays after a week or so.

**Comment by coreymaher** [comment]
Although there does seem to be a problem with the "parsed" icon.
@howardchung if you take a look at https://www.opendota.com/players/45061254/overview it's not showing this match as parsed: 3779866615
But if you navigate to that match page, it is parsed. https://www.opendota.com/matches/3779866615

Looking at the API response, `players/45061254/recentMatches` is showing `version: null` while `matches/3779866615` is showing `version: 21`

Any idea what could be causing that?

**Comment by howardchung** [comment]
I requested a reparse and it seems to have fixed the issue.

The data comes from two different cassandra tables, so it's possible that one write succeeded but the other failed (cassandra doesn't have transactions).
