### ISSUE TITLE
show ability information on hero pages

### ISSUE THREAD

**Issue by mickelsonmichael** [odota/web#1488]
Add more information to each hero's `heroes/#` page

- Spells and their information (mana cost, description, etc.)
- Commonly purchased items and their win rates

This could be built out as new tabs or pages, or it could even just be a large link to one of the Wiki pages

___

Along the same vein, it would also be good to have a link to each hero's page on the match overview tab. Even something as simple as wrapping the hero's portrait in a link

**Comment by howardchung** [comment]
Spells i think are in the hero data and we can do.

Commonly purchased items we aren't currently collecting data for, but could look into it.  I'm not really sure end-game item win rates are very useful, since expensive items tend to have very high win rates.

**Comment by mickelsonmichael** [comment]
That's true, in that case it could be interesting to see the average purchase time. For example, Battlefury on Anti-Mage; at what time does the average person buy the item? This would be mostly significant for early game items with important timings (radiance, boots, battle fury, etc.)

Would really just be a cool feature, but probably lower priority than others

**Comment by bdbch** [comment]
I would like to look into this. Not sure about showing the average buy time but I would like to add the abilities to the new hero header.

**Comment by bdbch** [comment]
@howardchung would that potentially need changes in core or is the ability data already included in the hero/herostats endpoint?

**Comment by howardchung** [comment]
https://github.com/odota/dotaconstants/blob/master/build/hero_abilities.json maps heroes to their abilities and talents

https://github.com/odota/dotaconstants/blob/master/build/abilities.json lists full ability info.

We may want to import these dynamically to avoid the need to load them as part of the main JS bundle (using import())

**Comment by bdbch** [comment]
Alright. I'll look into it for now! Thanks for the resources over at dotaconstants.

**Comment by bdbch** [comment]
Sorry for the longer off-time. Had some private stuff to manage. I'm making good progress here. Looking forward to finish it in the next hour.

4 Skills:
![image](https://user-images.githubusercontent.com/6538827/41192537-96e9c078-6bff-11e8-81fc-00b89345fb87.png)

Invoker:
![image](https://user-images.githubusercontent.com/6538827/41192547-b5fd5c54-6bff-11e8-8815-cc3814ba5f64.png)

Tooltip (WIP):
![image](https://user-images.githubusercontent.com/6538827/41192549-bf4038f4-6bff-11e8-810b-c9f96ae23dc3.png)

Just need a good solution for the Talents tooltip. Going to take inspiration from the official Dota design.

**Comment by bdbch** [comment]
Sorry for the delay again. I almost finished this. I just worked on it when suddenly my whole www folder got removed. :( So my last changes for the talents tooltip/icon are gone. Damn.

I'll update you as soon as a PR is ready!

**Comment by bdbch** [comment]
PR is ready #1625

**Comment by mickelsonmichael** [comment]
Awesome! Thanks so much for all you hard work, can't wait to see the changes live

**Comment by bdbch** [comment]
@mickelsonmichael check it out on staging already! 👍 

https://deploy-preview-1559--opendota-stage.netlify.com/heroes

**Comment by mickelsonmichael** [comment]
Beautiful! A great addition to the site
