### ISSUE TITLE
Highlight "self" row sometimes incorrect on teamfights page

### ISSUE THREAD

**Issue by coreymaher** [odota/web#1499]
There seem to be cases where the "highlight self feature" on the team fights page, highlights more than just you.
From the testing I've done, it appears that once a row is highlighted, it doesn't unhighlight again if you click on a different team fight. This is fine if you are always in the same row in the table, but causes issues if you are not.

This clears up if you click on a teamfight which doesn't contain the highlighted row, but that is only more common if you are on one of the lower rows.

**Comment by Argn0** [comment]
Hey, thanks for the good description of the issue. I pushed a potential fix.
