### ISSUE TITLE
replace UNSAFE_ React lifecycles with new ones for React 16.3

### ISSUE THREAD

**Issue by howardchung** [odota/web#1503]
As detailed in this post:
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by hawkins** [comment]
Looks like this was fixed in #1529, right?

**Comment by howardchung** [comment]
No, that only renamed the names to the UNSAFE_ aliases to make them easier to find and update.

**Comment by hawkins** [comment]
Whoops, my mistake; good catch. Just found the repo and was looking through issues for ways to help out, and I wasn't sure if there was work left to be done on this one. Thanks! 🙂

**Comment by howardchung** [comment]
Looks like componentWillMount should be replaced with componentDidMount and componentWillUpdate should be replaced with getSnapshotBeforeUpdate (or maybe componentDidUpdate)

**Comment by howardchung** [comment]
apparently these new methods are in 16.3, so we can actually start swapping them over now.

**Comment by howardchung** [comment]
Updated the title to more accurately reflect the task
