### ISSUE TITLE
A party rank of "0" renders as the string "0".

### ISSUE THREAD

**Issue by coreymaher** [odota/web#1506]
See: https://www.opendota.com/players/120696537

![screen shot 2018-03-29 at 1 59 31 am](https://user-images.githubusercontent.com/100885/38072563-e3adfdaa-32f4-11e8-9ac9-a45bcf2c1f8c.png)

It appears the API responds with `competitive_rank: 0` for this player, which the interface is rendering as just the string "0" without any labels or formatting.

It should probably have logic like the estimated mmr to ignore 0 values.

**Comment by howardchung** [comment]
0 isn't a valid MMR value, so I just purged 0 values from the database.

**Comment by coreymaher** [comment]
That works too, thanks!
