### ISSUE TITLE
Invoker spells don't show up in Teamfights

### ISSUE THREAD

**Issue by builder-247** [odota/web#1507]
Only quas, wex and exort uses are displayed in the abilities section of the Teamfights tab.

[Example match](https://www.opendota.com/matches/3799773485/teamfights)

**Comment by howardchung** [comment]
Are you sure invoker cast a spell in that fight?  Spells seem to be showing up in the Casts tab which uses the same data.

**Comment by builder-247** [comment]
I'm 100% positive on that - it doesn't show the spells in any fights and I invoke several spells each fight.

**Comment by howardchung** [comment]
Looks like the data was there all the time, just wasn't showing on the UI
