### ISSUE TITLE
'Actions' button is broken in parsed matches.

### ISSUE THREAD

**Issue by AaronH99** [odota/web#1511]
Clicking through the subheadings of a parsed match it's obvious that page names have a standard format on this site. For example;

https://www.opendota.com/matches/xxxxxxxxxx/overview (where the x's are a match ID)

However when you click the Actions button on any parsed game it now directs you to;

https://www.opendota.com/actions

This is a blank page that doesn't correspond to any game. I've tried just replacing the end of the URL with /actions to follow the standard format, so like this;

https://www.opendota.com/matches/xxxxxxxxxx/actions

but this doesn't show anything either apart from 3 new subheadings - Fantasy, Chat & Story. (These work as expected when you click them) Though none contain the actions data, so  I can't view a breakdown of actions of any specific game. I've been using these breakdowns in my dissertation, which I last worked on on Friday morning, and this feature worked fine then. So an update between Friday morning and now (Sunday April 1st) seems to have broken it.

**Comment by howardchung** [comment]
Thanks for spotting this!  Made the fix
