### ISSUE TITLE
SEA replays are missing

### ISSUE THREAD

**Issue by Noname932** [odota/web#1521]
Not sure if this is the place to report this, but since ranking up from Crusader (5) to Archon (0), my recent matches in Archon stopped being parsed. Has this happened before? and is there a way to fix it?

EDIT from @howardchung:
We can't do anything about this, Valve needs to fix the issue so the replay files are accessible.

**Comment by coreymaher** [comment]
@Noname932 are you logged in?
Your profile should have this icon:
![screen shot 2018-04-10 at 10 57 20 am](https://user-images.githubusercontent.com/100885/38564870-032c9c64-3cae-11e8-9391-bf0e058d7c73.png)
If you do then your games will be parsed automatically.

If instead you have this icon:
![screen shot 2018-04-10 at 10 58 22 am](https://user-images.githubusercontent.com/100885/38565029-4891b82a-3cae-11e8-95c4-086631d74cac.png)
Then you have not logged in within the last 2 weeks and your matches will not be parsed automatically.

**Comment by Noname932** [comment]
@coreymaher 
Of course I have been logged in (everyday, in fact), and it also have the icon you mentioned, here is the link: https://www.opendota.com/players/131846739

**Comment by coreymaher** [comment]
@Noname932 Unfortunately it looks like this is a valve issue. If you go to each of those unparsed matches and hit the replay button you'll see it says "not found".

Apparently valve is losing all your match replays 😕

**Comment by vsrnth** [comment]
Same issue with me too.

**Comment by coreymaher** [comment]
@vsrnth Are you also playing in the Singapore region? I wonder if valve is having trouble with their Singapore servers.

**Comment by coreymaher** [comment]
Looks like others are noticing this as well: https://www.reddit.com/r/DotA2/comments/8b8cej/sea_server_replays_not_available/

**Comment by howardchung** [comment]
are replays still missing?

**Comment by vsrnth** [comment]
replays are back now.
