### ISSUE TITLE
Faceless Void ability casts showing wrong image

### ISSUE THREAD

**Issue by Aeryan** [odota/web#1527]
In the Casts section of match 3831300358 Faceless Void's Time Dilation casts don't have the background image of Time Dilation, but rather the red version of Backtrack.

**Comment by howardchung** [comment]
likely related to #1454 , where Valve has outdated images for some abilities saved

**Comment by howardchung** [comment]
http://cdn.dota2.com/apps/dota2/images/abilities/faceless_void_time_dilation_lg.png is the image in question

**Comment by howardchung** [comment]
merge with #1454
