### ISSUE TITLE
Use smaller map image

### ISSUE THREAD

**Issue by howardchung** [odota/web#1545]
The 7.07 map image is 1.2MB.  We should make it smaller/find a more efficient compressed format.

**Comment by howardchung** [comment]
Image in question:
https://github.com/odota/web/blob/master/public/assets/images/dota2/map/detailed_707.png

We should also update the earlier images although this is less important:
https://github.com/odota/web/blob/master/public/assets/images/dota2/map/detailed_700.png
https://github.com/odota/web/blob/master/public/assets/images/dota2/map/detailed_686.png
https://github.com/odota/web/blob/master/public/assets/images/dota2/map/detailed_682.png
https://github.com/odota/web/blob/master/public/assets/images/dota2/map/detailed_pre682.png

**Comment by howardchung** [comment]
Couple of quick attempts with Paint 3D:
50% PNG: 342KB
50% JPG: 65KB

![detailed_707](https://user-images.githubusercontent.com/3134520/39404431-f2244072-4b47-11e8-99bc-32c4a9c986c5.png)
![detailed_707](https://user-images.githubusercontent.com/3134520/39404432-f238a116-4b47-11e8-933d-28570f2fe54a.jpg)

**Comment by bdbch** [comment]
I would pick this one up. Going to run it through compressing tools. What do you think about an alternative WebP version (if supported) @howardchung?

**Comment by howardchung** [comment]
Sure, if we can determine which to show in the React app.  Not sure if that's possible as I haven't tried using webp images before

**Comment by bdbch** [comment]
JPEG is at ~140kb right now. Should I use 50% for compression? I sticked with 80% for now.

**Comment by howardchung** [comment]
preview of how it looks at both?

**Comment by bdbch** [comment]
@howardchung I tried out 50% and wasn't really able to see a difference to the current ones. Used 50% so now we're at 90kb - 100kb.
