### ISSUE TITLE
Unable to select latest patch from Explorer Interface

### ISSUE THREAD

**Issue by belmegatron** [odota/web#1563]
Just noticed that you can't select Patch 7.14 (latest patch) from the drop-down menu available on the Explorer Interface - https://www.opendota.com/explorer

However, if I go to https://www.opendota.com/explorer?maxPatch=7.14&minPatch=7.14 then I can view the correct result. If I type the query in SQL using your Toggle SQL functionality then this also works!

Just thought it might be worth noting.

**Comment by Argn0** [comment]
I can see patch 7.14 on the master branch. Doesn't work correctly on the current production branch for some reason.

**Comment by howardchung** [comment]
The production branch hasn't been updated yet, it should update with the next release.

**Comment by Argn0** [comment]
fixed now
