### ISSUE TITLE
Datos

### ISSUE THREAD

**Issue by FelipeCHM** [odota/web#1581]
**Explain your question as detailed as possible**

I need help with...
(spanish) necesito ayuda con la web por que no se se actualiza mi perfil con mi rango ni nada. aparece en blanco.
---

If you have a support request or question please also check our Discord Server: https://discord.gg/opendota

**Comment by Argn0** [comment]
Did you enable "Expose Public Match Data" in Dota 2 options?

**Comment by FelipeCHM** [comment]
Si lo puse publico ahora pero el mmr ni la medalla se actualiza

**Comment by Argn0** [comment]
play a ranked match and it should update

**Comment by howardchung** [comment]
Please let us know if enabling public match data does not resolve the issue.
----
Indíquenos si la habilitación de los datos de coincidencia pública no resuelve el problema.
