### ISSUE TITLE
Broken wardmaps display

### ISSUE THREAD

**Issue by l7ssha** [odota/web#1587]
Wardmaps behave very weird. Points are not over map, but somewhere else. 

It has been broken since the last update, before it was fine.

**Environment**
- Browser Version: Opera 53
- OS: Arch Linux,  KERNEL: 4.16.9-1-ARCH, WM: Openbox

![image](https://user-images.githubusercontent.com/23033957/40276687-e016bca0-5c10-11e8-8ae4-bd572f5f0bb3.png)

![image](https://user-images.githubusercontent.com/23033957/40276689-e94d38ee-5c10-11e8-97f4-a8f7eba45388.png)

**Comment by howardchung** [comment]
@bdbch I think this might have to do with the minimap image update?

**Comment by howardchung** [comment]
https://github.com/odota/web/pull/1567/files

I think the inner MapImage div might need the sizing props passed down to it?  Also appears the heatmap or map z-index needs to be adjusted so the heatmap is overlaid properly on top of the map image.
