### ISSUE TITLE
Captains Mode Ban Order

### ISSUE THREAD

**Issue by mason-schulze** [odota/web#1602]
**Current Behavior**
The second phase bans if viewing a captains mode match are listed in the old order, with first pick getting the second and fourth ban of the phase, and second pick getting the first and third

**Expected behavior/code**
The order got flipped in 7.15 to second pick having the second and fourth ban of the second phase, and first pick having the first and third

**Console Output**
Doesn't apply

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
https://imgur.com/Zf2AmEQ incorrect order

**Comment by howardchung** [comment]
Thanks, think we just need some logic that changes the display based on match date/patch number

**Comment by howardchung** [comment]
page with the issue:
https://www.opendota.com/matches/3925656530/draft

viper and PL bans are shown on the incorrect side

**Comment by howardchung** [comment]
I think these arrays need to be updated:
https://github.com/odota/web/blob/master/src/components/Match/Draft/Draft.jsx#L177

**Comment by howardchung** [comment]
originally implemented by @njgingrich in https://github.com/odota/web/pull/1448
