### ISSUE TITLE
unusually wide table column

### ISSUE THREAD

**Issue by howardchung** [odota/web#1607]
**Current Behavior**
The damage dealt column is unusually wide, making the received column too narrow.

**Expected behavior/code**
Better spacing

https://www.opendota.com/matches/3930369369/combat

**Comment by howardchung** [comment]
similar issue on casts table:
https://www.opendota.com/matches/3973436245/casts

**Comment by howardchung** [comment]
@Argn0 did you want to look at this?

**Comment by Argn0** [comment]
Sure, I'll try.
