### ISSUE TITLE
how can i translate wardmap Api ? any docs?

### ISSUE THREAD

**Issue by LordVersA** [odota/web#1617]
how can i translate wardmap Api ? any docs?
how can i convert wardmap number to 1024 image scale?

**Comment by howardchung** [comment]
X/Y coordinates are given as described in this page:
https://github.com/odota/core/wiki/JSON-Data-Dump

The range for each is around 64-192, with 64,64 being the lower left corner.

**Comment by LordVersA** [comment]
tnx alot ,
