### ISSUE TITLE
I think hero rankings are getting something the wrong way round.

### ISSUE THREAD

**Issue by ReallyMadCow** [odota/web#1626]
**Current Behavior**
Hero's that I have 10 games on and 36% win rate are being rated top 60% in open dota rankings but heroes I have 46 games and 63% win rate on are bottom 1%.

**Expected behavior/code**
The opposite of above 

**Console Output**
Not really applicable but:

VM52:3 Uncaught TypeError: Cannot read property '_avast_submit' of undefined
    at <anonymous>:3:28
    at <anonymous>:32:19
q.stripe.com/?event=checkout.config.summary&rf=&sc=&optchecker-origin=configure&optchecker-numErrors=0&optchecker-numWarnings=0&distinct_id=45cf1ea5-a936-2cdb-de09-6735dff5b4fb&eventId=75839f3e-fa10-746c-b368-30fb3e0a60d6&option-key=pk_live_zFUQR74N5mWV4yZpImL6ouH6&h=1080&w=1920&lsid=c8b4cddf-e55a-498d-ae94-61f230097e7e&cid=3cd0fbd6-683a-4854-9156-e43a7829df0d&i=1529126522897:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
q.stripe.com/?event=checkout.outer.manhattanStatus&rf=&sc=&isEnabled=true&distinct_id=45cf1ea5-a936-2cdb-de09-6735dff5b4fb&eventId=01936d8f-d569-2157-4645-e1d66fdfdd5a&option-key=pk_live_zFUQR74N5mWV4yZpImL6ouH6&h=1080&w=1920&lsid=c8b4cddf-e55a-498d-ae94-61f230097e7e&cid=2144f9d6-f1d1-42f8-a460-45daf8b62a8b&i=1529126523653:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Environment**
- Browser Version: Chrome Version 67.0.3396.87 (Official Build) (64-bit)
- OS: Windows 10 Home 64-bit (10.0 Build 17134)

**Possible Solution**
N/A

**Additional context/Screenshots**
In Game stats:
https://i.imgur.com/Y121iFj.jpg
https://i.imgur.com/qZMHFup.jpg

Open Dota rankings:
https://i.imgur.com/oKm6WEa.png
https://i.imgur.com/VxkaaGM.png

**Comment by howardchung** [comment]
When did you start playing?  It's possible that some of your games were from before the rankings started.  Games played before that don't count.

**Comment by ReallyMadCow** [comment]
2014 really, Here is my activity map from dotabuff (sorry you guys dont have one). https://i.imgur.com/RFrOwMi.png But more specifically if we take the worst cases my Axe (ranked in the bottom 1% with 63% wr), I played 30 of the games this year https://i.imgur.com/JzlQB9S.png but my Sven (ranked top 55% with with 36% wr) I played only 3 games in the last year and before that was 2 years ago, https://i.imgur.com/DQ931YK.png . Hope this helps.
