### ISSUE TITLE
Edit Documentation

### ISSUE THREAD

**Issue by ljl7123** [odota/web#1640]
My university technical writing course has an assignment which involves editing documentation on GitHub repositories as practice in real world settings. Edits may involve aspects like style, structure, and concision.

Existing style guidelines would be taken into account. The following is one of the resources I would be using:
https://jacobian.org/writing/technical-style/

Would anyone mind if I propose edits to documentation in this repository? It would really help me out!

**Comment by howardchung** [comment]
Sure, go ahead! The API documentation is in the odota/core repo in the routes/spec.js file.  If you want to improve the READMEs you can do that as well

**Comment by howardchung** [comment]
I'll close this issue since there isn't a specific work item but feel free to submit a PR with improvements!
