### ISSUE TITLE
Underhollow event matches all showing as losses and counting towards overall winrate percentage

### ISSUE THREAD

**Issue by PrincessTamer** [odota/web#1641]
As somebody that valued the winrate shown on opendota as a sign of progress, underhollow has negated this entirely. Is there a way to separate event games and normal matches from winrate? In the same way that custom games such as overthrow dont count towards winrate on opendota.
Thanks

**Comment by howardchung** [comment]
Hey, do you have a link to a profile where this is happening?

**Comment by PrincessTamer** [comment]
https://www.opendota.com/players/201940161

The games which are 'Event/Co-Op Bots' are the underhollow, all of which show as losses and for some reason contribute to the winrate of the account.

**Comment by howardchung** [comment]
I don't believe the Underhollow matches are counting toward your winrate.  I checked by visiting the API for the matches page without insignificant matches included:
https://api.opendota.com/api/players/201940161/matches

The number of games is 3862 which is the same as displayed in the W/L count total.

They show up as losses and are visible in the matches list, but don't count toward your w/l total.  If you play a match, the w/l value should not change.

Let me know if this isn't the case.

**Comment by PrincessTamer** [comment]
I played 1 more underhollow to verify this and you are right it doesnt count towards my win/loss _now_ , but im 100% sure it did before. I was floating at ~57.40% winrate before underhollows release, and maintained at least a 40% winrate in normal matches, so there is no way i drop .4% just like that. Not sure if you can do anything but just thought i would say this. Thanks anyway
