### ISSUE TITLE
Adding Damage Dealt/Recieved Query

### ISSUE THREAD

**Issue by FeargusHJ** [odota/web#1644]
Hi,

I'm trying to sort heroes by damage received, specifically to try to determine which heroes have the highest 'tankability' which i think would be useful for drafting.

Could these fields be added to the meta/explorer queries?

Sincere thanks,

**Comment by howardchung** [comment]
There might be able to be a way to sum the values of the json objects that hold the damage dealt/received from heroes.  Would require some exploration though.  Feel free to experiment in Explorer SQL editor and comment if you find a solution, and we can add it to the preset queries in Explorer.
