### ISSUE TITLE
Show previous season's medal

### ISSUE THREAD

**Issue by aeosynth** [odota/web#1651]
Current and previous medal are shown in client.

**Comment by howardchung** [comment]
We could do this on the backend, the Dota 2 GC returns this data.  we'd probably just want to store in a separate postgres table and then update the UI to show both medals

**Comment by evillman** [comment]
Also, while showing previous medal, show Medal history. Just proposed it at https://github.com/odota/web/issues/1806

**Comment by howardchung** [comment]
I don't think Valve is planning to continue resetting seasons, so this may not be needed anymore.
