### ISSUE TITLE
Morphling's information page consisting of benchmarks, ranking etc, does not work.

### ISSUE THREAD

**Issue by statubom** [odota/web#1654]
**Current Behavior**
Specifically Morphling's Rankings page and other statistics is bugged and cannot be opened. 
Instead, it simply shows a black background screen.

**Expected behavior/code**
Behavior expected - Page should be opened and show contents

**Possible Solution**
Repair the bug in the coding if possible. (Sorry, I do not understand in coding.)

**Additional context/Screenshots**
It seems to occurr only to morphling's page, all other heroes seem to work fine.
(https://www.opendota.com/heroes/10) <This is morphling's page that is bugged.

**Comment by howardchung** [comment]
I prevented the crash in https://github.com/odota/web/commit/5d128585ed62454d28a5e218f915e711f8a6f3f0 but we need to fix the underlying problem which is that we're reading morphling's talents incorrectly from the data files.

**Comment by howardchung** [comment]
https://github.com/odota/dotaconstants/pull/52 manually patches the issue but we need to update the build script or else this will just happen again next time we run it to update after a patch.

**Comment by howardchung** [comment]
I fixed this by assuming all heroes have 8 talents and they are split into 4 tiers of 2.
