### ISSUE TITLE
show lane outcome in overview

### ISSUE THREAD

**Issue by aeosynth** [odota/web#1655]
Dotabuff shows lane outcome in the match overview page, which is the only reason I open matches both there and in Opendota.

**Comment by howardchung** [comment]
I believe we have the raw data for this (it's already displayed in the Story tab), we would just need to display it also in the overview if available

**Comment by Argn0** [comment]
The story tab only takes the net worth difference into consideration. So it's very simplistic.

**Comment by Argn0** [comment]
That being said, calculating the lane outcome by net worth difference should be accurate in most cases.

**Comment by wanderrful** [comment]
I'm currently working on a pull request for this issue. My solution is to just add another line to the tooltip when you wave your mouse over the hero icon on the map, like so:

![Image](https://i.imgur.com/3UObmxu.png)

**Comment by aeosynth** [comment]
Cool, but I'd prefer to see the outcome at a glance, instead of interactively lane by lane.

**Comment by howardchung** [comment]
Yeah, I think the intent is to put it into the table in the same line where the player's medal/rank currently is.  So it would be like `Crusader 1 / Mid (Lost)`

**Comment by wanderrful** [comment]
Ah so like how dotabuff does it. I think I can do that!

**Comment by howardchung** [comment]
I think we now show the lane winners in the laning tab
