### ISSUE TITLE
show more than 24h of meta

### ISSUE THREAD

**Issue by aeosynth** [odota/web#1657]
With 2 filters (Divine+, All Draft), multiple heros have <10 games.

**Comment by howardchung** [comment]
I can increase the sampling rate so there are more matches

**Comment by howardchung** [comment]
I've doubled it to 20 percent, it'll take a day to go into effect.

**Comment by aeosynth** [comment]
a better example: with just one filter (Min Tier - Immortal), over half the heroes have <10 games.

**Comment by aeosynth** [comment]
Thanks
