### ISSUE TITLE
Biggest Hit damage isn't displayed if it is a right-click attack in Performances

### ISSUE THREAD

**Issue by builder-247** [odota/web#1661]
**Current Behavior**
In match Performances tab if biggest hit is a right-click attack, it only shows the hero it was dealt to [1].

**Expected behavior/code**
If biggest his a right click attack, it should be displayed like it's displayed in Casts tab [2]

**Additional context/Screenshots**
[1] Current behaviour
![image](https://user-images.githubusercontent.com/14019974/42690382-a74a4218-86ac-11e8-8013-393e90d3df39.png)

[2] Wanted behaviour
![image](https://user-images.githubusercontent.com/14019974/42690364-92587014-86ac-11e8-95c8-7a9a31396421.png)

**Comment by howardchung** [comment]
thanks! I think this might have been broken with a recent update, IIRC it was working properly at the time it was implemented.

**Comment by howardchung** [comment]
to help debug do you have a link to a match where this happens?

**Comment by builder-247** [comment]
Here is an example match: https://www.opendota.com/matches/4003436729/performances

**Comment by S4elkyn4eGGG** [comment]
API Matches.data.players[numberPlayer].max_hero_hit must return need query, but it return him incorrect
