### ISSUE TITLE
Column "dn_t" does not exist

### ISSUE THREAD

**Issue by Cage3** [odota/web#1664]
Data Explorer:
https://www.opendota.com/explorer

SQL:
SELECT dn_t FROM player_matches LIMIT 10

Result:
error: column "dn_t" does not exist

Something wrong here. Column "dn_t" should exist.

**Comment by howardchung** [comment]
I think we forgot to run the schema update when this column was added.  I'll add it now, but the data will only show up for future matches unless we reparse all of them
