### ISSUE TITLE
Improve meta filters

### ISSUE THREAD

**Issue by aeosynth** [odota/web#1665]
Suggestion: sort filters on the meta page alphabetically, and remove irrelevent game modes. It's not obvious why Zeus is not the last entry in the Hero list, and because only the last 24h are shown, defunct game modes such as Limited Heroes and Diretide will not show any games.

**Comment by howardchung** [comment]
we could do this, but the intention is for users to type and let the autocomplete find the entry rather than scrolling through and finding the target
