### ISSUE TITLE
upgrade to material-ui v1

### ISSUE THREAD

**Issue by howardchung** [odota/web#1706]
https://github.com/mui-org/material-ui/releases

**Comment by polo123qwe** [comment]
Migration to v1 seems really cumbersome and it has a lot of issues, I've been fiddling with it for a bit and found many problems. [This gist](https://gist.github.com/fzaninotto/0a59220e0460134de321b415d1418e99) reflects many of the issues faced during migration in another project.

**Comment by howardchung** [comment]
Ouch. We may put this off for a while.

We've also been discussing reducing our dependency on material-ui, possibly starting with Tables.
