### ISSUE TITLE
Wardmap is really strange

### ISSUE THREAD

**Issue by denis331** [odota/web#1714]
![ward](https://user-images.githubusercontent.com/29519024/43333803-274796f0-91d4-11e8-9b1a-0e8bcb659275.png)
Hello! I think there is a problem with my wardmap, I've compared it to other players and theirs looks better than mine. For example take the "Observer" one: it has many blue spots and only a few of them are green/red. 
Is there any way you could reset them? 
Thank you!

**Comment by howardchung** [comment]
I think this happens if you have a lot of wards placed on the same spot, the scaling will make the less commonly used spots a lot fainter.  we can take a look at the scaling/normalization code
