### ISSUE TITLE
Unable to scroll Item history table right in long duration games.

### ISSUE THREAD

**Issue by MLPaladin888** [odota/web#1725]
**Current Behavior**
When attempting to scroll each teams' tables to the right in long duration games, the position will reset back to the far left.

**Expected behavior/code**
To be able to scroll the table to the right and have it stay there.

**Console Output**
 HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
purchases (1,3044)

 HTML1521: Unexpected "/body>" or end of file. All open elements should be closed before the end of the document.
purchases (1,3709)

**Environment**
- Browser Version: Microsoft Edge 42.17134.1.0, Google Chrome 68.0.3440.84 (Official Build) (64-bit), Mozilla Firefox Quantum 61.0.1
- OS: Windows 10 (17134.167)

**Additional context/Screenshots**
See match 3976886690 as an example: https://www.opendota.com/matches/3976886690/purchases

**Comment by howardchung** [comment]
@Argn0 I think this might have to do with the locking/moving of the first column.

**Comment by Argn0** [comment]
I think this happens because the first column shrinks on scroll. Not sure if there is a straight forward fix for this. I'll try to think of something.
