### ISSUE TITLE
GET /heroes/{hero_id}/matchups

### ISSUE THREAD

**Issue by maxuko** [odota/web#1742]
Good afternoon.
The documentation [(doc)](https://docs.opendota.com/) states that the method "matchups" (GET /heroes/{hero_id}/matchups) corresponds to Responses

`[
{
"id": 0,
"name": "string",
"localized_name": "string",
"primary_attr": "string",
"attack_type": "string",
"roles": [
"string"
]
}
]
`
but it's not. the response from the server will
`{"hero_id":51,"games_played":23,"wins":12}`

The fields declared in the documentation and the actual fields returned by the server do not match.
I ask you to check where the inconsistency.
Thank you.

**Comment by howardchung** [comment]
Thanks, I think this is due to reusing a common data object.  We'll update the docs.

**Comment by howardchung** [comment]
checked in the fix, it should be resolved soon

**Comment by maxuko** [comment]
good job)
