### ISSUE TITLE
Language Issue: Spanish

### ISSUE THREAD

**Issue by MeGA-ct** [odota/web#1773]
lane_role_3, It should not be "**Desactivar**" I know that the "official translation in Dota2 client it's that but that doesn't mean that it's right.

I see the other 2 JSON for the other 2 variants of spanish (es-PE and es-US) just use **Off** without translation.

I'll propose one of the earliest solutions spanish used before "lateral", it's in the localization files of the official client, token name in dota2_spanish.txt (i think it's inside vpk) = DOTA_HeroGuide_Role_OffLane for this token you will see, "**offlane**" translated as "**Solo lateral**"

**Comment by howardchung** [comment]
You can submit new translations on https://translate.opendota.com
