### ISSUE TITLE
players names on replays from TI8

### ISSUE THREAD

**Issue by luisiacc** [odota/web#1776]
is it normal that, in the replays i downloaded , the players names doesnt appear like for example, Liquid.Miracle-, Liquid.Kuroky, instead it appears what i think it is the name they are actually using in their accounts like , instead of Liquid.Miracle, it show "Kuroly-IR" and so for the other players on any replay, is there a way that i can change this ?

**Comment by Argn0** [comment]
This issue is not really related to OpenDota. The replays you download from OpenDota are hosted on valves servers

**Comment by luisiacc** [comment]
ok, do you have a solution or explanation however?
