### ISSUE TITLE
Complete pt-BR (Brazilian Portuguese) translation overhaul.

### ISSUE THREAD

**Issue by evillman** [odota/web#1796]
**Is your feature request related to a problem? Please describe.**
There's a lot of misspelling in the pt-BR translation, so I decided to make a complete overhaul.

**Describe the solution you'd like**
I will make all the corrections and make a standard portuguese language use.

**Teachability, Documentation, Adoption, Migration Strategy**
How are my translations approved?  I am using the Arthur "4rtd0t4" profile to do this. Can someone help me out?

**Comment by howardchung** [comment]
Are your translations showing up here?

https://github.com/odota/web/pull/1670

If they are, I can merge them in the next update.

**Comment by evillman** [comment]
Yes. They are. I already checked!

**Comment by howardchung** [comment]
In that case they'll be in the next release.
