### ISSUE TITLE
Hovering over "Exclude turbo matches" button attempts to show hero card

### ISSUE THREAD

**Issue by TheGuywithTheHat** [odota/web#1802]
**Current Behavior**
Hovering over "Exclude turbo matches" button attempts to show a hero card, and its values default to `undefined`, `NaN`, etc.:

**Expected behavior/code**
normal tooltip appears

**Console Output**
No output

**Environment**
- Browser Version: Chrome 69
- OS: Windows 10

**Possible Solution**

**Additional context/Screenshots**
![bugged hero card](https://i.imgur.com/znB6ur8.png)

**Comment by howardchung** [comment]
interesting.  @Argn0 have you seen this before?

**Comment by howardchung** [comment]
actually, I couldn't seem to repro this.  @Argn0 were you able to?

**Comment by Argn0** [comment]
yes. it happens only sometimes. super weird.
