### ISSUE TITLE
[Feature Request] Links to Gosu.AI for each hero on Match View

### ISSUE THREAD

**Issue by BetaLeaf** [odota/web#1807]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
A button to click that takes you to the specific match with a specific hero in Gosu.ai

**Describe alternatives you've considered**
None

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

//*[@id="root"]/div/div[3]/div/div/div[1]/div[5]/div/div/div/div/table/tbody/tr[5]/td[1]/div/div/div[3]

OR 

#root > div > div.sc-kQsIoO.gbkRrS > div > div > div:nth-child(1) > div:nth-child(5) > div > div > div > div > table > tbody > tr:nth-child(5) > td:nth-child(1) > div > div > div:nth-child(3)

Add 
```<div style="height: 38px; border-radius: 2px; transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; top: 0px;"><img src="/assets/images/gosu-24px.png" alt="" color="#303030" style="vertical-align: middle; margin-left: 12px; margin-right: 0px;"></div>``` 
and link to that specific hero on that specific match on gosu.ai

![https://i.imgur.com/3b9RJMT.png](https://i.imgur.com/3b9RJMT.png)

**Comment by howardchung** [comment]
Gosu.AI is no longer a sponsor so I'm not sure if we'll do this.
