### ISSUE TITLE
add contributor badge to player profiles

### ISSUE THREAD

**Issue by howardchung** [odota/web#1808]
suggested by @gu3st

**Comment by gu3st** [comment]
For this I was thinking about having a JSON file (maybe lives in core so API can serve it up?) that could also have Discord ids.  That way we could create a bot at some point that automatically assigns roles in the opendota discord.  Alternatively is a separate git repo with a single contributors.json file that gets brought in as package from github (into core)?

Thoughts?

**Comment by gu3st** [comment]
I was thinking a separate repo as a thin npm package so it could be shared. That way changes are independent of mobile/web/core. I can do it as part of either though. Probably just need a corresponding issue for the file creation along with UI implementation

**Comment by howardchung** [comment]
seems like overkill to make an npm package for this.  Let's just make it a json file in https://github.com/odota/core/tree/master/routes

Then we can import that file in the route logic and set an isContributor field in the player response.
