### ISSUE TITLE
Game did not appear at all in history until I parsed.

### ISSUE THREAD

**Issue by jjohnstongames** [odota/web#1815]
https://www.opendota.com/matches/4127346849

I was in this match, but it did not appear in my game history at all. When I tried to visit the match's url manually (by replacing the ID of a different game with the match ID of this game), I got an error page saying the page did not exist.

To fix the problem, I attempted to parse the match, which worked. Now the match has a page and it appears in my game history.

I am not sure what in the game could have cause it to not appear at all, and in my years of using this site I have never seen this behavior.

**Comment by howardchung** [comment]
I believe this happens very occasionally when the Valve GetMatchDetailsBySequenceNum endpoint for some reason doesn't list a match.  Querying it again later works, and GetMatchDetails works as well.  I'm not sure what a good solution for this is, aside from randomly running full history requests on players to find their latest match IDs.

**Comment by howardchung** [comment]
This has been happening more often, I think the easiest solution is just to periodically run full history checks on users. We can implement this on the core side

**Comment by howardchung** [comment]
I've deployed a service to do this, will monitor it.

**Comment by howardchung** [comment]
Closing, feel free to comment if this issue continues occurring
