### ISSUE TITLE
Draft page displays incorrectly in Microsoft Edge.

### ISSUE THREAD

**Issue by Argn0** [odota/web#1835]
Dire picks and bans have non functional left margins in Edge.
https://www.opendota.com/matches/4130022794/draft

**Comment by j08** [comment]
In https://github.com/odota/web/blob/master/src/components/Match/Draft/Draft.jsx
Line 57.

Take out
margin-left: ${props => (props.radiant ? '0' : 'auto')};
and put in 
justify-content: ${props => (props.radiant ? 'flex-start' : 'flex-end')};

Maybe...

**Comment by Argn0** [comment]
> In https://github.com/odota/web/blob/master/src/components/Match/Draft/Draft.jsx
> Line 57.
> 
> Take out
> margin-left: ${props => (props.radiant ? '0' : 'auto')};
> and put in
> justify-content: ${props => (props.radiant ? 'flex-start' : 'flex-end')};
> 
> Maybe...

Please make a pull request so we can check if it's working.

**Comment by j08** [comment]
To be honest I wouldn't know where to start making a Pull Request. I will try and work it out.

**Comment by j08** [comment]
I think I worked it out, although it seems that the margin-left has to be in there also otherwise it breaks in FireFox. It now seems like there is 2 commits which I hope doesn't mess things up.
