### ISSUE TITLE
Remove MMR tab from player profiles

### ISSUE THREAD

**Issue by mobyte0** [odota/web#1843]
The MMR tab should be removed since MMR isn't really a stat that is used anymore after being replaced by medals. It could stay in the files for archival purposes if desired but I don't see the point in having it on display in a profile when it doesn't serve any functionality anymore.

**Comment by howardchung** [comment]
I think it's still useful for looking up old data/graphs

**Comment by mobyte0** [comment]
Like I said, it could stay in as code for archival but I think when looking at the profile page, it doesn't make sense to have it as a link since the last updated data is from almost a year ago.

**Comment by xynazog** [comment]
I think people still refer to MMR on the Profile/Stats page on their DoTA accounts. It is used to calculate approximately the number of matches to win to reach the next level.

**Comment by mobyte0** [comment]
> I think people still refer to MMR on the Profile/Stats page on their DoTA accounts. It is used to calculate approximately the number of matches to win to reach the next level.

It hasn't been a public stat in a very long time, though. The only person that can actually see it is you unless you share a screenshot or something like that. It's effectively useless data-wise, now, in my opinion.

**Comment by evillman** [comment]
Isn't MMR still being tracked for people that didn't change in-game profile and show SOLO MMR: -----???

**Comment by mobyte0** [comment]
> Isn't MMR still being tracked for people that didn't change in-game profile and show SOLO MMR: -----???

No, the value is no longer updated publicly. It shows up as blank because there is not an option to show Solo MMR on your profile anymore.

**Comment by howardchung** [comment]
I think the data is actually still coming back on the backend so people who never changed it can still have it updated.  The client might hide it separately
