### ISSUE TITLE
Opendota doesnt show any of my stats 

### ISSUE THREAD

**Issue by Radozyte** [odota/web#1856]
Hey , I just learned about opendota and wanted to see my match performances and etc. However, when I logged in with my steam account it wont show any of my stats or anything in fact.I dont really know if this is normal or not.

Can you help me with this ?

am I doing something wrong ???

**Comment by gu3st** [comment]
Have you hit the refresh button on your profile to ask OpenDota to refresh your stats?

**Comment by Radozyte** [comment]
Yes on multiple occasions :/

**Comment by gu3st** [comment]
Inside of DOTA 2, have you enabled the "Expose Public Match Data" setting before refreshing?

Knowing your friend id (as that's the same as your profile id) could help debug as well.
