### ISSUE TITLE
Changing lobby type filter on player overview doesn't update recent matches window

### ISSUE THREAD

**Issue by C-Kenny** [odota/web#1870]
**Current Behavior**
Changing lobby type filter on player overview doesn't update recent matches window. 

**Expected behavior/code**
I would have expected the "Recent Matches" Window to only show Ranked matches, if the lobby type filter was set to 7. This behaviour works for the matches tab, but not the overview/recent matches section.

**Console Output**
NA

**Additional context/Screenshots**
Player Overview + Recent Matches Section:

![image](https://user-images.githubusercontent.com/5967521/46638734-ce4a4a00-cbbe-11e8-994e-69267b8576ef.png)

Matches tab + same filter:

![image](https://user-images.githubusercontent.com/5967521/46638749-e02bed00-cbbe-11e8-8866-f0ea1e7b9d75.png)

PS: I'm not sure why these screenshots came out so dark.

**Comment by howardchung** [comment]
Yeah, it's the same reason. Not sure if there's something we can do to make this behavior more obvious (maybe just don't show the recent matches at all and say something like "recent matches do not support filtering"

**Comment by howardchung** [comment]
closing as duplicate
