### ISSUE TITLE
Make average/best stats use the applied filters

### ISSUE THREAD

**Issue by evillman** [odota/web#1896]
**What?**
When applying filters on Overall tab, the stats for Average/Best should apply these filters too.

**Why?**
Most often the not, people want to check their ranked stats and check how they are doing overall... 
These stats are very useful if you play the same role over and over... Also, you can check your average GPM, XPM, KDA, in that position.

Also, I guess it was like this before and it got removed a few builds later.

**Comment by howardchung** [comment]
I don't think this is possible since that section uses the 20 recent matches, which do not update when a filter is applied.

**Comment by evillman** [comment]
Can't we apply the filter to it?

**Comment by howardchung** [comment]
No because the filtering requires fetching the full result set from the server and doing client side filtering.  Fetching last 20 is faster but prevents this.
