### ISSUE TITLE
meta: min duration (invalid template)

### ISSUE THREAD

**Issue by aeosynth** [odota/web#1897]
https://www.opendota.com/meta?minDuration=10

min duration shows as (invalid template); it should show as 10 minutes.

firefox 62.0.3, solus linux

**Comment by howardchung** [comment]
probably this is due to the strings not being loaded immediately.  i'll take a look

**Comment by karthicrajakumar** [comment]
Hey, Can I take up this issue?

**Comment by howardchung** [comment]
Yes, please go ahead!

**Comment by karthicrajakumar** [comment]
#1900 Added a small wait until strings objects are present.
