### ISSUE TITLE
meta: mark bonus heroes

### ISSUE THREAD

**Issue by aeosynth** [odota/web#1898]
daily bonus heroes will have odd spikes of win/pick rate; the meta page cannot show spikes as it doesn't track results for more than 24h

**Comment by howardchung** [comment]
Unfortunately for performance reasons the meta page can't operate on too many matches. I'll keep this in mind in case we can do something to optimize it but it won't be as easy as just changing a number.

**Comment by howardchung** [comment]
Actually I'm not sure if you're just requesting that the bonus heroes be indicated in some way. I believe the algorithm for bonus heroes is known in advance, but I haven't looked up how to implement it in JS.

**Comment by aeosynth** [comment]
yes sorry, this is a request to indicate the bonus heroes. where is the algorithm? i could try implementing it.

**Comment by howardchung** [comment]
this might be up to date: https://github.com/victorvde/dota_bonus_heroes
