### ISSUE TITLE
Discord invite link is outdated

### ISSUE THREAD

**Issue by kinglau66** [odota/web#1899]
**Current Behavior**
Discord invite link is outdated. Click on "chat on discord" logo gives me a discord link but the discord link has expired.
**Expected behavior/code**
Click on "chat on discord" should direct me to a invite link of the discord group.

**Console Output**
N/A

```
N/A
```

**Environment**
- 62.0.3 (64-bit)
- Windows 10 Pro (1809)

**Possible Solution**

Updating the invite link? or remove the chat on discord logo. or invite link set as never expired.

**Additional context/Screenshots**
N/A

**Comment by howardchung** [comment]
I can't seem to repro this, is the link https://discord.gg/opendota

**Comment by JulianJason** [comment]
Seems to still be working

**Comment by C-Kenny** [comment]
Can't reproduce either. Are you talking about the Discord logo at the bottom of the webpage? https://discordapp.com/invite/opendota

**Comment by kinglau66** [comment]
Opps, it's an issue from my end. Apparently the discord group does not allow to join the server as an "unclaimed account", thus giving me the problem. I can join the server after logging in myself. sorry for that
![image](https://user-images.githubusercontent.com/15945904/47252353-db482280-d475-11e8-8e9b-16029e1cc1b8.png)
![image](https://user-images.githubusercontent.com/15945904/47252354-dc794f80-d475-11e8-8165-6aa26a4bc517.png)
