### ISSUE TITLE
Bug on any hero selection filter drop down menu

### ISSUE THREAD

**Issue by pouliosk** [odota/web#1908]
Hey all, great work, but I think I came across a bug? 

When trying to filter matches using any of the hero selection filter (e.g. 'Hero', 'Opposing Heroes', 'Allied Heroes' etc), the drop down menu for selecting heroes stops at Treant Protector (so you can not filter for any of the heroes that are alphabetically below treant). 

I have tried this so far on both firefox and chrome on win10 OS and the issue is the same. 

Thanks in advance for the fix ;)
And thank you again for this great tool.

**Comment by howardchung** [comment]
So the intention for the filter is for users to start typing what they're looking for. The list will auto-filter based on the input
