### ISSUE TITLE
Party size filter not working (showing party games when 1 is selected)

### ISSUE THREAD

**Issue by evilmtv** [odota/web#1914]
**Current Behavior**
Selected party size 1 in filter but party (of 5) game showed up still.

**Expected behavior/code**
Only solo matches.

**Console Output**
N/A

**Environment**
- Browser Version: Chrome 70.0.3538.77
- OS: Windows 10

**Possible Solution**

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/19277738/47841461-a97b7800-ddf4-11e8-83c3-0ae992e3435e.png)
![image](https://user-images.githubusercontent.com/19277738/47841491-c152fc00-ddf4-11e8-9a30-99a390c8bb61.png)
https://www.opendota.com/matches/4193262367

**Comment by howardchung** [comment]
This is the "unexpected behavior" issue described here:
https://github.com/odota/core/issues/1636

Considering this is the third bug report about it we should probably prioritize this

**Comment by drusepth** [comment]
@howardchung FWIW, I was actually coming here to report "Lobby Type = Ranked" filter not working on the overview also, which seems to be the same unexpected behavior issue.

**Comment by howardchung** [comment]
yeah, I think #1915 should resolve it by subbing in the content of the matches tab if a filter is applied in the overview
