### ISSUE TITLE
Time limit or range on player's trend tab

### ISSUE THREAD

**Issue by kbastomi** [odota/web#1921]
The title pretty much sum the requested feature.

keep 20-moving average but add a feature to limit the time range (last 7 days, last 30 days, last patch, etc) a la https://www.dotabuff.com/players/299270712/trends?date=all&metric=experience

thank you

**Comment by howardchung** [comment]
I believe there's already a last N days filter available?

**Comment by kbastomi** [comment]
yes. but make it more obvious by placing filter portion below tabs. i know the intention of filter is to apply to all tabs, but with currents system IMO is too complicated if just want to see last x days or patch or whatever.

its like a local and global filter feature.

**Comment by howardchung** [comment]
I'm not sure if it makes sense to have a separate local filter section just for this tab, but I'm open to ideas or suggestions to make it more intuitive.
