### ISSUE TITLE
Add Current Patch API Request

### ISSUE THREAD

**Issue by jmpdmnky** [odota/web#1922]
It would be nice if there was a GET request like:

https://api.opendota.com/api/currentPatch

There are two reasons for this:
 1. It would make it easier to go from valve numbering (i.e. 7.19) to the numbering used (i.e. 38)
 2. It would also make it much easier to programatically search for results based on patches without the dev needing to manually change the patch or find it from a search through recent matches.

Thanks!

**Comment by howardchung** [comment]
you could pull this file and check its length then subtract 1: https://github.com/odota/dotaconstants/blob/master/build/patch.json

**Comment by jmpdmnky** [comment]
thanks!  I'll give that a shot

**Comment by howardchung** [comment]
I actually added the ID value to it in the latest version
