### ISSUE TITLE
Pros tab not displaying anything

### ISSUE THREAD

**Issue by onemorebadger** [odota/web#1923]
**Current Behavior**
Currently my pros tab is completely empty, I know this shouldn't be the case as up until about a month ago I had four or so pros there. Having read other threads on the issue I doubt that all four simultaneously turned off their expose data options and I couldn't find another fix.

**Console Output**
Happy to provide this but I believe it's just the basic info describing the webpage and nothing more.

**Environment**
- Browser Version: Chrome Version 70.0.3538.77 
- OS: Windows 10

**Comment by howardchung** [comment]
A while back Valve changed their APIs to return a more curated list of pro players (about 600 instead of 1100 players). We started using this new list since it seems to be a more accurate representation of actual pro players.

**Comment by onemorebadger** [comment]
Thanks for the response, that makes sense although i'm surprised light of heaven isn't on the list. Is their a way to view that list?

**Comment by howardchung** [comment]
http://www.dota2.com/webapi/IDOTA2Fantasy/GetProPlayerInfo/v001

**Comment by onemorebadger** [comment]
Thanks man, appreciate the work you do
