### ISSUE TITLE
It doesn't show my statistic since 2012 till now 

### ISSUE THREAD

**Issue by littlepinkdoggy** [odota/web#1928]
**Current Behavior**
A clear and concise description of the behavior.

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by littlepinkdoggy** [comment]
I have more than 8 thousand hours in Dota 2 but it shows only 20 games. 

How can I fix it? 

Thank you for your fast response and assistance.

**Comment by coreymaher** [comment]
@littlepinkdoggy The "Overview" tab on your opendota profile only shows the 20 most recent games. If you want to see all your games, click on the "Matches" tab.

**Comment by howardchung** [comment]
Also make sure your Expose Public Match Data setting is enabled.

**Comment by littlepinkdoggy** [comment]
Many thanks, it is fine now. ) 


>Воскресенье, 18 ноября 2018, 1:34 +03:00 от Howard Chung <notifications@github.com>:
>
>Also make sure your Expose Public Match Data setting is enabled.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Алдар Дорджиев
