### ISSUE TITLE
7.20 reworked abilities are bugged.

### ISSUE THREAD

**Issue by evillman** [odota/web#1948]
**Current Behavior**
Patch 7.20 Reworked abilities are bugged. With no images or descriptions.

**Expected behavior/code**
Show up the correct abilities on icons and tooltips.

See Lich and KotL on game ID: 
https://www.opendota.com/matches/4230803757

**Comment by howardchung** [comment]
This has been fixed in the stage build that should be shipping in the next couple days.

Please check https://stage.opendota.com/matches/4230803757 for any issues
