### ISSUE TITLE
Images for slark's agi steal and lion's finger of death kills total is not shown and displayed as autoattack/other

### ISSUE THREAD

**Issue by luffy333221** [odota/web#1965]
As the new patch came out the icon/images used for these buffs displayed on the page are not accurate.

**Comment by luffy333221** [comment]
okay thanks for the reply.
As you the main contributor, I'm just adding those values here:
"7" : "lion_finger_of_death",
"8" : "slark_agility_steal"

**Comment by DimasDSF** [comment]
Underlords permanent damage is also missing

**Comment by howardchung** [comment]
Do you have a link to matches/match ID with these abilities so I can verify the ID values?

**Comment by jgalat** [comment]
Hi @howardchung 
Here it is a match that has the 3 of them (https://opendota.com/matches/4244461283)
I've checked the positions/keys but how can I figure out the value of the object that I should use in the dotaconstants file?
Thanks!

**Comment by akshatmittal** [comment]
This issue should be closed since this has been fixed by the pull odota/dotaconstants#65.

[Preview](https://stage.opendota.com/matches/4244461283)
