### ISSUE TITLE
Shadow Demon's soul catcher doesn't get counted as damage

### ISSUE THREAD

**Issue by Schoolboy215** [odota/web#1970]
**Is your feature request related to a problem? Please describe.**
When Shadow Demon is in a match, the damage caused by his soul catcher doesn't get recorded. This has been happening since 7.20 came out.

**Describe the solution you'd like**
This spell should show alongside his others in the combat tab, along with its damage. I understand this is a little complicated, considering targets can sometimes gain some of the damage back, effectively negating it.

**Teachability, Documentation, Adoption, Migration Strategy**
Display would be exactly the same as any other hero's spells.

**Comment by howardchung** [comment]
Not sure what the issue is, will have to examine the combat log. Do they show up in the in-game combat log when watching the replay?

**Comment by Schoolboy215** [comment]
I don't know. I'll update this comment when I get home from work and try it.

**Comment by Schoolboy215** [comment]
Making a new comment in case it helps with getting the notification out:

The combat log does not appear to show damage dealt, and only shows the debuff being applied/going away

![image](https://user-images.githubusercontent.com/4270594/49257556-a75f0600-f400-11e8-8b4c-d4fb61ccbf49.png)

**Comment by Schoolboy215** [comment]
Does this mean OpenDota isn't supposed to track HP adjusting spells? Sorry if I opened this in error.

The whole thing struck me because after 7.20, this spell is potentially Shadow Demon's biggest source of "damage", and it seemed weird to not see it tracked.

**Comment by howardchung** [comment]
Yeah, we only work with what's in the combat log.
