### ISSUE TITLE
Inconsistency of match winner on combat tab

### ISSUE THREAD

**Issue by TheSagab** [odota/web#1978]
**Current Behavior**
When viewing combat tab on a match page, the header is showing Radiant Victory, but on damage section, the Dire team is showing as the winner.

**Expected behavior/code**
On damage section it should show Radiant team as the winner.

**Console Output**
No console outputs

**Environment**
- Browser Version: Chrome Version 70.0.3538.110
- OS: Windows 10

**Additional context/Screenshots**
Match link: [https://www.opendota.com/matches/4231658247/combat](https://www.opendota.com/matches/4231658247/combat)
Screenshots:
![image](https://user-images.githubusercontent.com/23238692/49325307-d2696700-f572-11e8-9e55-2984940dca27.png)
![image](https://user-images.githubusercontent.com/23238692/49325311-e1e8b000-f572-11e8-8531-8d16891dc474.png)
![image](https://user-images.githubusercontent.com/23238692/49325316-eb721800-f572-11e8-92b0-5cee2c6e79fe.png)

**Comment by howardchung** [comment]
I think this was fixed in https://github.com/odota/web/pull/1950

Does it work correctly on stage.opendota.com?

**Comment by TheSagab** [comment]
Whoops, yeah it works correctly on that version.
