### ISSUE TITLE
Laning - EFF@10

### ISSUE THREAD

**Issue by Merc62** [odota/web#1993]
Hi there! I wonder how exactly the EFF@10 parameter is calculated. Why do I have a relatively low EFF@10 metric (60%), if I made more LH and DN than the other players in the match? Passive and starting gold is equal, am I correct? Perhaps, it is somehow related to the item purchasing during strategy phase before the match actually begins.

**Comment by howardchung** [comment]
it's based on total gold obtained, so possibly other players got gold from hero kills or towers

**Comment by Merc62** [comment]
It's highly unlikely that in many matches people kill any towers under a 10 minute mark. 
I thought about Bounty runes, but they go for all teammates, but I see a strike difference in EFF@10 performance between the players of the same team. I also checked first blood kills - no correlation found as well.

**Comment by evillman** [comment]
It's all about hero kills and assists. Check the kills before 10mins. The lane with higher EFF@10 will probably have a better KDA than yours.
