### ISSUE TITLE
Bitcoin donation no longer works as Stripe no longer supports bitcoin

### ISSUE THREAD

**Issue by minecraft2048** [odota/web#1997]
**Current Behavior**
When I go to https://carry.opendota.com/ and try to donate a cheese using the yellow `Or B using Stripe` and entered my address and such, it shows `the type bitcoin is not a valid source type`, and by googling around it turns out that Stripe payment provider no longer supports bitcoin: https://stripe.com/blog/ending-bitcoin-support

**Expected behavior/code**
I can pay cheese using bitcoins

**Possible solutions**
I think that the easiest solution for now is to remove that yellow pay with bitcoin button, and in the long term use other payment processor such as [BitPay](https://bitpay.com/) for direct fiat conversion or [BTCPay](https://en.bitcoin.it/wiki/BTCPay) if you want to take control of your bitcoins

**Comment by howardchung** [comment]
@albertcui should we just remove the option to donate via Bitcoin from the carry site? I don't know if we'll be able to set up another payment service provider.

**Comment by hshar7** [comment]
https://developer.kyber.network/docs/WidgetOverview/ would be a very good choice imo. It allows the user to donate using any erc20 token including the just released WBTC (wrapped bitcoin in erc20)
