### ISSUE TITLE
Can not request data from the backend server with api

### ISSUE THREAD

**Issue by qiu198022** [odota/web#2001]
**Explain your question as detailed as possible**
I have download the source code and install and setup as the quick start guide. 5 docker have been start success as the attached picture
Now I can get some api content from my server using serverip/api. But if i use the serverip/api/matchs/matchid or other API interface, the webbrowser always display erro "Not found"
I have apply the 
STEAM_USER=*********
STEAM_PASS=********************
STEAM_API_KEY=********************************
and fill the info into the .env file and upload it onto my server
Can you help me what should I need do next? Something wrong with the postgres sql port or other step?
Thanks
---

If you have a support request or question please also check our Discord Server: https://discord.gg/opendota
<img width="1050" alt="2019-01-09 7 55 57" src="https://user-images.githubusercontent.com/51344/50897951-9fa37000-1448-11e9-9679-ad085e60b3eb.png">
<img width="1452" alt="2019-01-09 7 56 40" src="https://user-images.githubusercontent.com/51344/50897999-be096b80-1448-11e9-831f-bb1d6820a422.png">
<img width="697" alt="2019-01-09 7 57 41" src="https://user-images.githubusercontent.com/51344/50898031-da0d0d00-1448-11e9-88d1-c4868052aaa1.png">

**Comment by coreymaher** [comment]
@qiu198022 When you first start up the api, your database will contain no matches. You'll need to request them first: https://docs.opendota.com/#tag/request%2Fpaths%2F~1request~1%7Bmatch_id%7D%2Fpost

I think by default the part of core that grabs all new matches and parses them is off by default, but someone more familiar with this repo will have to confirm that.

**Comment by Argn0** [comment]
I edited your post, but you made your steam username and password public.

**Comment by qiu198022** [comment]
@coreymaher thank you for the reply message of the match api. I have understand and resolve the match api and can get the data from the match api. But I meet other question and problem for example i want to call GET /heroes  using this url http://kan905.com:5000/api/heroes . But I still can not get the heroes data from this api

**Comment by howardchung** [comment]
you need to populate data into the database by running the ingestion workers

**Comment by qiu198022** [comment]
@howardchung I am the fresh-man of opendota. Can you tell me the operation guide or document how to run the the ingestion workers?

**Comment by howardchung** [comment]
check out the README file. The default configuration only runs the web server, you'll have to do `pm2 start manifest.json --only {servicename}` to run the others
