### ISSUE TITLE
How to configure jump weburl after steam authorize successfully

### ISSUE THREAD

**Issue by qiu198022** [odota/web#2003]
I have setup a server and fill the opendota/core .env with applied steam STEAM_API_KEY. And I have changed this three line configure
ROOT_URL: 'http://locahost:5000', // base url to redirect to after steam oauth login
  RETRIEVER_HOST: 'locahost.com:5100', // Comma separated list of retriever hosts (access to Dota 2 GC data)
  PARSER_HOST: 'http://locahost.com:5600', // host of the parse server
the localhost to my domain.
Then in the setup web I lick the login button in the right-top side, after steam authorize. The web always jump to the http://domin.com:5000/api. It not jump to http://domin.com:5000/player/xxxxx
like the office https://www.opendota.com can jump the right path https://www.opendota.com/players/xxxx

Can I get the guide how to modify jump weburl after steam authorize successfully

---

If you have a support request or question please also check our Discord Server: https://discord.gg/opendota

**Comment by qiu198022** [comment]
Yes the configure.js UI_HOST: '', // The host of the UI, target of /logout and /return this line is empty.
My current server is using the empty configure. How should I modify it to the right /players/xxxx.Becuase I don't knonw where to get the user xxx id

**Comment by howardchung** [comment]
If the login was successful the redirect should go to the player's profile:
https://github.com/odota/core/blob/master/svc/web.js#L250

**Comment by qiu198022** [comment]
Yes, After I modify the UI_HOST: '',  to UI_HOST: 'domin:3000', it can jump right way in the webbrowser. But I meet a problem in the mobile reactive native project. The ios project jump to web browser web not jump to the native web style. How could I modify? I post at the  
https://github.com/odota/mobile/issues/143

**Comment by howardchung** [comment]
@Proyoyo might know the answer to that. I believe the mobile version requires the user to set their account separately.

**Comment by Proyoyo** [comment]
Please have a look here: https://github.com/odota/mobile/issues/143#issuecomment-456251842
