### ISSUE TITLE
Invalid template and undefined for all 'labels' when default language is [nb-no](Norwegian)

### ISSUE THREAD

**Issue by vilrolf** [odota/web#2019]
**Current Behavior**
![image](https://user-images.githubusercontent.com/5473322/52089081-eef34100-25ad-11e9-8a9c-2a4999ab0d27.png)

Every label or title is "undefined", (invalid template) or blank

Goes back to normal when i select another language on language picker.

And when i choose another default browser language.

Should be able to replicate it by changing default browser  language to Norwegian.

**Expected behavior/code**
Labels have correct text. 

**Console Output**
537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1 Uncaught (in promise) Error: Cannot find module './undefined.json'
    at 537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1
(anonymous) @ 537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1
Promise.then (async)
a @ 537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1
s @ 537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1
Promise.then (async)
a @ 537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1
s @ 537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1
(anonymous) @ 537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1
(anonymous) @ 537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1
(anonymous) @ 537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1
(anonymous) @ 537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1
797 @ 537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1
l @ 40292151:1
439 @ 537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1
l @ 40292151:1
u @ 40292151:1
n @ 40292151:1
(anonymous) @ 537d816f8cecc996fc63b0f5b221a90d093d8f63.js:1

**Environment**
Chrome 71.0.3578.98 and Fireforx 62.0.3
Default languages:
Norwegian on both.

![image](https://user-images.githubusercontent.com/5473322/52089466-de8f9600-25ae-11e9-8e21-4842f97e3744.png)

![image](https://user-images.githubusercontent.com/5473322/52089907-1ea34880-25b0-11e9-9432-29feb80646e4.png)

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/5473322/52089556-27474f00-25af-11e9-8d36-6b23b631cffb.png)

Firefox:
![image](https://user-images.githubusercontent.com/5473322/52089789-bf453880-25af-11e9-88d0-1ee0c8ed6b57.png)

**Comment by howardchung** [comment]
fixed in https://github.com/odota/web/commit/245187c3d85f3677ac71654ba5418a8a5f99af3a
