### ISSUE TITLE
advanced meta filters

### ISSUE THREAD

**Issue by aeosynth** [odota/web#2020]
i'd like to see only heroes with above a certain number of games played, and above a certain win rate.

**Comment by howardchung** [comment]
while this could be implemented, the results always return just the list of heroes (120 or so) so this could be done by sorting the returned result list.

**Comment by abnersajr** [comment]
I think an issue on Core repository could be opened. Probably would be better to do this filter first at the back-end.

**Comment by howardchung** [comment]
meta queries just perform  direct database queries (it's basically the same API as explorer but with a simplified query builder)

**Comment by howardchung** [comment]
The Meta query explorer is now deprecated, but you can still use the Heroes tab, Scenarios feature which might be what you're looking for, or the Explorer to query for pro games.
