### ISSUE TITLE
7.21 Win/Loss count incorrect

### ISSUE THREAD

**Issue by MLPaladin888** [odota/web#2024]
**Current Behavior**
As of 02:24 (UTC-5) 2019-02-03, it is currently showing that I am 6-2 under version 7.21 on both the Overview and Counts pages.  I think that there should be more games included under 7.21.  It looks like its only counting games that are listed as far back as "2 days ago".  It should go back to some point in 2019-01-29.

**Expected behavior/code**

**Console Output**

**Environment**
- Browser Version: Microsoft Edge 42.17134.1.0
- OS: Microsoft Windows 10 (OS Build 17134.472)

**Possible Solution**

**Additional context/Screenshots**
https://www.opendota.com/players/307855/overview
https://www.opendota.com/players/307855/counts

**Comment by howardchung** [comment]
Unfortunately since updating the patch is manual, matches that get played before the manual update get tagged with the previous patch. Hopefully this will smooth out as more matches are played in the new patch.

**Comment by abnersajr** [comment]
Would it be difficult making a SQL to manually updates the wrong matches on the DB? I'm new on the project, didn't review how everything works, but It could work.

**Comment by howardchung** [comment]
Unfortunately it's not that simple, as cassandra tables aren't indexed by date and have runtime limits. We would likely need to write a node.js script and manually run it (or deploy as a new service) to fix up the incorrect matches.
