### ISSUE TITLE
Show itemization in matches list

### ISSUE THREAD

**Issue by pvutov** [odota/web#2026]
**Is your feature request related to a problem? Please describe.**
I want to look up top players for a certain hero and see what items they build on that hero.

**Describe the solution you'd like**
Currently the one-line match summary only shows what hero the match was played with and the KDA. [Example](https://www.opendota.com/players/138719682/matches?hero_id=108). I'd like an additional column showing what items the player had at the end of the match. This probably won't work for the overview tab since there isn't enough space, but the matches tab could probably fit even more than that.

**Describe alternatives you've considered**
I guess you could make it customizable which columns are shown, but that seems like even more work.

**Teachability, Documentation, Adoption, Migration Strategy**
N/A

**Comment by howardchung** [comment]
We could add these columns to cassandra, but it would be applicable to future matches only unless we backfill it.

**Comment by howardchung** [comment]
I have added these columns to the schema and the data should be available for future matches if we want to add it.

**Comment by ccyccyccy** [comment]
Is this feature still wanted? If so can I work on it?

**Comment by howardchung** [comment]
Yes! I think the data has been added to the database, but it's not shown yet in the UI. You might have to modify the API call to request the item_1 through 6 fields.

**Comment by ccyccyccy** [comment]
Thanks for the advice. WIll start worknig on it :)
