### ISSUE TITLE
Sange and Yasha showing old icon on Story tab

### ISSUE THREAD

**Issue by guigax** [odota/web#2039]
**Current Behavior**
Sange and Yasha shows up with [old icon](https://i.imgur.com/DXAstMM.png) on Story tab of a parsed match

**Expected behavior/code**
It should show up the [new icon](https://dota2.gamepedia.com/File:Sange_and_Yasha_icon.png)

**Environment**
- Browser Version: Chrome Version 72.0.3626.109 (Official Build) (64-bit)
- OS: Windows 10 Version 1809 (OS Build 17763.316)

**Additional context/Screenshots**
Old icon: 
![image](https://user-images.githubusercontent.com/18263553/52915695-f60c9580-32b5-11e9-93fc-f9e24c77ec49.png)

New icon: 
![image](https://user-images.githubusercontent.com/18263553/52915709-0c1a5600-32b6-11e9-9d0e-1df7852e9aff.png)

**Comment by howardchung** [comment]
Is this also a problem on the overview page? I assume it is since it's the same icon. Probably some CDN cache needs to be flushed

**Comment by guigax** [comment]
Yes, the same image shows up on the Overview page (the link to the Story one is [this](https://api.opendota.com/apps/dota2/images/items/sange_and_yasha_lg.png?3) and in the Overview is [this one](https://api.opendota.com/apps/dota2/images/items/sange_and_yasha_lg.png)), I have "Disable cache (while DevTools is open)", opened DevTools and did a Ctrl + F5 and it stayed the old icon

**Comment by howardchung** [comment]
Update: The image has been updated on the Valve side but the CDN cache still needs to be flushed. . . will see if we can figure that out

**Comment by howardchung** [comment]
Note: we can force the image to update by passing a query param in the request:
http://cdn.dota2.com/apps/dota2/images/items/sange_and_yasha_lg.png?t=1234

Maybe we should just do this in the client

**Comment by guigax** [comment]
I see, my worry is that in an eventual update by Valve, that link with the parameter gets removed, does it impact the client?

**Comment by howardchung** [comment]
No, the parameter just forces the new image to show up since i think the CDN permanently caches the first file it finds at that path.

**Comment by howardchung** [comment]
I updated the dotaconstants build script to add the current time as a query param so we always get the latest images. next deploy should fix this
