### ISSUE TITLE
Unknown Bounty Hunter buff

### ISSUE THREAD

**Issue by Argn0** [odota/web#2051]
need to investigate what this is. it's possibly track gold.

https://www.opendota.com/matches/4467511154

**Comment by coreymaher** [comment]
That's the stolen gold from Jinada, which I imagine came from https://github.com/odota/dotaconstants/commit/33a064df6dffbe3156187db96d08c5e0bdd7974d

Looks like the image needs to be updated.

**Comment by howardchung** [comment]
I think dotaconstants version needs to be bumped, I'll do it now
