### ISSUE TITLE
Missing Mars

### ISSUE THREAD

**Issue by bxyoung89** [odota/web#2056]
**Current Behavior**
Missing mars in the hero list.

**Expected behavior/code**
Would expect https://www.opendota.com/heroes/122 to direct to mars' hero page

**Console Output**

```
Whoops! Something went wrong. Hero 122 not found...
```

**Possible Solution**
Please add him to your database.

**Comment by howardchung** [comment]
This should be resolved with the data file update https://github.com/odota/web/commit/7b3ea4938f305add09ac244c04de7cbace3401f7
