### ISSUE TITLE
Blocked in russia

### ISSUE THREAD

**Issue by PhilippBalakin** [odota/web#2067]
Due to your site sharing IPs with some weird blocked site, many russian users cannot access opendota
https://isitblockedinrussia.com/?host=Opendota.com

**Comment by howardchung** [comment]
We're currently hosted by Netlify which apparently has an address in a blocked range:
https://www.reddit.com/r/Netlify/comments/9lvdvg/netlify_is_partly_blocked_by_censorship_in_russia/

I'll see what we can do

**Comment by howardchung** [comment]
Looks like this is actually cloudflare, testing shuffling the domain around various cloudflare accounts to fix the issue

**Comment by PhilippBalakin** [comment]
Whatever you did, for me the site became accessible again. Thanks!

**Comment by howardchung** [comment]
isitblockedinrussia still indicates it's blocked, but maybe it's not consistent?

**Comment by PhilippBalakin** [comment]
It was consistent for more than a month, now more than 4 people told me that its’s working again. I’ll keep you updated if anything changes, thanks!
