### ISSUE TITLE
rank medal not acutalized

### ISSUE THREAD

**Issue by gandalfelglande** [odota/web#2068]
I have ranked up 2 days ago to archon 2 to legend 2 ( solo and party mmr) and my pparty mmr is much higher, i'm now legend 2 but i dont have the medal actualized, it's normal?

**Comment by howardchung** [comment]
Do you have a link to your profile?

**Comment by gandalfelglande** [comment]
https://steamcommunity.com/id/GandoulfLeVieux/ 

id dota :153815405

**Comment by Argn0** [comment]
it shows that you're Legend 2.
https://www.opendota.com/players/153815405

**Comment by howardchung** [comment]
please let us know if there's a delay in it updating again (typically within 1-2 ranked games after the change)
