### ISSUE TITLE
http://yasp.co/ has a CloudFlare CNAME error

### ISSUE THREAD

**Issue by steve9164** [odota/web#2071]
**Current Behavior**
http://yasp.co/ has a CloudFlare error and no longer redirects to opendota

**Expected behavior/code**
http://yasp.co/ should redirect to opendota successfully

**Environment**
- Browser Version: Chrome 72.0
- OS: Windows 10

**Additional context/Screenshots**
```
Error 1014 Ray ID: 4b8c0147f919655d • 2019-03-17 03:50:50 UTC
CNAME Cross-User Banned
What happened?
You've requested a page on a website that is part of the Cloudflare network. The host is configured as a CNAME across accounts on Cloudflare, which is prohibited by security policy.

What can I do?
If you are interested in learning more about Cloudflare, please visit our website.
```

**Comment by howardchung** [comment]
Currently testing moving opendota around due to the Russia block issue in #2067 .

I think it can be resolved by moving yasp.co over as well, will try that later.

Is there a reason you're still using the yasp.co domain?

**Comment by howardchung** [comment]
should be fixed

**Comment by steve9164** [comment]
Cool. By the way my reasons for using yasp.co are an old bookmark (that I’ve updated) and yasp.co is slightly shorter to type (and 3 letters “yas” before there’s no other suggestions in a browser bar). Nothing major.

Nice work on the OpenAI sponsorship BTW. Good to see them utilising open source
