### ISSUE TITLE
Explorer: visual bars are outside of <tr>-element, causing the bottom-most bar to disappear

### ISSUE THREAD

**Issue by Fractura** [odota/web#2110]
**Current Behavior**
As an example I used this query: [opendota.com/explorer](https://www.opendota.com/explorer?minDate=&team=67&team=3&team=2586976&team=543897&team=2163&team=2626685&team=6214973&team=15&team=39&team=726228&team=1838315&team=1883502&group=player&select=fantasy_points&limit=&tier=&league=10681&league=10482&league=10810&result=&side=&megaWin=)
Within the results, the bars for winrate and winrate_wilson are showing outside the row/element they are supposed to be in. [0]

The bars being outside their expected box is not just confusing, it also causes the entry at the very bottom to not have any visible bars. [1] 

**Expected behavior/code**
The bars for visualization of winrate and winrate_wilson should be within the boundaries of the row to avoid confusion (and to avoid the bottom entry having none).

**Console Output**
Not applicable.

**Environment**
- Browser Version: Google Chrome Version 74.0.3729.131 (Official Build) (64-bit)
- OS: Microsoft Windows 10, Version 10.0.17763

**Possible Solution**
Move the bars up 5 to 6 pixels so they are well within the boundaries of the row they're supposed to be in. A "quick and dirty" fix is shown in [2], using `style="top: 16px;"` (instead of the inherited 22px).

**Additional context/Screenshots**
[0] [imgur link](https://i.imgur.com/dZU7IFB.png)
[1] [imgur link](https://i.imgur.com/Ua03X8H.png)
[2] [imgur link](https://i.imgur.com/f5oxKQF.png)

**Comment by Argn0** [comment]
if we change the top property then it might look ugly in other places where this percentage bar is being used.

I suggest setting the min height of table cells that contain this percentage bar to 32px.

**Comment by howardchung** [comment]
Yeah, that sounds good to me

**Comment by howardchung** [comment]
32px globally would probably also work unless we have small tables somewhere?
