### ISSUE TITLE
Missing new chatwheel responses

### ISSUE THREAD

**Issue by MrYadro** [odota/web#2152]
**Current Behavior**
404 for new audio files

**Expected behavior/code**
Audio files avaliable

**Console Output**

```
HTTP load failed with status 404. Load of media resource https://odota.github.io/media/chatwheel/dota_chatwheel_187.wav failed.
NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.
```

**Environment**
- Browser Version: [Firefox 69.0a1 (2019-06-29) (64-bit)]
- OS: [MacOS 10.14.5]

**Possible Solution**

Upload files here: https://github.com/odota/media/

**Comment by howardchung** [comment]
@mdiller do you remember if we had a script/auto process for this?

**Comment by mdiller** [comment]
Sorry, didn't see this till now. I ran the script and made a pull request for them:
https://github.com/odota/media/pull/3
