### ISSUE TITLE
Rename solo/party mmr to core/support mmr

### ISSUE THREAD

**Issue by Assaders** [odota/web#2172]
New update introduced core/support mmr instead of solo/party. Currently Opendota shows core mmr as solo, and support one as party.

**Comment by Fallyx** [comment]
What about having 2 additional lines in a different color? Because the change of solo/party mmr to core/support mmr could be temporary. The history would then show solo/party in blue/red until 5th of august and from 6th of august core/support in yellow/green (for example) until the end of season or longer if they keep this system.

**Comment by howardchung** [comment]
Does someone have a link to a profile with the new MMRs so I can see what the data is returning? If it's showing up the same I suspect Valve is reusing the same identifiers.

**Comment by Assaders** [comment]
It really seems like this, because profile showcase values (First match, Matches, Likes etc.) was renamed too (Solo -> Core mmr, Party -> Support). 
That link u need? That's my ODota link: https://www.opendota.com/players/51897268
![image](https://user-images.githubusercontent.com/19349290/62820186-4f6cc780-bb69-11e9-8c1a-ddcb20c2a190.png)

**Comment by Assaders** [comment]
Big gap at the end of graph is Party to Support mmr conversion

**Comment by howardchung** [comment]
Do you have the option to display your MMR in the client? I don't seem to have that option. From what I recall people who already had it showing can still display it, but not people who didn't already have it selected.

**Comment by Assaders** [comment]
I'm not sure about that you asking about. If you talking about profile showcase I mentioned before, now it looked like this and it doesn't show values as before (you can't select them if you didn't do it long time ago):
![image](https://user-images.githubusercontent.com/19349290/62847563-9086e800-bcdf-11e9-995d-011672e90a20.png)
MMR numbers now located at profile/stats section 
![image](https://user-images.githubusercontent.com/19349290/62847626-f2dfe880-bcdf-11e9-866f-6530be46c838.png)
dota_client_account_debug console debug:
```
CDOTAGameAccountClient:
account_id: 51897268
wins: 2788
losses: 2629
xp: 525
level: 149
initial_skill: 102
leaver_count: 0
low_priority_until_date: 0
prevent_text_chat_until_date: 1508519814
prevent_voice_until_date: 1508519814
last_abandoned_game_date: 1546294766
leaver_penalty_count: 1
completed_game_streak: 465
teaching: 762
leadership: 759
friendly: 755
forgiving: 750
account_disabled_until_date: 0
account_disabled_count: 0
match_disabled_until_date: 1558375756
match_disabled_count: 62
partner_account_type: PARTNER_NONE
low_priority_games_remaining: 0
competitive_2019_rank: 4198
competitive_2019_calibration_games_remaining: 0
solo_competitive_2019_rank: 5174
solo_competitive_2019_calibration_games_remaining: 0
recruitment_level: 230
has_new_notifications: true
is_league_admin: false
secondary_leaver_count: 79
last_secondary_abandoned_game_date: 1546691217
casual_games_played: 3381
solo_competitive_games_played: 1316
party_competitive_games_played: 591
casual_1v1_games_played: 0
curr_all_hero_challenge_id: 82
play_time_points: 858
account_flags: 3
play_time_level: 343
tourney_skill_level: 8
tourney_recent_participation_date: 1543082400
prevent_public_text_chat_until_date: 0
favorite_team: 152878446
anchored_phone_number_id: 292244525285901911
ranked_matchmaking_ban_until_date: 1508541687
recent_game_time_1: 1565465976
recent_game_time_2: 1565337658
recent_game_time_3: 1565212056
general_seasonal_ranked_calibration_games_remaining: 3
general_seasonal_ranked_games_played: 7
general_seasonal_rank_transferred: false
solo_seasonal_ranked_games_played: 0
solo_seasonal_rank_transferred: false
favorite_team_packed: 281582352776558
custom_game_disabled_until_date: 0
recent_win_time_1: 1565209260
recent_win_time_2: 1564864024
recent_win_time_3: 1564781219
coach_rating: 0
competitive_core_rank: 5174
competitive_core_calibration_games_remaining: 0
competitive_support_rank: 5114
competitive_support_calibration_games_remaining: 0
behavior_score: Normal
```

**Comment by howardchung** [comment]
OK, it sounds like Valve has just changed the labels and not how the sharing works. It's probably not intended to allow sharing MMR on the profile, so most people won't be able to do it.

With that in mind, maybe it just makes sense to have the client graph split the data based on date, and create new series to plot on the graph, rather than changing the backend/data schema since the whole core/support MMR concept is an experiment anyway.
