### ISSUE TITLE
Winner Tag issue in Teamfights tab

### ISSUE THREAD

**Issue by GoldMath** [odota/web#2180]
**Current Behavior**
![Capture](https://user-images.githubusercontent.com/7282547/63032608-6dfaf780-beb6-11e9-9b91-9f6d8b65eac8.JPG)

Hello, when looking at **Teamfights** the wrong team have the **Winner** tag.
In this screenshot the double-swords was correctly Radiant (green) but the Dire team was tagged Winner. 

**Expected behavior/code**
The team winning the most gold post-teamfights should be tagged as Winner.
The Winner tag could also use a better background color for quicker visibility.

**Environment**
- Browser Version: Brave (0.67.124) based on Chromium: 76.0.3809.100
- OS: Windows 10

Regards,

**Comment by Argn0** [comment]
That tag indicates that the team won the match. I understand it could be confusing though.

**Comment by howardchung** [comment]
I agree. Maybe we could remove on just that tab?
