### ISSUE TITLE
Histograms/Trends: Duration display as seconds instead of minutes

### ISSUE THREAD

**Issue by GoldMath** [odota/web#2184]
**Current Behavior**
Hello, when you look at your Duration in **Histograms** or **Trends** the labels, median and tooltips are only display as seconds making it difficult to quickly read and understand the values. 

**Expected behavior/code**
A second line in the label, or simply replaced with the converted values to minutes would be welcome.
(38:53 instead of 2312)

**Environment**
- Browser Version: Brave (0.67.125) based on Chromium: 76.0.3809.100
- OS: Windows 10

Regards,

**Comment by howardchung** [comment]
I think recharts has formatting functions we can implement. We should be able to do this.

**Comment by bdbch** [comment]
I created a fix for this, see #2212
