### ISSUE TITLE
On /heroes, <ReactTooltip/> downloads _vert.jpg for all heroes on initial render 

### ISSUE THREAD

**Issue by 3nuc** [odota/web#2188]
**Current Behavior**
If you go to /heroes, and open the devtools then go to Network, then filter to see only images, you'll see that the component downloads two images for each hero. One you see in the table, the second one you see once you hover over the first image.
![image](https://user-images.githubusercontent.com/5359825/63228141-7bceb680-c1ef-11e9-8459-c758480dfbd5.png)
![image](https://user-images.githubusercontent.com/5359825/63228206-22b35280-c1f0-11e9-8051-f423111e724f.png)

**Expected behavior/code**
The second tooltip images should be lazy-loaded/code-splitted so they download only when the user hovers over the image.

**Console Output**
N/A

**Environment**
- Browser Version: Google Chrome | 76.0.3809.100 (Official Build) (64-bit)
Revision | ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}

- OS: Ubuntu on KDE

**Possible Solution**
This is `/src/components/Visualizations/Table/HeroImage.jsx` on line 610. 

```
<HeroImage id={heroID} imageSizeSuffix={IMAGESIZE_ENUM.VERT.suffix} />
```

The component itself ok, it just needs to be lazy loaded.

**Comment by howardchung** [comment]
Yeah, it looks like we're pre-mounting all these components into the DOM and just toggling visibility

**Comment by howardchung** [comment]
For OpenUnderlords we put the ReactTooltip component in the top level App and then just swap its contents, which is what we should also do here. It will likely improve page load times a lot:
https://github.com/odota/underlords-web/search?q=react-tooltip&unscoped_q=react-tooltip

**Comment by Argn0** [comment]
This only affects hero tooltips. The item and ability tooltips are mounted on hover.

We could just simply use the same workaround for hero tooltips as well until the ReactTooltip component is moved to top level? Not sure how much work refactoring the ReactTooltip component will be.

**Comment by howardchung** [comment]
I think this bit of code controls the Hero tooltips:
https://github.com/odota/web/blob/85b0d644c33f5fd1f5c8d93f7b7be8c951bed4df/src/components/Visualizations/Table/HeroImage.jsx#L606

I'm not entirely sure what's different about it than the Ability tooltip:
https://github.com/odota/web/blob/1e0586a2f1100ac5978e4b6994ca2f803e338cc1/src/components/Hero/Ability.jsx

**Comment by howardchung** [comment]
The ability one seems to be using nanoid() to generate a unique ID

**Comment by Argn0** [comment]
It's here https://github.com/odota/web/blob/1e0586a2f1100ac5978e4b6994ca2f803e338cc1/src/components/Visualizations/inflictorWithValue.jsx#L186

```onMouseEnter={this.setShowTooltip}```

**Comment by Argn0** [comment]
and

```
{this.state.showTooltip &&
              <ReactTooltip id={ttId} effect="solid" place="left">
                {tooltip}
              </ReactTooltip>
}

**Comment by howardchung** [comment]
Oh, I see, so we're also pre-mounting all the ability tooltips e.g. on https://www.opendota.com/matches/4972785319 as well. Probably worth fixing there as well.

**Comment by howardchung** [comment]
The OpenUnderlords approach doesn't seem too hard to implement, we just have to add a getContent prop to the ReactTooltip component I think, and then updating the data-tip prop on the hovered element updates the tooltip as well?

**Comment by Argn0** [comment]
The ability tooltips are each their own component and conditionally rendered on hover. I don't think they're pre-mounted.

What makes you think they're pre-mounted?

**Comment by Argn0** [comment]
Does React mount conditionally rendered components?

**Comment by howardchung** [comment]
Oh, I think I might have searched wrong. I tried to look for a class name and found a ton of results but that might have been in the stylesheet and not the actual DOM.

**Comment by howardchung** [comment]
It is true that we don't remove tooltips even after they disappear, and we don't reuse the same tooltip component for multiple tooltips, even though only one can show at a time.
