### ISSUE TITLE
README.md: stage.opendota.com Not Found

### ISSUE THREAD

**Issue by GoldMath** [odota/web#2189]
**Current Behavior**
When looking at the **README.md** the link to the last build website (https://stage.opendota.com/) say "**Not Found**", probably outdated or deleted?

**Expected behavior/code**
Update or remove the link?

**Environment**
- Browser Version: Brave (0.68.131) based on Chromium: 76.0.3809.100
- OS: Windows 10

**Comment by howardchung** [comment]
Yes, it broke while I was moving some things a while ago. We can remove it from the README, unless someone really wants to it back,
