### ISSUE TITLE
i cant see my score in opendota

### ISSUE THREAD

**Issue by renegade37makedifference** [odota/web#2205]
**Current Behavior**
A clear and concise description of the behavior.

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by renegade37makedifference** [comment]
![image](https://user-images.githubusercontent.com/55846881/65702952-c403b300-e090-11e9-8a71-ea15ed6b8e8d.png)

**Comment by Argn0** [comment]
Did you enable the "expose publich match data" option?

Here is how to do it : https://www.youtube.com/watch?v=rXh40-tKjL4

**Comment by bdbch** [comment]
Seems like this is a core issue since the backend already returns empty data for your profile. @albertcui what do you think?

**Comment by howardchung** [comment]
Yeah, this can be closed.
