### ISSUE TITLE
specific Game Mode Ability Draft stats don't work

### ISSUE THREAD

**Issue by troicy** [odota/web#2206]
**Current Behavior**
I mainly play Ability draft and I cannot find stats for heroes, records or even wardmaps for this mode. Basically the only thing that works is "overview" and "activity" for this mode.

**Expected behavior/code**
When I choose "Ability Draft" as a game mode it should show me the specific items.

**Additional context/Screenshots**
https://www.opendota.com/players/98641119/heroes?game_mode=18
![image](https://user-images.githubusercontent.com/56112939/66115805-d9696780-e5d1-11e9-9716-1da60cdcf5b4.png)
![image](https://user-images.githubusercontent.com/56112939/66115837-ea19dd80-e5d1-11e9-9a83-d8ddf61a4387.png)

**Comment by howardchung** [comment]
You need to enable the "include insigificant" filter to get them to show up.
