### ISSUE TITLE
parse is not working

### ISSUE THREAD

**Issue by helicopter8841** [odota/web#2207]
Parse is not working. Any match everlasting loading.
![56](https://user-images.githubusercontent.com/56151588/66191686-91147d00-e697-11e9-9e9b-0f5153a2f6f8.png)

**Comment by helicopter8841** [comment]
![57](https://user-images.githubusercontent.com/56151588/66192170-90301b00-e698-11e9-9409-9730a315ce9e.png)

**Comment by howardchung** [comment]
There is currently heavy load on the request endpoint, probably someone submitting a lot of automated requests. I've tightened the rate limit and am monitoring the situation.

**Comment by helicopter8841** [comment]
It receives the correct request, the data is loaded, but something blocks the output of information on the page.
In any case, thanks for the prompt assistance in this problem.
![1](https://user-images.githubusercontent.com/56151588/66197700-a2638680-e6a3-11e9-9f7b-def5c63c3367.png)
![2](https://user-images.githubusercontent.com/56151588/66197702-a2638680-e6a3-11e9-9291-66760e7585a2.png)

**Comment by nitsuga7** [comment]
I can't parse either :(

**Comment by helicopter8841** [comment]
Yep, - new day, new problem:
At this moment we can see next frightening picture)
![1](https://user-images.githubusercontent.com/56151588/66254704-ca75e700-e782-11e9-95bc-21a6fd59a358.png)

but...
if we look at "developer tools" -> "network", we'll see that information:
![2](https://user-images.githubusercontent.com/56151588/66254869-2c375080-e785-11e9-9c91-9834f3f9bb74.png)
![3](https://user-images.githubusercontent.com/56151588/66254870-2c375080-e785-11e9-9b42-533043559ff0.png)

If I if I get it right - it gave information what we need (scr.2), but he can't show it to us correctly...
Well, I hope you can fix it)

**Comment by howardchung** [comment]
The queue is still building, I've temporarily disabled requesting until it drains a bit so people don't keep retrying and making the problem worse.

**Comment by howardchung** [comment]
This issue should now be resolved, thanks for your patience!
