### ISSUE TITLE
Implement @material-ui theme provider

### ISSUE THREAD

**Issue by bdbch** [odota/web#2220]
**Is your feature request related to a problem? Please describe.**
Currently we have to write our own styled components for material-ui which doesn't make sense. If we try to implemented the new @material-ui library, we should also add their new ThemeProvider.

See: https://material-ui.com/customization/theming/

**Describe the solution you'd like**
Implement ThemeProvider with correct theming configuration.

**Comment by howardchung** [comment]
One thing I don't love about this is that the themes are specific to material-ui. If we decide to move off the library or write our own code, it's not immediately clear what styles will be missing.

**Comment by bdbch** [comment]
@howardchung thats true. I think we could create a general theming configuration which we can transform to the material-ui theme configuration so if we decide to not use material-ui anymore, we can still use our own theming configuration and map it to whatever library we want to use.

**Comment by bdbch** [comment]
In general I also started doing this ticket in combination with #2226

**Comment by howardchung** [comment]
I think we are looking to move on from material-ui and styled-components more generally, so closing this issue
