### ISSUE TITLE
Replace mobile menu drawer with @material-ui/core drawer

### ISSUE THREAD

**Issue by bdbch** [odota/web#2222]
Since we want to switch to the new @material-ui-migration we need to replace the mobile drawer menu. Should we maybe even move the main menu into a drawer and just keep a search + settings on the navbar?

See:
https://material-ui.com/components/drawers/

**Comment by howardchung** [comment]
Yeah, that makes sense to me. If we do that (switch to drawer for small viewports) then we may not even need the change in https://github.com/odota/web/pull/2215 to collapse the menus?

**Comment by howardchung** [comment]
Correction, it's https://github.com/odota/web/pull/2219/files I'm referring to that we might not need.
