### ISSUE TITLE
Rank distributions incorrect after Oct 10 matchmaking update

### ISSUE THREAD

**Issue by luluyume** [odota/web#2229]
**Issue**

Rank distributions at https://www.opendota.com/distributions are incorrect after the 10 October 2019 [matchmaking update](http://blog.dota2.com/2019/10/continuing-matchmaking-updates/). Valve changed the amount of stars per tier from seven back to five, so the website is not reading the distributions correctly anymore.

![image](https://user-images.githubusercontent.com/43284013/66656854-a20f4200-ebf3-11e9-81cf-3908c009c5f4.png)

**Comment by howardchung** [comment]
We could just wait it out, eventually players will play another game and the data should update.

At the next ranked season the data will also clear.
