### ISSUE TITLE
Items appearing and disappearing. 

### ISSUE THREAD

**Issue by Yrdi** [odota/web#2230]
After a match has been parsed some item rows will display correctly and others will not. The items will hide behind other items and only show up when you hover over or near the item it is behind.

Doesn't happen in all matches, or all browsers. Bug can be replicated on chrome and chrome based browsers but not on Firefox.

Also seems to go away if you just F5 refresh the page,

![2019-10-11_22-29-41](https://user-images.githubusercontent.com/6851466/66686546-b7c64b00-ec77-11e9-8173-53f25b67bd31.gif)

**Comment by howardchung** [comment]
The fact that it happens when the tooltip is triggered seems to suggest it might be related to tooltips?

@bdbch recently redid the tooltips, maybe we can check if this issue repros on the new version

**Comment by howardchung** [comment]
We have checked in a possible fix for this, please comment if it's still appearing.

**Comment by Argn0** [comment]
it's still appearing
