### ISSUE TITLE
Matches are delayed/not appearing

### ISSUE THREAD

**Issue by ZenMasta** [odota/web#2232]
**Current Behavior**
Matches are delayed/not appearing. If I view my own, or someone elses profile, not all of the matches are displaying. Seems like starting with games from today October 12th. 

**Expected behavior/code**
Generally new completed matches are listed within a few minutes of completion. 

**Console Output**
not available. 

**Environment**
Edge 79.0.294.1 (dev)
- OS: [ Windows 10 ]

I am unable to parse specific matches either, for example 5066247016
It's only showing 2 of 4 matches today.

**Comment by howardchung** [comment]
New matches were stuck due to a bad API response. It's catching up now.
