### ISSUE TITLE
monthly api limit exceeded

### ISSUE THREAD

**Issue by jon1267** [odota/web#2239]
I'm trying to get your api data. GET request is https://api.opendota.com/api/players/{steamID32}/recentMatches?api_key={my api key} 
I'm get next message: "{"error": "monthly api limit exceeded"}".  What wrong with request, or my api key or my production domain ,,,

I need help please !!!

---

If you have a support request or question please also check our Discord Server: https://discord.gg/opendota

**Comment by howardchung** [comment]
This looks correct, and if your key is being passed properly it should not hit a monthly rate limit. Make sure there's no extra text at the end of the URL. You can email api@opendota.com with support questions as well.
