### ISSUE TITLE
I hope to get a fast and iterative official openDota APP

### ISSUE THREAD

**Issue by AlexLWT** [odota/web#2247]
I am an ordinary **Chinese player** who loves **dota2**. Now this era has been the era of **app**, and it is really not very convenient to search things on the web page every time.
In China, every service always has a variety of user-friendly solutions (such as apps), but openDota is not maintained by the Chinese, so only features like Max + are very simplified.I think it will benefit all users if an official app is launched with an immediate iteration
At the same time, I hope this app will support more languages, all for the user experience!

**Comment by howardchung** [comment]
We have an OpenDota app on the Google and Apple stores, although I'm not sure if they're accessible in China.

The app is not yet localized, and doesn't support all of the features of the web version.

**Comment by AlexLWT** [comment]
> 我们不确定Google和Apple商店中是否有OpenDota应用，尽管我不确定在中国是否可以使用它们。
> 
> 该应用程序尚未本地化，并且不支持网络版本的所有功能。

Thank you very much for your answer. However, I found that I had installed the openDota app modified by others. The app is available in mainland China, but its functions are still very simple.
In addition, dota BBS in China has lost a large number of players who love dota. I hope you can give us a surprise when the game version is updated

**Comment by bdbch** [comment]
I'd suggest we try to improve the apps performance and UX/UI to make it viable as a PWA. After that we could wrap it with Capacitor and replace our current RN app. I don't think we really need a RN application for that.

Thoughts?

**Comment by AlexLWT** [comment]
Maybe it's a cultural difference

**Comment by AlexLWT** [comment]
> I'd suggest we try to improve the apps performance and UX/UI to make it viable as a PWA. After that we could wrap it with Capacitor and replace our current RN app. I don't think we really need a RN application for that.
> 
> Thoughts?

Maybe it's a cultural difference

**Comment by bdbch** [comment]
@AlexLWT not really. We also use a lot of apps in the western world. The problem is just that developing a native application takes a lot of resources and doubles the amount of work.

Since the app itself does not use any native feature it doesn't make sense to develop a native app. We can improve the current website to load offline and have better caching + performance so you can install it to your phone and open it from the home screen.

**Comment by bdbch** [comment]
https://www.openunderlords.com/ is a PWA application already and could be wrapped into a native container so you can install it from the appstore.

I think native apps for just "content" consuming apps is not a necessary thing.
