### ISSUE TITLE
Tome of Experience string isn't interpolated

### ISSUE THREAD

**Issue by ahi-el** [odota/web#2256]
**Current Behavior**
When hovering over 'tome of experience' in a match, the following is shown:
![image](https://user-images.githubusercontent.com/37062459/67796400-a5764a80-fa88-11e9-98eb-5b1b16551153.png)

The description is gotten from https://github.com/odota/dotaconstants/blob/master/build/items.json

and then rendered here:
https://github.com/odota/web/blob/master/src/components/ItemTooltip/index.jsx

at line 232. This looks like it should be an easy fix,  but I don't see where the "%customval_team_tomes_used% is meant to be interpolated

**Expected behavior/code**
The description should interpolate "%customval_team_tomes_used%" for the actual value (other items possibly affected by this too)

**Comment by howardchung** [comment]
I'm pretty sure this is only used in-game and probably should just be removed from our tooltip.

**Comment by hooahest** [comment]
that explains it then

I know this is a small issue but what do you think about deleting lines with '/n%.*%' in them? should be an easy fix

**Comment by howardchung** [comment]
This customval one might be unique. I also see some instances of %abilitycastrange% that we might be using on some items.

**Comment by hooahest** [comment]
since this is relevant only to tome of knowledge and is pretty minor, I'm closing this

**Comment by howardchung** [comment]
I'd keep this open since it is a real issue, even if minor

**Comment by Argn0** [comment]
Or we could just make it display how many Tomes were used.

**Comment by howardchung** [comment]
That may not be possible in all situations since I think we also use the tooltip outside match contexts (e.g. scenarios, explorer)

**Comment by guastallaigor** [comment]
> since this is relevant only to tome of knowledge and is pretty minor, I'm closing this

Just to let you guys know, this is relevant also to "Range: %abilitycastrange%" or "Allied Range: %abilitycastrange%" from Ethereal Blade for example.

**Comment by sohan-shingade** [comment]
I want to try fixing this but I don't know where variables like abilitycastrange and customval_team_tomes_used are declared.

**Comment by ZoraizQ** [comment]
This issue was fixed from odota/dotaconstants
