### ISSUE TITLE
Link to profile is missing in menu on mobile 

### ISSUE THREAD

**Issue by jim-moody** [odota/web#2259]
**Current Behavior**
The profile link is not present in the menu so there’s no way to see my own stats

**Expected behavior/code**
There used to be a link labeled “My Profile” which would navigate to my personal stats page but that is missing 
![8186FCF8-6D05-43B0-ADD0-BB5DED45BF95](https://user-images.githubusercontent.com/26190589/68072321-d097bd00-fd5a-11e9-9566-dba63625f636.png)

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Chrome mobile on iPhone 8

**Possible Solution**
It’s possible that the link is there, but I can’t actually scroll down in the menu, when I try to scroll, the whole menu just moves. 

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by howardchung** [comment]
Whoops! @bdbch I guess we need to add this back as the top option?

**Comment by bdbch** [comment]
@howardchung I'm on it!

**Comment by bdbch** [comment]
Pull Request is out:
https://github.com/odota/web/pull/2260

**Comment by jim-moody** [comment]
Its fixed, thank you!!
