### ISSUE TITLE
I have nothing on my profile. it's been this way since i can't remember.

### ISSUE THREAD

**Issue by jooheechou** [odota/web#2266]
No match history, no replays parsed, no win no loss no everything..

help?

**Comment by jooheechou** [comment]
https://www.opendota.com/players/891454065 
![sdadadad](https://user-images.githubusercontent.com/57351606/68122638-c38af180-ff45-11e9-8bc7-08db3fac6a5b.JPG)

**Comment by bdbch** [comment]
I was able to reproduce this with the profile of a friend of me. Seems like new registrations don't get fetched. @howardchung do you have an idea what could go wrong here?

**Comment by jooheechou** [comment]
> I was able to reproduce this with the profile of a friend of me. Seems like new registrations don't get fetched. @howardchung do you have an idea what could go wrong here?

i think I login my account a long time ago (it was a different steam name then) and I wanted to download a replay using opendota ... but when I tried to login my steam account , it is still the same..

**Comment by howardchung** [comment]
Did you toggle on the Expose Public Match Data setting in-game?
