### ISSUE TITLE
Items bought on Hero recent matchups

### ISSUE THREAD

**Issue by worthy7** [odota/web#2269]
**Is your feature request related to a problem? Please describe.**
The problem is I want to see at a glance the general kinds of item builds people are using for a hero but I can't

**Describe the solution you'd like**
I would like to see inventory snapshots of the hero for each matchup on the "recent" page. I am guessing each match may need it's own API call, thus a checkbox at the top "Show items" (off by default) might be good, when on will display 5 min snapshot builds of the hero during that match.

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?
![image](https://user-images.githubusercontent.com/4762399/68173099-2e2b4400-ffbd-11e9-9fb6-cdbd55259265.png)

This looks a bit cramped because I stretched the image in MS paint, but you get the idea. It's an option since it wont look nice for people using mobile for example.

Alternative 1, replace the KDA section when the item builds are shown. A toggle for that column (for aesthetics) instead of adding it on to the end.

Alternative 2, the inventory snapshots show below each row, instead of on the right side of each row. This gives them more space width-wise
![image](https://user-images.githubusercontent.com/4762399/68173293-e822b000-ffbd-11e9-88cd-71341a580407.png)

**Comment by worthy7** [comment]
Later this could be expanded into some kind of "common items" feature where we take the most recent 1000 games for a hero, snapshot their inventory at each 5 minute mark, then display % on each item for how many games had that item at that minute mark. Separate feature though really.

**Comment by worthy7** [comment]
Another alternative, to just show the final item build, the same as the match overview page - instead of every 5 minutes.
![image](https://user-images.githubusercontent.com/4762399/68174100-33d65900-ffc0-11e9-90b4-50881e14baa0.png)

**Comment by howardchung** [comment]
I think storing the final items for each player here would be OK. I think there's another issue open requesting that, but it won't be available for old matches.

**Comment by howardchung** [comment]
see https://github.com/odota/web/issues/2026

**Comment by worthy7** [comment]
@howardchung I see, that other request is the same as my "another alternative" so I would say that is sufficient if it can be done.
