### ISSUE TITLE
Items unordered in match review page

### ISSUE THREAD

**Issue by worthy7** [odota/web#2270]
**Current Behavior**
Items ordered randomly (by name?)

**Expected behavior/code**
Items ordered by time

![image](https://user-images.githubusercontent.com/4762399/68173880-b7dc1100-ffbf-11e9-97c9-0e49ed6aeda6.png)

**Comment by howardchung** [comment]
They are ordered in the player's inventory in-game.

**Comment by worthy7** [comment]
@howardchung Hold on, that's not helpful is it. Can we order them by time then please. Nobody cares what order they are in the inventory.

**Comment by howardchung** [comment]
Actually, it's one way of tracking smurfing as players tend to keep certain items in the same inventory slots.

**Comment by worthy7** [comment]
OK well if you that that order is more important/relevant that the time order then you can go ahead and close this.
