### ISSUE TITLE
Hello, I've been trying to parse this game.. can this game still be parsed so I can download it? this game is very funny match id: 5098895352 

### ISSUE THREAD

**Issue by jooheechou** [odota/web#2274]
**Explain your question as detailed as possible**

I need help with...

---

If you have a support request or question please also check our Discord Server: https://discord.gg/opendota

**Comment by howardchung** [comment]
Unfortunately it looks like Valve lost the replay: http://replay144.valve.net/570/5098895352_1634957267.dem.bz2
