### ISSUE TITLE
Skills that are either ground- or target-cast only count up when target-cast

### ISSUE THREAD

**Issue by eeitobi** [odota/web#2280]
On the casts tab, skills like Lina's Dragon Slave or Lion's Earth Spike are not summed up correctly. This seems to happen when a skill can either be cast directly on a target (in which case it is summed up correctly) or be ground-targeted (in which case it isn't included in the summation).

I remember in the past there was a feature that would show the total casts when hovering over the sum of target-casts, but that doesn't seem to be there anymore.

Suggestion: Show the total number of times the ability was cast on the ability icon, then in the breakdown show how many times which hero was directly targeted with it - the two numbers won't add up, but it should be clear that the ability can be cast without a target on creep waves etc.

For reference: https://www.opendota.com/matches/5105025673/casts

**Comment by hooahest** [comment]
it's also inconsistent currently as is. In your match, the 'hit' dragon slaves is a higher number than the 'cast' dragon slaves

I'll look into this

**Comment by hooahest** [comment]
found the issue - in TargetBreakdowns.js function processCasts, it ignores the total casts of a spell if it has any target hits - which is why in that match Lina cast 74 LSA, yes dragon slave has 16

The number of times cast should not be dependent on the targets hit. I'll open a PR later to fix this

**Comment by howardchung** [comment]
Yeah, I think we should show 65 instead of 16 there on Dragon Slave. Thanks for tracking it down!
