### ISSUE TITLE
Cumulative CS in laning doesn't show for the last player

### ISSUE THREAD

**Issue by zachkont** [odota/web#2281]
**Current Behavior**
Cumulative CS in Laning tab inside tooltip when hovering over minute is not visible for the last player due to `overflow-y: hidden`

**Expected behavior/code**
It should be visible as it is for all other players

**Console Output**
N/A

**Environment**
- Browser Version: Chrome Version 78.0.3904.87 (Official Build) (64-bit)
- OS: Windows 10

**Possible Solution**
Add some padding or move the tooltip higher

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/17274058/68546367-2a912600-03de-11ea-9fa6-4f9fe16f242d.png)
![image](https://user-images.githubusercontent.com/17274058/68546377-3a106f00-03de-11ea-8a12-2255b6b5667f.png)

**Comment by hooahest** [comment]
I'll look into this later

**Comment by Argn0** [comment]
I don't think there is a straight forward way to prevent the overflow. Just position the tooltip a few pixel higher.
