### ISSUE TITLE
Wrong tab on player page

### ISSUE THREAD

**Issue by carceri** [odota/web#2282]
**Current Behavior**
Wrong tab when you click player profile

**Expected behavior/code**
`OVERVIEW` tab instead of `PEERS` after you click another person

**Console Output**
clear

**Environment**
Firefox 71.0

**Additional context/Screenshots**
https://imgur.com/a/OXSBFhJ

**Comment by howardchung** [comment]
@bdbch possibly has to do with the refactor to tabs?

**Comment by bdbch** [comment]
I'll look into it!

**Comment by bdbch** [comment]
Thanks, was able to reproduce this bug. I'll fix it ASAP!

**Comment by bdbch** [comment]
PR is out:
https://github.com/odota/web/pull/2286
