### ISSUE TITLE
occasional CI failures on chrome

### ISSUE THREAD

**Issue by howardchung** [odota/web#2287]
Looks like occasionally CI will fail with an HTTP error, which should not happen since we cache our responses in files.

Example:
https://travis-ci.org/odota/web/builds/609668899?utm_medium=notification&utm_source=github_status

I'll investigate, but @Argn0 might know about this

**Comment by howardchung** [comment]
Looks like it's trying to make a request to /explorer?minDate=2018-08-01T13%3A03%3A40.498Z which it's not finding

**Comment by mezba1** [comment]
Looks like /explorer?minDate=2018-08-01T13%3A03%3A40.498Z is the first path tested and by the time testcafe runs test for that path the app might still be in booting state (serve -s build). I think adding a delay in testcafe (--app-init-delay) might solve the problem.

**Comment by howardchung** [comment]
Do you want to investigate further?

**Comment by Argn0** [comment]
I wanted to keep this open, since the error is still happening in Chrome and someone might want to figure out why.
