### ISSUE TITLE
Null received from API

### ISSUE THREAD

**Issue by MMA15** [odota/web#2296]
For some player matches we have been receiving `null` as their damage, stuns, hero_kills, etc.
A couple of examples: 
https://api.opendota.com/api/matches/402089254
https://api.opendota.com/api/matches/5120391172

We  should be receiving the correct value for each player, not null.

**Comment by howardchung** [comment]
These fields are only available for parsed matches. You can request a parse of matches that are less than 10 days old.

**Comment by MMA15** [comment]
@howardchung  thank you for the quick response. Sorry what do you mean by parsed matches?

**Comment by howardchung** [comment]
A lot of extra data per match comes from the replay file. We don't always process this file since it's relatively expensive.

**Comment by MMA15** [comment]
Just a couple of quick questions. Typically how long does it take to process a parse request?
When parsing a request, does `null` indicate that it has been completed? (i.e. https://api.opendota.com/api/request/116868683?api_key=d5f6f92d-77ff-461c-a6bb-8d54f57d0862) 
Also if that is the case, for this match 402089254, it did not actually work. https://api.opendota.com/api/matches/402089254

**Comment by howardchung** [comment]
Parse requests generally take under a minute.

This match is too old to be parsed, the replay is no longer available.

**Comment by MMA15** [comment]
Ah that makes sense. and when parsing a request, does receiving `null` indicate that it has been completed?

**Comment by howardchung** [comment]
Yes, it does

**Comment by MMA15** [comment]
Ty for the quick responses. This is unrelated but of one our users says he played a morphling match an hr or two before the faceless void Match. Can you think of any reason for it to not show up? He said somebody in the game did abandon but shouldn't the match still show?

https://www.opendota.com/players/402089254

**Comment by howardchung** [comment]
There were some delays processing matches earlier today, which should be recovering now.

**Comment by MMA15** [comment]
@howardchung does it make sense if we proceed like so:
- POST /parse
- GET /request/{jobId}
- while (timeLapsed < 5s) { check if GET /request/{jobId} === null, sleep 0.5s  }
would that be the best way to confirm if the match has been parsed
We will be paying for the requests we make, so trying to optimize that. 

please let me know what you think of our strategy.

**Comment by howardchung** [comment]
You can wait longer intervals between checking for completion. You should also make requests only for matches that aren't too old, as otherwise the replays will have expired.

**Comment by howardchung** [comment]
Also returning null just means the job is no longer in the queue, it does not indicate whether the match successfully parsed or whether it could not process the replay. You'll have to check the match data endpoint again for that.

**Comment by MMA15** [comment]
Thank you for the quick replies.
