### ISSUE TITLE
Errors about CORS when using IPv6

### ISSUE THREAD

**Issue by TableCraft0R** [odota/web#2297]
`2662adba8547ee70c1d3b2372a3011b537cb31fba.js:1 GET https://api.opendota.com/api/players/153747782/recentMatches? 429
t @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
getPlayerRecentMatches @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
nh @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
value @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
t.unstable_runWithPriority @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Wr @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
vl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
rl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
el @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Hl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Gl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
ul @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Zl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
render @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
925 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
535 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
c @ 153747782:1
n @ 153747782:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
153747782:1 Access to fetch at 'https://api.opendota.com/api/players/153747782/recentMatches?' from origin 'https://www.opendota.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
backend.js:6 TypeError: Failed to fetch
r @ backend.js:6
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Promise.catch (async)
t @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
getPlayerRecentMatches @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
nh @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
value @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
t.unstable_runWithPriority @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Wr @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
vl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
rl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
el @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Hl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Gl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
ul @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Zl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
render @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
925 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
535 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
c @ 153747782:1
n @ 153747782:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
2662adba8547ee70c1d3b2372a3011b537cb31fba.js:1 GET https://api.opendota.com/api/players/153747782/counts? 429
t @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
getPlayerCounts @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
nh @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
value @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
t.unstable_runWithPriority @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Wr @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
vl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
rl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
el @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Hl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Gl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
ul @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Zl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
render @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
925 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
535 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
c @ 153747782:1
n @ 153747782:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
153747782:1 Access to fetch at 'https://api.opendota.com/api/players/153747782/counts?' from origin 'https://www.opendota.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
backend.js:6 TypeError: Failed to fetch
r @ backend.js:6
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Promise.catch (async)
t @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
getPlayerCounts @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
nh @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
value @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
t.unstable_runWithPriority @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Wr @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
vl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
rl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
el @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Hl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Gl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
ul @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Zl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
render @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
925 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
535 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
c @ 153747782:1
n @ 153747782:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
2662adba8547ee70c1d3b2372a3011b537cb31fba.js:1 GET https://api.opendota.com/api/players/153747782? 429
t @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
getPlayer @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
value @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
t.unstable_runWithPriority @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Wr @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
vl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
rl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
el @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Hl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Gl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
ul @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Zl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
render @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
925 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
535 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
c @ 153747782:1
n @ 153747782:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
153747782:1 Access to fetch at 'https://api.opendota.com/api/players/153747782?' from origin 'https://www.opendota.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
backend.js:6 TypeError: Failed to fetch
r @ backend.js:6
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Promise.catch (async)
t @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
getPlayer @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
value @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
t.unstable_runWithPriority @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Wr @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
vl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
rl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
el @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Hl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Gl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
ul @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Zl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
render @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
925 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
535 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
c @ 153747782:1
n @ 153747782:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
2662adba8547ee70c1d3b2372a3011b537cb31fba.js:1 GET https://api.opendota.com/api/players/153747782/peers 429
Jp @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
value @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
t.unstable_runWithPriority @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Wr @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
vl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
rl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
el @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Hl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Gl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
ul @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Zl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
render @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
925 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
535 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
c @ 153747782:1
n @ 153747782:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
153747782:1 Access to fetch at 'https://api.opendota.com/api/players/153747782/peers' from origin 'https://www.opendota.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
2662adba8547ee70c1d3b2372a3011b537cb31fba.js:1 GET https://api.opendota.com/api/players/153747782/wl? 429
t @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
getPlayerWinLoss @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
value @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
t.unstable_runWithPriority @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Wr @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
vl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
rl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
el @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Hl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Gl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
ul @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Zl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
render @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
925 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
535 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
c @ 153747782:1
n @ 153747782:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
153747782:1 Access to fetch at 'https://api.opendota.com/api/players/153747782/wl?' from origin 'https://www.opendota.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
backend.js:6 TypeError: Failed to fetch
r @ backend.js:6
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Promise.catch (async)
t @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
getPlayerWinLoss @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
value @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
t.unstable_runWithPriority @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Wr @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
vl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
rl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
el @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Hl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Gl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
ul @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Zl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
render @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
925 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
535 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
c @ 153747782:1
n @ 153747782:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
2662adba8547ee70c1d3b2372a3011b537cb31fba.js:1 GET https://api.opendota.com/api/players/153747782/peers? 429
t @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
getPlayerPeers @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
nh @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
value @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
t.unstable_runWithPriority @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Wr @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
vl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
rl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
el @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Hl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Gl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
ul @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Zl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
render @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
925 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
535 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
c @ 153747782:1
n @ 153747782:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
153747782:1 Access to fetch at 'https://api.opendota.com/api/players/153747782/peers?' from origin 'https://www.opendota.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
backend.js:6 TypeError: Failed to fetch
r @ backend.js:6
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Promise.catch (async)
t @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
getPlayerPeers @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
nh @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
value @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
t.unstable_runWithPriority @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Wr @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
vl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
rl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
el @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Hl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Gl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
ul @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Zl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
render @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
925 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
535 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
c @ 153747782:1
n @ 153747782:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
2662adba8547ee70c1d3b2372a3011b537cb31fba.js:1 GET https://api.opendota.com/api/players/153747782/heroes? 429
t @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
getPlayerHeroes @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
nh @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
value @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
t.unstable_runWithPriority @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Wr @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
vl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
rl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
el @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Hl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Gl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
ul @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
Zl @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
render @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
925 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
535 @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
l @ 153747782:1
c @ 153747782:1
n @ 153747782:1
(anonymous) @ 662adba8547ee70c1d3b2372a3011b537cb31fba.js:1
153747782:1 Access to fetch at 'https://api.opendota.com/api/players/153747782/heroes?' from origin 'https://www.opendota.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by TableCraft0R** [comment]
Also api.opendota.com endpoints say
`// 20191121160612
// https://api.opendota.com/api/players/153747782/counts?

{
  "error": "monthly api limit exceeded"
}`
when browsing over IPv6.

IPv4 api works fine.

**Comment by howardchung** [comment]
This is the probably the IP limit. We likely don't read IPv6 addresses correctly.

**Comment by TableCraft0R** [comment]
It is probably rate limiting Cloudflare's ipv6 addresses by the looks of it. Because even if I force to change my ipv6 address I still get ratelimits. I hope for resolution so I wont have to disable my ipv6 everytime i check my stats

**Comment by howardchung** [comment]
We added a new package for determining IP on the server side. Is this still a problem?
