### ISSUE TITLE
Background brightness changes when changing tabs

### ISSUE THREAD

**Issue by Argn0** [odota/web#2298]
There is this weird bug where switching between the Benchmarks and Overview tab very slightly changes the background brightness.

https://www.opendota.com/matches/5118002212

EDIT: it's on the right side

**Environment**
- Browser Version: chromium
- OS: win 10

**Comment by howardchung** [comment]
I am not seeing this, but maybe my eyes are just bad

**Comment by Argn0** [comment]
I should have added that it's on the right side only which makes me think that it has something to do with a color gradient...

**Comment by Argn0** [comment]
I think it's the background increasing in size and the color gradient shifting around in position.

**Comment by bdbch** [comment]
I can see it too and it's for sure the background gradient. With a 180° degree background-gradient this effect won't be noticed that hard.

What is strange is, that while loading the new page content the background gets darker a lot for me. Is there something with the footer darkening the page area around it?

**Comment by Argn0** [comment]
Or maybe we could define the gradient color stops in pixels instead of percentages (which is the default).
