### ISSUE TITLE
Feedback about new color scheme

### ISSUE THREAD

**Issue by Argn0** [odota/web#2318]
Leave your feedback here

**Comment by viology** [comment]
it looks a lot like the starcraft 2 forums, also since player names are also blue, it's a little hard to read

**Comment by jjjjjjjjjjjjjjjjjjjj** [comment]
I love it :heart:

**Comment by billcuthbert** [comment]
I prefer it to the old theme

**Comment by bdbch** [comment]
I think it's better. The blurple/purple from before was okay but the blue scheme is cleaner for my preferences.

**Comment by macmillerw** [comment]
New color scheme is better!
