### ISSUE TITLE
Add last hits per minute

### ISSUE THREAD

**Issue by zbyju** [odota/web#2320]
I think it would be really nice to see how many last hits per minute each player got in the match page. Also I think it's a good stat to show on the player page in the Avg/Max bar at the top. I think a lot of mid and carry players would appreciate this feature.

Just to be clear I know there is the farm tab where you can see how many CS you got each 5 minutes, you can also look at the graphs but the think I'm talking about is one number only CS/1 minute

**Comment by howardchung** [comment]
We have the data for this, but need to figure out what the best way to display it is.

**Comment by Argn0** [comment]
I suggest as a tooltip when you hover over the last hits

**Comment by howardchung** [comment]
That might work, but would you need to show the last 5 minutes' worth in each tooltip since we only show last hits at 5 minute intervals?

**Comment by Argn0** [comment]
I just remembered we already show LHM in the Benchmarks tab. So I guess this is more about showing the overall lifetime LHM in the player overview page.

**Comment by zbyju** [comment]
So just to be clear I wanted a single number CS/minute over the span of the whole game. For example if I get 400 last hits in a game that was long 40 minutes and 30 seconds that would be 400/40.5=9.88. My suggestion is to put a tooltip when you hover over the number of CS you have in a game and this tooltip would display this number.
I think this number is pretty nice to know so maybe it would be nice to have it in the profile page in the top bar (Averages/Maximums)?

**Comment by howardchung** [comment]
As @Argn0 mentioned we do have this data for each match in e.g. https://www.opendota.com/matches/5114541347/benchmarks.

However, we don't average it across different matches.
