### ISSUE TITLE
Vision map uses outdated image 

### ISSUE THREAD

**Issue by lightblue0** [odota/web#2324]
Vision tab for parsed matches uses an old map. 
![image](https://user-images.githubusercontent.com/22945007/70669730-307c6000-1c45-11ea-969e-1eaecea5b1c5.png)

**Comment by howardchung** [comment]
I think we have code to choose the map based on timestamp, but we need a png of the latest map and update to add it to the code.

**Comment by lightblue0** [comment]
![image](https://user-images.githubusercontent.com/22945007/70677639-bad0be00-1c5d-11ea-9cee-35f3b1bc03ea.png)

Image found @ https://dota2.gamepedia.com/File:Minimap_7.23.png
