### ISSUE TITLE
More informative home page

### ISSUE THREAD

**Issue by blukai** [odota/web#237]
Do it when all from the current ui will be ready in new maybe with some improvements

![- -1](https://cloud.githubusercontent.com/assets/20866892/19109929/3635e0c2-8b00-11e6-8d5a-c2180febbf40.jpg)

**Comment by howardchung** [comment]
did we have ideas for what we could put in the image slots?

**Comment by howardchung** [comment]
I don't think we'll be doing this, although if someone wants to revamp the homepage that would be interesting!
