### ISSUE TITLE
White gap under the footer after settings dropdown being open

### ISSUE THREAD

**Issue by 102** [odota/web#2386]
**Current Behavior**
When I open settings dropdown in header (screenshot in details), and close it after that, I can see the white gap below the footer (screenshot is attached as well).

**Expected behavior/code**
The gap should not appear

**Console Output**
There's no output in console

**Environment**
- Browser Version: Chrome Version 79.0.3945.88 (Official Build) (64-bit)
- OS: Windows 10

**Possible Solution**
I have no solution for the moment

**Additional context/Screenshots**
<details>
<summary>Related screenshots</summary>

Header options button:
![image](https://user-images.githubusercontent.com/5839225/71503636-42464000-28a0-11ea-83ae-52a7008e4dc3.png)

The gap:
![image](https://user-images.githubusercontent.com/5839225/71503669-6e61c100-28a0-11ea-996d-eca3e4d53fa1.png)
</details>

**Comment by Argn0** [comment]
nice catch. I was wondering what was causing this.

**Comment by ahi-el** [comment]
I was in the middle of debugging this when it suddenly disappeared, and now I can't get it to reproduce. So, uh...odd.

**Comment by wanderrful** [comment]
I'm also not able to reproduce this on local or in production

**Comment by 102** [comment]
I still can reproduce this on production (haven't tried on local), on seemingly any page (tested player page, teams page, index page)

**Comment by bdbch** [comment]
I was able to reproduce this bug in production. It seems to be related to the body element and I think something is broken with it anyway. Seems to be the css-reset setting `display` to `initial`.

I quickly played around in the inspector to try out if `display: block` fixes it and it seems to do the trick.

Anyway I think the body element is broken anyway as in the inspector it doesn't really show up in the box model but still has it's correct height and width defined on it.

I'll take a look at this as soon as I have time (tomorrow morning).

**Comment by bdbch** [comment]
started working on this on 2386-fix-white-offset
