### ISSUE TITLE
Talent levelling tooltips not showing values

### ISSUE THREAD

**Issue by dpatterbee** [odota/web#2406]
**Current Behavior**
In the Ability Builds section of the match overview page, hovering over levelled abilities and talents shows a tooltip describing the ability or talent. However, for talents, any values associated with the chosen talent show only as {s:value}. 

![image](https://user-images.githubusercontent.com/19880509/72453149-8a2cf880-37b6-11ea-8b97-15ddb7e31591.png)

**Expected behavior/code**
I would expect numbers

**Possible Solution**
This appears to be due to an update to the [dotaconstants](https://github.com/odota/dotaconstants) database, where a commit on 3rd october removed all the values. Probably as a result of actual changes in the game files. I can't think of an actual solution that updates with game updates as I'm not familiar with the game files and dotaconstants seems to get them from the [d2vpk](https://github.com/dotabuff/d2vpkr) repository from dotabuff.

**Comment by howardchung** [comment]
Yep this is tracked by https://github.com/odota/dotaconstants/issues/73#issuecomment-561684877

The files changed and we haven't had a chance to fix it yet. Help is appreciated!
