### ISSUE TITLE
n is null

### ISSUE THREAD

**Issue by Turmfalke2** [odota/web#2418]
hi,
n is null.
https://www.opendota.com/matches/1450741943

![screen02](https://user-images.githubusercontent.com/5174562/73205838-0d006c80-4142-11ea-9e86-e19be2a1b42a.png)

and the page/match data fails to load.

**Comment by ahi-el** [comment]
interesting, it only happens for that specific match

the error occurs in MatchGraph.jsx
```
const generateDiffData = (match) => {
  const radiantGoldAdv = match.radiant_gold_adv;
  const radiantXpAdv = match.radiant_xp_adv;
  const data = [];
  radiantXpAdv.forEach((rXpAdv, index) => {
    if (index <= Math.floor(match.duration / 60)) {
      data.push({ time: index, rXpAdv, rGoldAdv: radiantGoldAdv[index] });
    }
  });
  return data;
};
```
match.radiant_gold_adv and match.radiant_xp_adv are both null, thought everything else seems to be fine.

**Comment by howardchung** [comment]
I think we should just check the fields. This is a really old match and it's probably just because the parser didn't output those fields at that time.
