### ISSUE TITLE
Update the explanation of MMR page

### ISSUE THREAD

**Issue by 102** [odota/web#2450]
**Is your feature request related to a problem? Please describe.**
It doesn't seem that this page has any data since MMR is private. It still can be useful for someone who added data back in the time, so it makes sense to keep this page as is. However, I think it would be helpful to add a note about this to the page

**Describe the solution you'd like**
Currently, there's a link to the blog post on how to make the MMR data public: https://blog.opendota.com/2016/01/13/opendota-mmr-and-you/ (it was created back in the 2016 and suggested solution does not work anymore), so it probably makes sense either to:

1. add a new blog post and link on this page
1. update the existing blog post
1. add a plain text note on the page itself

**Describe alternatives you've considered**
It may be left as is

Example page: https://www.opendota.com/players/385676285/mmr

@howardchung what do you think?

**Comment by howardchung** [comment]
I believe we want to keep it around for those players who do have MMR history from a long time ago.

**Comment by 102** [comment]
I have updated the description of the issue, so it now does not suggest to remove the page completely

**Comment by howardchung** [comment]
Sure, we can update the existing post:
https://github.com/odota/blog/blob/master/_posts/2016-01-13-opendota-mmr-and-you.md

**Comment by Zeroks77** [comment]
@102 
you still can track your MMR -> the DotaPlus from Overwolve is pretty accurate...

So this site can maybe still get a use ?

**Comment by 102** [comment]
> @102
> you still can track your MMR -> the DotaPlus from Overwolve is pretty accurate...
> 
> So this site can maybe still get a use ?

it looks like a standalone app, how this could be helpful for this page?

**Comment by Argn0** [comment]
I think it's still possible to display the MMR on your profile by setting it up in an older client which can be downloaded through a little trickery.
