### ISSUE TITLE
Why column 'team_id' of 'bigint' type in table 'teams' sometimes return string values?

### ISSUE THREAD

**Issue by godzilla65536** [odota/web#2453]
**Current Behavior**
~~~sql 
select 
  column_name, 
  data_type, 
  character_maximum_length 
from 
  INFORMATION_SCHEMA.COLUMNS 
where 
  table_name = 'teams';
~~~
![image](https://user-images.githubusercontent.com/35817040/74782409-717f9900-52b4-11ea-93ce-4713dd038cbe.png)

And after query
~~~sql
SELECT 
  * 
from 
  teams 
where 
  LOWER(teams.name) like LOWER('%mode%')
~~~
we will get it
![image](https://user-images.githubusercontent.com/35817040/74782998-b1934b80-52b5-11ea-9f6e-6fc5ac632c45.png)

**Comment by howardchung** [comment]
The data is correct in the database, this is a display bug.

https://github.com/odota/web/blob/master/src/components/Explorer/ExplorerOutputSection.jsx#L115

The display attempts to translate IDs to team names to be more user-friendly, but this is probably confusing behavior. We should probably add it as a tooltip or something so people who want the ID value can still see it.

if you export the data as CSV/JSON it should still be an ID value.
