### ISSUE TITLE
NULL values in table 'matches'

### ISSUE THREAD

**Issue by godzilla65536** [odota/web#2454]
**Explain your question as detailed as possible**

Hello. Why columns 'radiant_team_name' and 'dire_team_name' in table 'matches' contain only NULL values?

~~~sql
SELECT
    radiant_team_name,
    dire_team_name
FROM matches
WHERE
    radiant_team_name IS NOT NULL OR
    dire_team_name IS NOT NULL
~~~

![image](https://user-images.githubusercontent.com/35817040/74839062-b3045880-5335-11ea-9487-7488deebca75.png)

These columns are useless

**Comment by howardchung** [comment]
I believe these columns used to be populated but were later replaced with a dedicated teams table. We just never got around to deleting the extra columns
