### ISSUE TITLE
Tell me why it does not work

### ISSUE THREAD

**Issue by godzilla65536** [odota/web#2456]
**Explain your question as detailed as possible**

~~~sql
with t as (SELECT objectives from matches where match_id = 5250819171)

SELECT
    value -> 'type'
FROM
    t,
    json_array_elements(objectives)
~~~

I hope to receive such data

![image](https://user-images.githubusercontent.com/35817040/74878013-840ed680-5377-11ea-9d77-d7e1261ec284.png)

**BUT!**

![image](https://user-images.githubusercontent.com/35817040/74878074-a30d6880-5377-11ea-9dab-821e9ddffcb6.png)

Maybe you will give a hint what am I doing wrong?  (:

**Comment by howardchung** [comment]
this is of type json[] so I think you have to operate on each element in the column

**Comment by godzilla65536** [comment]
The problem was that the database returned JSON as text. So I manually converted it to JSON using "to_json()" function

~~~sql
with t as (SELECT objectives from matches where match_id = 5250819171)

SELECT
    value -> 'type'
FROM
    t,
    json_array_elements(to_json(objectives))
~~~
