### ISSUE TITLE
Trident image being used instead of Kaya

### ISSUE THREAD

**Issue by MLPaladin888** [odota/web#2458]
**Current Behavior**
The image being displayed for the Kaya, in places like the the Overview or the Items sections of a match, is actually the image for the Trident.  The pop-up/tool-tip shows the correct image, but the image in the charts themselves are incorrect.

**Expected behavior/code**
When Kaya is built, it should show the the proper image for Kaya, not Trident.

**Console Output**
N/A

**Environment**
- Browser Version: Microsoft Edge Version 80.0.361.57 (Official build) (64-bit)
- OS: Microsoft Windows 10 Version 1909 (OS Build 18363.592)

**Possible Solution**

**Additional context/Screenshots**
See the following match:
https://www.opendota.com/matches/5252722580/overview
Bane has a Kaya, but it shows the image of a Trident.  If you hover over the Trident, the tool tip correctly shows Kaya

**Comment by howardchung** [comment]
@Argn0 I forgot why we mapped kaya to trident. Probably a missing image file somewhere:
https://github.com/odota/web/commit/d540dde9ed1f15662ed2b98c6403224388db5043

**Comment by Argn0** [comment]
yes the files were missing

**Comment by Argn0** [comment]
or had unexpected names
