### ISSUE TITLE
Ability Build table - hero has 'autoattack' icon instead of talent

### ISSUE THREAD

**Issue by ahi-el** [odota/web#2459]
**Current Behavior**
https://www.opendota.com/matches/5252722580/overview Chen has a level 20 talent of 'Auto Attack/Other' instead of the actual talent. I'm guessing this is some kind of a 'default' icon when it can't find the correct talent?

**Expected behavior/code**
The correct talent

![image](https://user-images.githubusercontent.com/37062459/75048617-70778300-54d1-11ea-9fa4-22f930f84987.png)

**Comment by howardchung** [comment]
I ran a dotaconstants update and this seems to be fixed
