### ISSUE TITLE
separate benchmarks for turbo

### ISSUE THREAD

**Issue by argv1** [odota/web#2475]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]
If I currently take a look at the benchmarks, even bad player in a turbo match perform better than average.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.
So I would suggest that benchmarking of turbo matches should be separated from the other matches

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by howardchung** [comment]
We currently store the benchmarks in redis zsets based on "normal" game types. So to achieve this, we would need to store a separate set of data for turbo games only. We could do this if there's sufficient interest/motivation in benchmarks for turbo games.

**Comment by howardchung** [comment]
Implemented in https://github.com/odota/core/commit/660eeed11984a1f45c234e856ee89aadcd4f7f90
