### ISSUE TITLE
total wins and losses (including turbo)

### ISSUE THREAD

**Issue by argv1** [odota/web#2476]
**Current Behavior**
A clear and concise description of the behavior.
If I take a look at any profile, I see wins, losses and a win rate, but always without all the turbo matches. Take for example https://www.opendota.com/players/7841909/matches
He played 22 non turbo matches and 53 turbo matches.

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).
If I use the api request (https://api.opendota.com/api/players/7841909/matches), I only get the non turbo matches
It would be great if the win, losses and win rate would include all matches and also the API request would provide all matches

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.
Just compare the matches listes under https://www.opendota.com/players/7841909/matches and 
https://api.opendota.com/api/players/7841909/matches

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]
does not make a difference

**Possible Solution**

at least a modification of the API, better a change of the profile frontpage content

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by howardchung** [comment]
To do this you add the significant=0 parameter to the API call.

This is sort of documented, but not sure how to surface it better.

**Comment by bdbch** [comment]
Should we create a ticket for the API including a better documentation for this endpoint?

**Comment by howardchung** [comment]
Sure
