### ISSUE TITLE
Hero item suggestions

### ISSUE THREAD

**Issue by ccyccyccy** [odota/web#2478]
**Is your feature request related to a problem? Please describe.**
I want to know what items to buy on a hero, i.e. what items to buy at the start of the game, early game, mid game and late game.

**Describe the solution you'd like**
A new tab with generated item suggestions from past 100 professional matches, split into "Start of Game", "Early Game", "Mid Game" and "End Game" item category, with some sort of heuristic to determine an item's category.
![image](https://user-images.githubusercontent.com/32454748/76541689-e82c4280-64be-11ea-951f-dc2ebd88fe95.png)

**Describe alternatives you've considered**
I guess you can simply list down popularity of each items at the end of all matches.

I can help to implement it, but I need some suggestions for it's feasibility and difficulty.

**Comment by howardchung** [comment]
This data is from SQL so both approaches are possible.

You'd probably do the aggregation using JavaScript and implement a new endpoint for this in odota/core.

**Comment by howardchung** [comment]
Looks like this data was added to core, but the UI was never implemented?

**Comment by lhazuca** [comment]
Hi! I would like to give this one a try. Can someone assign it to me?

**Comment by howardchung** [comment]
Done!

**Comment by talal-najam** [comment]
Hi @lhazuca, just wanted to check if you're still working on this? thanks

**Comment by lhazuca** [comment]
Hi @talal-najam , yes i've been working in something. I'll probably make a PR in a few days. I was trying something like this:
![image](https://user-images.githubusercontent.com/21280252/124480595-cde63a00-dd7d-11eb-86a2-e145abbe6e41.png)
I need to order the items, i'm not showing the item count on each one but i can give it a try.

**Comment by talal-najam** [comment]
Looking good! I'm actually not sure if it's ideal to show the number now 😄, without that it looks great too! A few thoughts:

- I feel ordering would be nice to prioritize e.g. so a sentry ward doesn't come first and a quelling blade as last
- I'm thinking whether we could see e.g. if more people are buying blink in mid game (91) than early game (3), we could then maybe put it only under the category where it's bought more frequently i.e. mid game?
- The late game item shows 2 Aghs, the other is Aghs blessing. I'm not sure if anything can be done to indicate that

**Comment by lhazuca** [comment]
Hi @talal-najam i could order the items. But i'm having trouble running the tests. When i try to run `npm test` i get this error:
```
Error: Command failed: serve -s build
/bin/sh: 1: serve: not found

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:486:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at Pipe.<anonymous> (net.js:673:12)
    at Pipe.callbackTrampoline (internal/async_hooks.js:129:14)
```

**Comment by howardchung** [comment]
Did you npm install? But also you don't have to test locally, the CI should do it

**Comment by lhazuca** [comment]
I did run npm install. I think it's looking for the `serve` command which i don't have (maybe something i need to install globally?). But it's okey I'll just let the CI do it. Thanks
