### ISSUE TITLE
broom handle does font color.

### ISSUE THREAD

**Issue by Turmfalke2** [odota/web#2507]
hi,
![screen02](https://user-images.githubusercontent.com/5174562/78509720-80e97180-7790-11ea-98e7-dc82a8ce429e.png)

**Comment by howardchung** [comment]
We can regex these out in the dotaconstants code (parsing HTML with regex?!)

**Comment by bdbch** [comment]
@Turmfalke2 do you have a link to a game with a Broom Handle in it?

**Comment by Turmfalke2** [comment]
@bdbch https://www.opendota.com/matches/5336834691

**Comment by bdbch** [comment]
Thanks, I'll check this out today

**Comment by bdbch** [comment]
@howardchung I exported a regex for that called HTML_REGEX from the utility file in #2517

**Comment by bdbch** [comment]
@howardchung I added a PR to dotaconstants to fix this issue
