### ISSUE TITLE
tome of knowledge customval_team_used not interpolated.

### ISSUE THREAD

**Issue by Turmfalke2** [odota/web#2508]
hi,
![screen03](https://user-images.githubusercontent.com/5174562/78509770-cb6aee00-7790-11ea-86e5-afe1cec893e7.png)

**Comment by howardchung** [comment]
We wouldn't have real data for this since it's different for each match and not intrinsic to the item.

Should probably just regex it out in:
https://github.com/odota/dotaconstants/blob/37aa096d59897a062fe37482c87ad98ed82a7bf9/tasks/updateconstants.js#L45

**Comment by Turmfalke2** [comment]
duplicates #2256
