### ISSUE TITLE
iron talon abilitycastrange not interpolated.

### ISSUE THREAD

**Issue by Turmfalke2** [odota/web#2509]
hi,
![screen04](https://user-images.githubusercontent.com/5174562/78509804-11c04d00-7791-11ea-839b-9eb16980081d.png)

**Comment by howardchung** [comment]
Code for that is here:
https://github.com/odota/dotaconstants/blob/37aa096d59897a062fe37482c87ad98ed82a7bf9/tasks/updateconstants.js#L67

We'll need to investigate what's different about this item

**Comment by ZoraizQ** [comment]
This issue was fixed from odota/dotaconstants
