### ISSUE TITLE
How to map the (x,y)coordinates to dota2 map/minimap

### ISSUE THREAD

**Issue by leafstar** [odota/web#2521]

**Comment by howardchung** [comment]
I believe you subtract 64 from both the x and y values, and then those are positions from the left bottom corner.

**Comment by leafstar** [comment]
and where can I find the mini map that I can put my (x,y) values on accurately. I use the map from opendota site, but it seems not fit... I have to manually adjust the size etc..

**Comment by howardchung** [comment]
That depends on how large you've scaled the image. I believe the min/max in each dimension is 64/192, so use that to scale the coordinates
