### ISSUE TITLE
404 for polar_furbolg_ursa_warrior_thunder_clap_md.png

### ISSUE THREAD

**Issue by Turmfalke2** [odota/web#2522]
hi,
![screen02](https://user-images.githubusercontent.com/5174562/79020356-e6ff3b80-7b78-11ea-866f-75f611d2a522.png)

**Comment by howardchung** [comment]
We do have a collection of neutral images here:
https://github.com/odota/web/tree/master/public/assets/images/dota2/neutral_abilities

We can either make the odota-core proxy point to these images, or change the code in dotaconstants to use this alternate address
