### ISSUE TITLE
404 for lycan_summon_wolves_critical_strike_sm.png and lycan_summon_wolves_critical_strike_md.png

### ISSUE THREAD

**Issue by Turmfalke2** [odota/web#2523]
hi,
![screen03](https://user-images.githubusercontent.com/5174562/79020457-2594f600-7b79-11ea-81d8-ccde6e5059ba.png)

**Comment by howardchung** [comment]
Note that this is just a https pass-through to cdn.dota2.com

We do have the ability to upload our own images and override this behavior.
