### ISSUE TITLE
Consider Removing Removed Ranks from Rank Tier Distribution 

### ISSUE THREAD

**Issue by MaksymKarunos** [odota/web#2524]
I have seen the previous question regarding rank distribution before. At that point, matchmaking update just came out and the curve did not look that bad. Now a few players who probably did not calibrate since the last season make the perfect normal distribution of ranks look a bit ugly.
![Capture](https://user-images.githubusercontent.com/42012902/79035489-3a7b8480-7b8d-11ea-839e-4a83997bcdfe.PNG)
If you want me to fix it, I can do it over the weekend.

What do you think?

**Comment by howardchung** [comment]
The next reset should be coming soon, since it looks like the last one was in October.

https://github.com/odota/web/issues/2229

**Comment by howardchung** [comment]
I ended up just doing this manually
