### ISSUE TITLE
Problem with Hero Damage and Hero Growth

### ISSUE THREAD

**Issue by zerols** [odota/web#2529]
**Explain your question as detailed as possible**

As the level of the hero grows, to which level of damage will exceed the previous increase, or there will be a relatively big change in control, whether there are certain characteristics of the hero that reaches a certain level at a specific time, all occur Qualitative change

---

If you have a support request or question please also check our Discord Server: https://discord.gg/opendota

**Comment by howardchung** [comment]
I'm sorry, but I'm having a hard time understanding the question. Could you phrase it differently?

**Comment by bdbch** [comment]
I updated the title and put the actual question into the description even though I don't understand the question myself. @zerols could you please rephrase your question? Do you want to see the relative character growth per level/item?

**Comment by zerols** [comment]
The strength period of each hero is different. Reaching the corresponding level at the right time, and the corresponding equipment, to a certain extent, this game has a great chance of winning.
On each hero's page, is it possible to count the relationship between level, time, equipment, and win rate.
This one was translated through Google, maybe some places are not very clear, sorry.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dominik"<notifications@github.com&gt;; 
发送时间: 2020年4月15日(星期三) 晚上9:52
收件人: "odota/web"<web@noreply.github.com&gt;; 
抄送: "1989017988"<1989017988@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [odota/web] Problem with Hero Damage and Hero Growth (#2529)



I updated the title and put the actual question into the description even though I don't understand the question myself. @zerols could you please rephrase your question? Do you want to see the relative character growth per level/item?

**Comment by bdbch** [comment]
I think I understand and no problem. Language barriers can be tough. :)

As far as I understand you want to see what items at what level were used the most when winning with a certain hero? @howardchung do you think this is possible with the data we have or is this not being tracked?

**Comment by zerols** [comment]
like on this photo ， i hope x change time ， y change the&nbsp;possibility of win ，&nbsp; and the three lines represent changes in level over time, changes in equipment over time, and changes in damage over time.&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dominik"<notifications@github.com&gt;; 
发送时间: 2020年4月16日(星期四) 下午3:55
收件人: "odota/web"<web@noreply.github.com&gt;; 
抄送: "1989017988"<1989017988@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [odota/web] Problem with Hero Damage and Hero Growth (#2529)



I think I understand and no problem. Language barriers can be tough. :)
 As far as I understand you want to see what items at what level were used the most when winning with a certain hero? @howardchung do you think this is possible with the data we have or is this not being tracked?

**Comment by bdbch** [comment]
I think sending a photo is not supported by answering this via email. Could you attach it again directly on Github?

**Comment by howardchung** [comment]
We do this somewhat on the scenarios page:
https://www.opendota.com/scenarios/itemTimings?hero_id=1&item=bfury
