### ISSUE TITLE
Roshan gold and Other gold in gold sources are mixed up

### ISSUE THREAD

**Issue by SeraphicGreevil** [odota/web#2530]
https://www.opendota.com/matches/5360333943/farm

Please, observe Roshan and Other gold distribution. All the heroes, have 600 Other gold, which is exactly the amount of starting gold. No time-based income is present. Radiant never killed Roshan, only Dire did once. However, Roshan gold is present on all the heroes. Moreover, some heroes have really strange amounts, like WK with 5479 or Juggernaut with 7560.

**Comment by howardchung** [comment]
It's likely that Valve has changed the enums so that what used to be Roshan gold is now something else. We could take a look at the gold events and see if we spot any patterns

**Comment by howardchung** [comment]
Here's a text version of the parse output. Looks like gold reason 14 corresponds to any neutral (may or may not include roshan). I can update the label.

[parse.zip](https://github.com/odota/web/files/4490210/parse.zip)

**Comment by howardchung** [comment]
Seems like Roshan is now 15
Courier is now 16
Rune is 17
Ward is 20

Unsure if 18 and 19 exist, if they do they're not in this match.
