### ISSUE TITLE
swap img links to use akamai CDN

### ISSUE THREAD

**Issue by howardchung** [odota/web#2535]
We previously proxied all image requests through api.opendota.com since cdn.dota2.com has an invalid HTTPS cert. However we've just found that there is an Akamai CDN endpoint for images: https://steamcdn-a.akamaihd.net/apps/dota2/images/items/ward_dispenser_lg.png?t=1587186172645

Places where we currently use images:
https://github.com/odota/web/blob/b25adb9c861dbd03206aec1eb831f68a7f793a52/src/components/Match/Vision/VisionFilter.jsx
https://github.com/odota/web/blob/759ca92c62c83396acb3753af93f0b670d8b1bc6/src/components/Match/matchColumns.jsx
https://github.com/odota/web/blob/8509a2e5208c83dcc25f95823085ad75a199f971/src/components/Hero/Matchups.jsx
https://github.com/odota/web/blob/8509a2e5208c83dcc25f95823085ad75a199f971/src/components/Match/PlayerThumb/index.jsx
https://github.com/odota/web/blob/1e0586a2f1100ac5978e4b6994ca2f803e338cc1/src/components/Hero/Ability.jsx
https://github.com/odota/web/blob/cc4a6c56c6c87324a71845956fdba09c4c3a1ac3/src/components/Visualizations/inflictorWithValue.jsx
https://github.com/odota/web/blob/e7db47f37d1d07af7e43bb3852b3a29f5d0d52c5/src/components/Match/BuildingMap/BuildingMap.jsx
https://github.com/odota/web/blob/8509a2e5208c83dcc25f95823085ad75a199f971/src/components/Hero/Header.jsx
https://github.com/odota/web/blob/6c0685c384eb6dc845c688543429a317e1aad518/src/components/Match/Vision/VisionLog.jsx
https://github.com/odota/web/blob/d57649283287344149b1257b5ae211433bd3dbd8/src/components/Match/Draft/Draft.jsx
https://github.com/odota/web/blob/5a3dc1c24379dfd7f828009ad7dca7f91b8011e0/src/components/Match/MatchStory.jsx
https://github.com/odota/web/blob/e7db47f37d1d07af7e43bb3852b3a29f5d0d52c5/src/components/Match/TeamfightMap/index.jsx
https://github.com/odota/web/blob/8509a2e5208c83dcc25f95823085ad75a199f971/src/components/Match/Overview/Timeline.jsx
https://github.com/odota/web/blob/283fb83059aa1cfd5dfdbf0261277b85562e53d1/src/components/AbilityTooltip/index.jsx
https://github.com/odota/web/blob/8509a2e5208c83dcc25f95823085ad75a199f971/src/components/Scenarios/FormFieldData.jsx
https://github.com/odota/web/blob/e7db47f37d1d07af7e43bb3852b3a29f5d0d52c5/src/components/ItemTooltip/index.jsx
https://github.com/odota/web/blob/a39162ce874554ade7cd308a5bb7df99aa0f8de0/src/utility/index.jsx
https://github.com/odota/web/blob/631ce0f2b9816d397b208a6f74922345d5a79545/src/components/Visualizations/HeroImage.jsx

**Comment by akibrhast** [comment]
Hi, I have never contributed to github project before. So this is a first for me.
Now in regards to this issue, would this just involve changing this:
`
image: <img height="24" **src={`${process.env.REACT_APP_API_HOST}/apps/dota2/images/items/ward_observer_lg.png`}** alt="" />,
`
to this:
`
image: <img height="24" **src="https://steamcdn-a.akamaihd.net/apps/dota2/images/items/ward_observer_lg.png"** alt="" />,
`
for all the above linked places?

**Comment by howardchung** [comment]
Yes, although we'd probably want to make it a variable so we can swap it as needed.

**Comment by akibrhast** [comment]
Should that variable go under web/.env. Something along the line of
IMAGE_CDN : https://steamcdn-a.akamaihd.net

So the changes in each of the file would be 
```

const data = [
  {
    type: 'observer',
    image: <img height="24" src={`${process.env.IMAGE_CDN}/apps/dota2/images/items/ward_observer_lg.png`} alt="" />,
  }
```

**Comment by howardchung** [comment]
Yes, that sounds good. Most of the work will be validating that images exist at the new path.

**Comment by akibrhast** [comment]
If the image doesnt exist should it `alt="img not found"` or de default to using REACT_APP_API_HOST ?

**Comment by howardchung** [comment]
If you find broken images on the new host please make a note of them. We can make it fallback for now, but would be good to know which ones don't work so we can try to spot patterns.

What I mean is that we've been using the old host for years with only minor issues, so we should just check that the new host also works well.
