### ISSUE TITLE
OpenDotaAPI return null

### ISSUE THREAD

**Issue by azuredragon3000** [odota/web#2576]
when i am trying to get information from OpenDotaAPI
but its not working 
example i went to https://api.opendota.com/api/players/416359835
416359835 is player id, but API web return null 
when i checked my profile , its working.
i mean some player ids return properly , some player ids return null , do you know why ?

thank you in advance

---

If you have a support request or question please also check our Discord Server: https://discord.gg/opendota

**Comment by howardchung** [comment]
This can happen in some cases if the player hasn't logged into OpenDota and they haven't played a match with stats enabled for us to pick up the ID.

**Comment by azuredragon3000** [comment]
thank you Howardchung, so are there anyway to collect the their information even they haven't logged to OpenDota?

**Comment by howardchung** [comment]
You can try using the Steam APIs for that

**Comment by azuredragon3000** [comment]
thank you :)
