### ISSUE TITLE
Combos are not working anymore

### ISSUE THREAD

**Issue by kereyit** [odota/web#2591]
**Current Behavior**
02/06/2020 I tried to find the last match given in Battle Pass, but no results at all

**Expected behavior/code**
Find a related match

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by howardchung** [comment]
It's not clear yet whether this data is still available. Will have to see if it happens again tomorrow.

**Comment by kereyit** [comment]
> It's not clear yet whether this data is still available. Will have to see if it happens again tomorrow.

Thank you for your reply! Should i guess by myself today or it may be fixed? Cause i have a win streak bets thanks to you.

**Comment by howardchung** [comment]
I wouldn't rely on it being fixed today

**Comment by QzSG** [comment]
I tried the following sql 
```
SELECT * FROM (SELECT match_id , ARRAY_AGG(id) hero_array FROM 
(SELECT matches.match_id,matches.start_time,heroes.id FROM matches JOIN match_patch using(match_id) JOIN player_matches using(match_id) 
JOIN heroes on heroes.id = player_matches.hero_id WHERE TRUE AND matches.start_time >= extract(epoch from timestamp '2019-01-01T10:10:10.010Z') order by match_id, id asc) as custom
GROUP BY match_id) as groupedmatches
WHERE hero_array = ARRAY[5,16,21,23,26,35,40,44,56,71]
```
where ```ARRAY[5,16,21,23,26,35,40,44,56,71]``` is the list of heroes appearing in today's guess, searched all the way back to 2019 Jan with not a single match having the list of heroes.

Valve probably took a very old match or hidden/softdeleted the match data

**Comment by howardchung** [comment]
That table is pro matches only

**Comment by howardchung** [comment]
I think we can conclude that Valve is hiding the selected community match in the API. The feature still works, just not for that match.
