### ISSUE TITLE
Some hero images don't load

### ISSUE THREAD

**Issue by prashantdwivedi** [odota/web#2595]
Please fix that issue match not find and some of the hero missing on during select

**Comment by howardchung** [comment]
Weird issue where some of the hero images aren't loaded. In the Combos UI this also means they're not pickable as there's no width to that element. Should probably put a width on it.

**Comment by prashantdwivedi** [comment]
try to pick necro it not show. see image

![image](https://user-images.githubusercontent.com/6306052/83612935-b51abc00-a5a0-11ea-80a0-904fc45461e3.png)

**Comment by matrix945** [comment]
It seems just UI problem. URL query is working. This is 03.06 combos
[https://www.opendota.com/combos?teamA=114&teamA=84&teamA=22&teamA=90&teamA=16&&queryType=public](url)
Unfortunately, still no correct matches.
