### ISSUE TITLE
Battle Pass 2020 Combos search Still Not Working and Can't Even see heroes

### ISSUE THREAD

**Issue by juncombo** [odota/web#2597]
**Current Behavior**
Cannot see any hero pic , all names of heroes are on top of each other. Also cannot see any hero pic in team A and B box. Last thing the search always return empty results

**Environment**
- Chrome
- Windows 10

**Additional context/Screenshots**

![Screenshot_1](https://user-images.githubusercontent.com/31518503/83637087-739a0900-a5c0-11ea-8335-ece9776f0808.png)

**Comment by howardchung** [comment]
duplicates of #2595 and #2591
