### ISSUE TITLE
findMatches API can't fetch latest matches

### ISSUE THREAD

**Issue by wangrunxinyes** [odota/web#2615]
API: https://api.opendota.com/api/findMatches

For example, I can only get the newest matches on 6/18 when using this api on 6/23.
Looks like there is a 5 days gap for searching latest games and no document mentions that.

**Comment by howardchung** [comment]
This is probably a bug. I'll take a look

**Comment by howardchung** [comment]
OK, so it seems that the issue is that the returned results aren't necessarily in order of most-recent first. So if you get back results, they'll just be the first 5 results found that match the criteria.

**Comment by wangrunxinyes** [comment]
Thanks. So is there any change to add a sort by datetime desc?

**Comment by howardchung** [comment]
Unfortunately it's not that simple as the index is unsorted and might have a performance impact to get the results then sort.
