### ISSUE TITLE
Match history seems to be outdated

### ISSUE THREAD

**Issue by SeraphicGreevil** [odota/web#2617]
Seems that at some point of time match history is no longer retrieved from Dota API.
[OpenDota profile](https://www.opendota.com/players/70557514)
Compare to dotabuff, who seems to have no such issues:
[Dotabuff profile](https://www.dotabuff.com/players/70557514/matches)
Note, that at the moment there are 4 games not listed, all being turbo - 2 Warlock games, Grimstroke and Faceless Void.
I also briefly checked match history for pro games, which seems to be fine, and match history for public games: [High MMR highlights](https://www.opendota.com/matches/highMmr). There all the top matches are marked as 2 days ago.

**Comment by howardchung** [comment]
There seems to be around a 6-hour delay at this point on new matches but it's catching up.
