### ISSUE TITLE
"Combos" does not show recent Public Matches

### ISSUE THREAD

**Issue by JinNada** [odota/web#2633]
When using the hero combos feature, only five public matches from June 29 that fit the criteria are displayed.   The Pro Matches version still seems to be working as intended.

Browser Version: Chrome 84.0, Edge 84.0
OS: Windows 10

**Comment by JinNada** [comment]
Additional information: I was only filtering by one or two heroes.  If filtering by 3 on one team, the date changes to May 10 but otherwise acts the same.

The feature seems to work as intended when there are at least 6 heroes in the query.

**Comment by howardchung** [comment]
Probably the same issue as https://github.com/odota/web/issues/2615

The returned results aren't returned in order of time so you just get back the first 5 matches

**Comment by howardchung** [comment]
I made a change that should fix this
