### ISSUE TITLE
Medal in profile not updating after 2 weeks.

### ISSUE THREAD

**Issue by Fropsyh** [odota/web#2645]
Rank jumped from Ancient 5 > Divine 1, 2 weeks ago, and my opendota profile still hasn't updated the medal even though I have public match data turned on and all of my recent games are visible.

https://www.opendota.com/players/288310304
pls fix

https://imgur.com/a/Ji3EwsQ

**Comment by howardchung** [comment]
I believe you have a play a ranked match to get it to update.

**Comment by Fropsyh** [comment]
> I believe you have to play a ranked match to get it to update.

Alright thanks, will try, maybe.
