### ISSUE TITLE
Profile name/picture not updating with Steam profile name/picture

### ISSUE THREAD

**Issue by Crossfiyah89** [odota/web#2651]
**Current Behavior**
After I updated my profile picture/steam name, my opendota profile did not update.
https://www.opendota.com/players/83853375

**Expected behavior/code**
Profile name/avatar should have updated to match https://steamcommunity.com/id/crossfiyah/

**Console Output**
n/a

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by howardchung** [comment]
You can force a refresh by logging out and back in, but otherwise it's a random update that might happen at any time
