### ISSUE TITLE
Add a bright magnifying glass symbol to the heroes filter input field on the combos page

### ISSUE THREAD

**Issue by Argn0** [odota/web#2653]
People had reported that they missed the filter functionality.

**Comment by MaksymKarunos** [comment]
Working on it.

**Comment by MaksymKarunos** [comment]
Made a pull request

**Comment by divyavit** [comment]
Hey, I am up for this task. Is it already done or can I make a contribution? Please let me know.

**Comment by howardchung** [comment]
https://github.com/odota/web/pull/2657/files is in progress but not merged yet. You could maybe take it over

**Comment by divyavit** [comment]
Okay sure thanks

**Comment by MaksymKarunos** [comment]
Sorry guys I was inactive for a while, you are more than welcome to take over @divyavit

**Comment by dhanush1909** [comment]
created a PR #2673
