### ISSUE TITLE
Turbo mode button

### ISSUE THREAD

**Issue by howardchung** [odota/web#2663]
Add a button to player profiles that makes all player stats API requests send the turbo parameters (significant=0 and game_mode=23). Click to toggle on/off.

Store it in localStorage so it's persistent.

I only play turbo now, so this would be nice.

**Comment by ohnickmoy** [comment]
Hey @howardchung. I'm interested in contributing, but I'm also new to open source and I'm not sure if this akin to a good-first-issue.

**Comment by howardchung** [comment]
You can give it a shot, I don't think it's overly complicated. I'm available to answer questions if you've got them.

**Comment by bdbch** [comment]
I started to work on this on the branch `turbomode-stats`, see here:
https://github.com/odota/web/tree/turbomode-stats

**Comment by bdbch** [comment]
@howardchung do you only want matches to be filtered by turbomode? Or do you also want to update your profile stats? If so - does the query for stats allow the game_mode differentiation?

**Comment by howardchung** [comment]
I think we should be able to pass through the turbo params to all the /players endpoints

**Comment by bdbch** [comment]
Alright, I'll see if I can easily get this into all requests.

Just a question - for the overview we already have the filter for gamemode. I guess this should overwrite the global toggle?

**Comment by bdbch** [comment]
@howardchung I got it but it seems the recentMatches query ignores the gamemode param.
Could you maybe check my PR? I can't find out why the stats/summary is not updated in combination with the game_mode.
