### ISSUE TITLE
The unix time provided seems to be innaccurate

### ISSUE THREAD

**Issue by gheoneaemil** [odota/web#2684]
Hello,

If I request : [https://api.opendota.com/api/live](url) , the `activate_time` ( for example ) provides innaccurate ( e.g : 3 numbers are missing ).

For example , the first `activate_time` I see on my received response is `1603609856` where `new Date(1603609856)` is `Mon Jan 19 1970 15:26:49 GMT+0200`

Is there a fix for this ?

Thank you !!

**Comment by howardchung** [comment]
if you're using JS you have to multiply by 1000

**Comment by gheoneaemil** [comment]
You are right , I don't know why but for some reason I thought if I multiply by 1000 I'll lose the date accuracy. It seems it's not the case and I was wrong.

Thank you very much !!
