### ISSUE TITLE
turbo toggle missing label/looks weird on mobile

### ISSUE THREAD

**Issue by howardchung** [odota/web#2694]
Visit a player profile on mobile, toggle looks off. Likely need to fix some css

**Comment by Shaka-n** [comment]
Hey @howardchung, is anyone working on this? Because if not, I'm interested in picking this up.

**Comment by howardchung** [comment]
It's all yours if you want it!

**Comment by Edu93Jer** [comment]
@howardchung Hi there, dude Im new to the project, could you give me like more context about the issue, so I can take a look at it in the code
