### ISSUE TITLE
Matches not available

### ISSUE THREAD

**Issue by n00berator** [odota/web#2717]
**Current Behavior**
Matches not being shown.
Matches not searchable.
https://www.opendota.com/players/124406808
Not showing: 5752158372

**Expected behavior/code**
Matches should be shown automatically
Matches should be searchable.

**Console Output**
N/A

**Environment**
- Browser Version: Firefox 84
- OS: Windows 10

**Possible Solution**
Unsure.

**Additional context/Screenshots**
N/A

**Comment by howardchung** [comment]
https://www.opendota.com/matches/5704205107 appears to work
https://www.opendota.com/matches/5752158372 does not, but sometimes the Steam API misses matches initially. You can request it manually using the request page, or we have a backfill process that should eventually pick it up
