### ISSUE TITLE
Wrong (team) recording of courier death

### ISSUE THREAD

**Issue by wrtiap** [odota/web#2723]
**Current Behavior**
Radiant courier was killed before the 0:00 mark. Opendota reports Dire courier died.

**Expected behavior/code**
Report the correct team courier death.

**Additional context/Screenshots**
Example is match ID 5767993393. In "story" and "log" it states Dire courier died at -0:13. In "graphs" it can be seen that the Dire team has 25 extra gold per player at 0:00, and that Axe (Dire) has 1 last hit then for the courier.

**Comment by builder-247** [comment]
Closed via https://github.com/odota/web/commit/00e10a143be59c24319674d6d03f9aff86cbc4eb
