### ISSUE TITLE
replay server does not exist.

### ISSUE THREAD

**Issue by Turmfalke2** [odota/web#2735]
hi,
https://www.opendota.com/matches/5821139220 can't be parsed/downloaded. The download replay button links to http://replay273.valve.net/570/5820859623_1172064913.dem.bz2 , however there is no such replay server.

```

$ dig replay273.valve.net

; <<>> DiG 9.16.11 <<>> replay273.valve.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 55990
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
```

How is the correct replay server determined?

**Comment by howardchung** [comment]
It's the "cluster" field of the match data. Not sure why it's failing here, does it work in client?

**Comment by Turmfalke2** [comment]
Just tested and no I can't. I guess that firmly puts it into valve problem category, now if only they had a proper way to report issues like that.
