### ISSUE TITLE
Matches stopped being parsed

### ISSUE THREAD

**Issue by BoraxKid** [odota/web#2736]
**Current Behavior**
My matches haven't been parsed since February 6 (except one).

**Expected behavior/code**
All matches should be parsed not long after they've ended.

**Console Output**
No console output.

**Environment**
- Browser Version: Version 88.0.4324.146 (Official Build) (64-bit)
- OS: Windows 10

**Possible Solution**

**Additional context/Screenshots**
My profile: https://www.opendota.com/players/29176648
When I try to download the replay from match page, I get "This site can’t be reached" error.

**Comment by Turmfalke2** [comment]
Same issue as #2735. I have tried reaching out to valve, but so far to no avail.

**Comment by howardchung** [comment]
Auto-parsing is now a subscriber feature. There are also some unrelated issues with some replays not existing
