### ISSUE TITLE
table `matches` doesn't contain leagueid for amateur leagues

### ISSUE THREAD

**Issue by DerMaddi** [odota/web#2737]
**Current Behavior**
When I use explorer to find matches of an amateur league (e.g. epulze: 12766) I  get 0 results.

**Expected behavior/code**
The query should return some games as you can see on [dotabuff](https://www.dotabuff.com/esports/leagues/12766-epulze-com/matches)

**Console Output**
There isn't any :)

**Environment**
- Browser Version: Firefox 85.0.1
- OS: Manjaro

**Additional context/Screenshots**
Example code:
```
SELECT
    *
FROM matches
WHERE matches.leagueid = 12766
LIMIT 10
```

**Comment by howardchung** [comment]
We only track premium/professional leagues in this table to keep the size manageable.

**Comment by DerMaddi** [comment]
Thank you for your respone, I managed to get the information directly via Steam API:
https://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/V001/?key=<key>&league_id=12766
