### ISSUE TITLE
How to query my matches with /explorer?

### ISSUE THREAD

**Issue by mqliutie** [odota/web#2740]
**Explain your question as detailed as possible**

I want to get all matches by `account_id` . 

I have tried to do.

**The first way**
I have done `https://api.opendota.com/api/players/{account_id}/matches` but data after index 500, all `item_{0-6}` is null,

If request `https://api.opendota.com/api/matches/{match_id}` `item_{0-6}` have correct value.

**The second way**

`https://api.opendota.com/api/explorer?sql=select * from player_matches where account_id={xxx}`  but response `rows` is empty array.

**Comment by howardchung** [comment]
We did not store data for end-game items in the past. You can get the list of match IDs and make individual requests for each match if you need that data.

**Comment by mqliutie** [comment]
Ok , It’s just that one  by one request is too time-consuming
