### ISSUE TITLE
league id = 0

### ISSUE THREAD

**Issue by monsterofmusicvids** [odota/web#2742]
In the live endpoint all matches have the 'league_id' = 0.

**Comment by howardchung** [comment]
Does that happen even with a match you've confirmed to be part of a league?

**Comment by monsterofmusicvids** [comment]
yeah , for a while all matches from the live endpoint have this problem. the official valve api has the league ids in the GetLiveLeagueGames endpoint and i would use that but i also need the names connected to those ids but their league info endpoint doesn't work.

**Comment by howardchung** [comment]
We currently source the data for this endpoint from GetTopLiveGame so I guess league games aren't included? Maybe could combine with the result of GetLiveLeagueGames

**Comment by howardchung** [comment]
But as a workaround for now you could use OpenDota's league endpoint to match up the IDs with names

**Comment by monsterofmusicvids** [comment]
Yes. First thank you! i wasn't  aware the GetTopLiveGame  was actually a working endpoint.  So thank you for that. i will use the opendota endpoint to match the league name with the id. if you don't mind me asking where do you get that info (leagueid = name) the GetLeagueListing endpoint for 570 does not work for me and the 205790 one seems to end a few years ago. 

Thanks a lot! Cheers!

**Comment by howardchung** [comment]
Looks like http://www.dota2.com/webapi/IDOTA2League/GetLeagueInfoList/v001

**Comment by monsterofmusicvids** [comment]
oh wow! i was using the endpoint from http://api.steampowered.com/IDOTA2Match_<ID>/GetLeagueListing/v1/ and scratching my head. 
Thank you!
