### ISSUE TITLE
"Chat" tab not showing anything but in-game Chat Wheels

### ISSUE THREAD

**Issue by viciecal** [odota/web#2747]
Dunno why this started happening, but it's kind of annoying. I'll just attach games of my own as a proof, in those games there was a lot of all chat, however the API is somehow not parsing the messages. I had nobody muted during games + All Players message social tab enabled.

[Game 1](https://www.opendota.com/matches/5910998209/chat)
[Game 2](https://www.opendota.com/matches/5918808776/chat)
[Game 3](https://www.opendota.com/matches/5918714446/chat)
[Game 4](https://www.opendota.com/matches/5916858944/chat)

**Comment by howardchung** [comment]
We've been chatting about this on Discord and think we've found the new way chat messages are stored (they got moved). We should have a fix soon (and you can manually request reparses for games missing chat)

**Comment by howardchung** [comment]
Currently blocked by https://github.com/skadistats/clarity-protobuf/issues/8
