### ISSUE TITLE
Thai translation

### ISSUE THREAD

**Issue by radiusgreenhill** [odota/web#2751]
Thai translation on crowdin is now completed.
Please implement it so I can see if there is any issue.

I’m happy to help :)

**Comment by howardchung** [comment]
I think we have to manually fix up the conflicts in https://github.com/odota/web/pull/1958 and merge. It's been a while since we did that. . .

**Comment by radiusgreenhill** [comment]
`  "gold_reasons_11": "สิ่งก่อสร้าง",
  "gold_reasons_12": "ฮีโร่",
  "gold_reasons_13": "ครีป",
  "gold_reasons_14": "Roshan",
  "NULL_gold_reasons_15": "Courier",
  "gold_reasons_14": "ครีปป่า",
  "gold_reasons_15": "Roshan",
  "NULL_gold_reasons_16": "Courier",
  "gold_reasons_17": "รูน",
  "gold_reasons_20": "Ward",
  "header_request": "ร้องขอ",
  "header_distributions": "การกระจาย",
  "header_heroes": "ฮีโร่",`

**Comment by radiusgreenhill** [comment]
`  "gold_reasons_11": "สิ่งก่อสร้าง",`
`  "gold_reasons_12": "ฮีโร่",`
`  "gold_reasons_13": "ครีป",`
`  "gold_reasons_14": "Roshan",`
`  "NULL_gold_reasons_15": "Courier",`
`  "gold_reasons_14": "ครีปป่า",`
`  "gold_reasons_15": "Roshan",`
`  "NULL_gold_reasons_16": "Courier",`
`  "gold_reasons_17": "รูน",`
`  "gold_reasons_20": "Ward",`
`  "header_request": "ร้องขอ",`
`  "header_distributions": "การกระจาย",`
`  "header_heroes": "ฮีโร่",`
