### ISSUE TITLE
Fix dawnbreaker image

### ISSUE THREAD

**Issue by howardchung** [odota/web#2755]
Looks like the old URL scheme does not work for dawnbreaker.

There is a new image available at https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dawnbreaker.png

However this doesn't support the multi-sizes that some of the code currently relies on.

We can update the code to use the new URLs and give up sized images, or special-case Dawnbreaker in HeroImage.jsx.

**Comment by howardchung** [comment]
This is partially fixed but still not working on the player page (maybe it doesn't use HeroImage.jsx?)

Also we need to find the new URLs for ability images since they don't seem to be available for Dawnbreaker

**Comment by iversonLv** [comment]
Hi, new hero image and icon path and name are different from other heros'  
Could we update them consistently?  
Example  
https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/snapfire_full.png?  
New hero  
https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dawnbreaker.png  

icon  
https://steamcdn-a.akamaihd.net/apps/dota2/images/heroes/bounty_hunter_icon.png  
new hero  
https://www.opendota.com/assets/images/dota2/heroes/135_icon.png  

Thanks.

**Comment by aemreaydin** [comment]
Hey,
I would like to work on this. I'm new here and this will be my first issue.
@howardchung I see that HeroImage.jsx has some temporary fixes for DawnBreaker and the other new heroes.
But the Heroes Page - Header.jsx get the image prefix from the env. so it doesn't work.

We can have another temporary solution where we update the getHeroImage function and use a different url for dawnbreaker.
Or can we just use HeroImage.jsx instead of a HeroAvatar styled-comp?

I will just go through the code till I hear more from you guys.

**Comment by howardchung** [comment]
A few different things here:
* We probably want to switch the heroes header to use HeroImage.jsx so all the code is in one place
* We need to update all the hero images to use the new URL path as new images will probably not be uploaded to the old one

**Comment by aemreaydin** [comment]
- Using HeroImage in the header works well, but the size will be different from the former version. I used IMAGESIZE_ENUM.MEDIUM for it.
- However, the problem remains for the abilities and header background image. To me, it seems like the primary solution is to figure out what the main source of the images should be. Is it possible to host the images locally, like in core?

**Comment by howardchung** [comment]
Yeah, I think that's the best solution.

We would lose the ability to have multiple image sizes though, so need to find those callsites and verify they're ok with the single image size.

**Comment by aemreaydin** [comment]
So, the url changes should also be made in the core, right?
How should I proceed with this issue?

**Comment by howardchung** [comment]
No, I don't think any changes need to be made in core. You can try changing the REACT_APP_CDN_URL to point to the new location and fix any issues that come up. There will need to be a fair amount of manual validation.

**Comment by aemreaydin** [comment]
This is what is being fetched from the web app
/apps/dota2/images/heroes/dawnbreaker_full.png?
I believe the urls should be changed to
/apps/dota2/images/dota_react/heroes/dawnbreaker.png

The reasoning behind this is that dota2.com's new redesign is using this url path to fetch the images.

**Comment by howardchung** [comment]
Oh yeah, we'd also need to update dotaconstants to the new path. maybe we can get away with just a runtime replacement for now while we test, but at some point we'll want to update that as well.

**Comment by aemreaydin** [comment]
Oh, we're fetching the hero information from dotaconstants? That should make things easier probably.

Here is what i've done so far;

- In Hero/Header.jsx replaced HeroAvatar comp. to HeroImage.jsx/HeroImage comp
-- This fixes the Dawnbreaker hero image, but doesn't fix the abilities or the hero background blurry image. For that the fetched urls should be changed.
- Added the new url path to .env.

I guess I'm not sure what I should be doing next. I can fork and update dotaconstants, maybe?

**Comment by howardchung** [comment]
Yeah, then you can test with your forked version of dotaconstants.
