### ISSUE TITLE
OpenDota missing a match entirely

### ISSUE THREAD

**Issue by Crossfiyah89** [odota/web#2767]
The issue isn't that it won't parse, but rather, it isn't showing up in the list of matches played.

https://www.opendota.com/players/83853375/matches

The last match here played on 4/29 is 5971138353, a 2-9-33 win. 

![OpenDota](https://user-images.githubusercontent.com/30727919/116720831-a2745700-a9aa-11eb-8512-f7831d7fa77b.PNG)

However, if I navigate to other external data collection sites:

https://www.dotabuff.com/matches/5971192538

The last match here played is a 7-4-20 win.

![Dotabuff](https://user-images.githubusercontent.com/30727919/116720813-9e483980-a9aa-11eb-8721-6000f0c98cef.PNG)

**Comment by Crossfiyah89** [comment]
My profile:

https://www.opendota.com/players/83853375/overview

**Comment by Crossfiyah89** [comment]
5971192538

Match ID from Dota 2 client.

**Comment by howardchung** [comment]
The Steam API sometimes drops matches. You can fix by clicking the "refresh" button on your profile which I've done for you.

There is a background process that also does this, but it may not trigger for a particular user for a few days.
