### ISSUE TITLE
7.30 Date is incorrect

### ISSUE THREAD

**Issue by loegare** [odota/web#2820]
The cutover between patch 7.29 and 7.30 is incorrect

**Comment by builder-247** [comment]
Can you elaborate? What would be the correct date?

**Comment by loegare** [comment]
this game https://www.opendota.com/matches/6141705552 is listed as being
under 7.29, but if you look at tinkers skill build it is clearly in 7.30

**Comment by builder-247** [comment]
Clicking the re-parse button changed the patch to the correct number, the game was probably processed before we had the correct data set up.

**Comment by loegare** [comment]
Fair play
