### ISSUE TITLE
Minor inconsistency in heroes stats page

### ISSUE THREAD

**Issue by evilmtv** [odota/web#2826]
https://www.opendota.com/heroes/pro
https://www.opendota.com/heroes/public
uses 'matches in last 30 days'

https://www.opendota.com/heroes/turbo
uses 'matches this month'

**Comment by davidherszenhaut** [comment]
Looking at Line 65 in [`src/components/Heroes/index.jsx`](https://github.com/odota/web/blob/master/src/components/Heroes/index.jsx#L65), it seems like the two different subtitles for Turbo and non-Turbo was done on purpose.

```jsx
subtitle={`${abbreviateNumber(matchCount)} ${key === 'turbo' ? strings.hero_this_month : strings.hero_last_30days}`}
```

**Comment by howardchung** [comment]
Yeah, they have slightly different countin mechanisms. But I think it's better to store the data per day as described in https://github.com/odota/core/issues/2658 and then we can show last 30 days for both
