### ISSUE TITLE
Doesn't see the games

### ISSUE THREAD

**Issue by pudgemladshii** [odota/web#2829]
There was a problem that when the statistics were updated, only 1700 games on the hero out of 2370 appeared on the site, although up to 2000 games were updated on the same dotabuff, what could be connected with? Played for about a year with a hidden account.

id dotabuff / opendota 389373662

Google translate sorry =p

**Comment by hikara987** [comment]
unable to parse the games at the moment. "Failed to get match data"

**Comment by howardchung** [comment]
The games played while hidden may not be fetchable anymore, unfortunately.
