### ISSUE TITLE
Two unparsed matches causing http status code: 500 error in MangoByte when any query is attempted that captures them.

### ISSUE THREAD

**Issue by Crossfiyah89** [odota/web#2893]
For whatever reason, two of my matches from 18 days ago did not parse and will not parse now. Since then, any query using MangoByte fails when attempting to analyze this data.

Matches in question:

https://www.opendota.com/matches/6374277000

https://www.opendota.com/matches/6374220596

As a side note, all matches are now Unknown skill level on my account since these two have been played.

**Comment by howardchung** [comment]
These two look fine on the OpenDota website, maybe you can check with the MangoByte author to confirm what the issue is.

Skill level is no longer available from the Steam API (not related to this)

**Comment by Crossfiyah89** [comment]
It looks like they finally parsed, maybe something you did on your end? Not
sure. But the queries are working now. Thanks!
