### ISSUE TITLE
Water Rune 

### ISSUE THREAD

**Issue by kshammer** [odota/web#2932]
**Is your feature request related to a problem? Please describe.**
In the match log water runes are not represented. 
![image](https://user-images.githubusercontent.com/5688067/163913662-91a944c6-edc5-4a1e-a25d-3f0b8d50060a.png)

**Describe the solution you'd like**

Adding water runes to the rune chart. 

**Describe alternatives you've considered**

N/A

**Teachability, Documentation, Adoption, Migration Strategy**
N/A 

I was looking to implement this myself but I wanted to check a few things first. It looks like all I need to do is add the rune to the assets and than add a mapping in the language json files. I was wondering where the rune pngs are sourced from and to check that mentioned above is all I need to complete.

**Comment by howardchung** [comment]
Yes I think that's it. I don't remember where we got the pictures. . . maybe from a wiki?
