### ISSUE TITLE
Axe cullingblade buffs are tracked as royal jelly

### ISSUE THREAD

**Issue by Turmfalke2** [odota/web#2938]
hi,
Have a look at this game:

https://www.opendota.com/matches/6552707711

Apparently the number of culling blade buffs is tracked as royal jelly buffs.

**Comment by TDP17** [comment]
Necrophos also shows up as aa/other -> that image should be changed as well I think
![image](https://user-images.githubusercontent.com/71214045/167270098-f1de8efd-729d-4211-b50c-880a9a3dd2a7.png)
