### ISSUE TITLE
Не скачивается запись матча

### ISSUE THREAD

**Issue by nodirnavruzov** [odota/web#2945]
**Current Behavior**
Не работает кнопка Запись (т.е не скачивается повтор матча)

**Console Output**
Ничего так как пытается окрыть другую вкладку при нажатии Запись
НО при нажатии обработать повторно выводиться: 
GET https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js net::ERR_BLOCKED_BY_CLIENT

**Environment**
- Browser Version: 102.0.5005.61 (Официальная сборка), (64 бит)

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/71634617/171136266-521f5959-2867-4fdc-b2e4-1c3f504d5c46.png)

![image](https://user-images.githubusercontent.com/71634617/171137057-11e19cb1-d459-4152-8110-94af3ab8c354.png)

**Comment by builder-247** [comment]
Looks like Chromium doesn't like downloading from http, you can still download it if you right click the button and select "Save link as", or use Firefox.

**Comment by nodirnavruzov** [comment]
thanks this solved my problem
