### ISSUE TITLE
Incorrect Hero Benchmarks (Game Analysis)

### ISSUE THREAD

**Issue by lostpolaris** [odota/web#2980]
**Current Behavior**
A clear and concise description of the behavior.
GPM and XPM are inflated by 1000 units each (e.g. 500gpm -> 1500gpm)
KPM and LHM are inflated by 10 units each
HDM is inflated by 10000 units

This seems to not be flat, but rather, based on the 10^x size of the unit. 

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).
For benchmarking units to be correct and not inflated. 

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![image](https://user-images.githubusercontent.com/6691735/179300943-e1b20fe5-2251-461d-a4d4-67baeaff43a5.png)

![image](https://user-images.githubusercontent.com/6691735/179300965-29b6ce71-339a-4547-8d57-9db5ac94d318.png)

![image](https://user-images.githubusercontent.com/6691735/179300980-9a022481-3c3f-4f10-84db-9b35b4baf748.png)

![image](https://user-images.githubusercontent.com/6691735/179301004-0dff469c-0820-43d2-94dd-4817ef0f6995.png)

**Comment by naelito24** [comment]
no aparecen mis partidas anteriores ni el indice de victoria que tengo
