### ISSUE TITLE
Benchmarks for certain heroes with low pick rates are incorrect

### ISSUE THREAD

**Issue by JVIPerson240** [odota/web#2993]
**Current Behavior**
Benchmarks for certain heroes with low pick rates stop increasing after a certain point. The GPM benchmark for Oracle is the same at 70% as it is for 99%. Dark Willow is the same. This is reflected in game analysis as shown in: https://www.opendota.com/matches/6709248063/benchmarks

https://www.opendota.com/heroes/111/benchmarks
https://www.opendota.com/heroes/119/benchmarks

**Expected behavior/code**
Benchmarks should accurately show the GPM and other stats in a game.

**Environment**
- Browser Version: Firefox 103.0.2 (64-bit

Oracle Benchmarks as seen on the website.
![OpendotaScreenshot](https://user-images.githubusercontent.com/106777739/186301080-b9df4d34-ccc5-467a-91dd-91775fb2f9ed.PNG)
)

**Comment by howardchung** [comment]
This is due to the reduction in auto-parsed matches. 

Solutions:
* Increase the sampling interval from 3 days to something like a week
* Only track benchmarks for unparsed stats (i.e. remove LH@10 and stuns since this requires parsing)
* Add more subscribers to increase the sample size

**Comment by howardchung** [comment]
Switched benchmarks to run on non-parsed data only so we have enough to do meaningful comparisons. It may take a week or so to populate data though
