### ISSUE TITLE
I cant get Api key.The website keep showing "There was an error with the request. Please try again. If it continues, contact us at support@opendota.com."

### ISSUE THREAD

**Issue by thinh1991999** [odota/web#3005]
**Current Behavior**
A clear and concise description of the behavior.

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by howardchung** [comment]
Please email support, but this may be due to an unpaid invoice or using an non-accepted form of payment.
