### ISSUE TITLE
Bugs of my rank

### ISSUE THREAD

**Issue by AojiaoU** [odota/web#3008]
My Dota2 ID is 368705895 and I reached rank of Immortal 1 week ago. But in OpenDota it still tells me that my rank is Divine 5. Plz fix my rank thx!

**Comment by builder-247** [comment]
You need to play one ranked game I believe.

**Comment by AojiaoU** [comment]
> You need to play one ranked game I believe.

i cannot. I only play in 5 people party for rank. But after i got to immortal, we spent 1 hour finding opponents but still cannot find a game in SEA sever. Then we gave up rank.
