### ISSUE TITLE
Hero points are not awarded for the victory

### ISSUE THREAD

**Issue by KawaiEvai** [odota/web#3027]
Hero points are not awarded for this match : 6802852741

**Comment by howardchung** [comment]
What are hero points?

**Comment by KawaiEvai** [comment]
before this match it was 8400, after, too, this game seemed not to be
counted
https://www.opendota.com/matches/6802852741

чт, 13 окт. 2022 г. в 21:42, Howard Chung ***@***.***>:

**Comment by howardchung** [comment]
I assume this is hero ranking points. There may be a small percentage of matches that are not ranked due to infrastructure issues, but this should be quite uncommon.
