### ISSUE TITLE
excluded tier for eeu qualifiers

### ISSUE THREAD

**Issue by ergmyth** [odota/web#3050]
https://api.opendota.com/api/leagues/14880/matches
eeu qualifiers has an "EXCLUDED" league tier. Why is that? There is no match history too.

**Comment by howardchung** [comment]
does it have "Open Qualifier" in the name?

We excluded those because past qualifiers had thousands of games played by the public: https://github.com/odota/core/blob/f27ca8b5aff14a6a0912a870c71cae6ae923866a/svc/leagues.js#L19
