### ISSUE TITLE
Bug report, opendota profile

### ISSUE THREAD

**Issue by anda3007** [odota/web#3066]
My opendota profile is broken, it shows that i have played 0 games, 0 win 0 everything

My steam profile is opened
![Screenshot_20230201-143515_Chrome](https://user-images.githubusercontent.com/124159564/216043968-595ecf1c-df2d-4337-becb-0e6a9af8b545.jpg)

**Comment by kolya140** [comment]
да блять такая же хуйня параша какая-то

**Comment by howardchung** [comment]
Likely due to Expose Public Match Data not enabled
