### ISSUE TITLE
Scenarios data is not working as expected 

### ISSUE THREAD

**Issue by hainej96** [odota/web#3087]
**Current Behavior**
Query is not returning any results for any hero with a selected item. I am trying to do PA for example with BKB at minutes 15-20

**Expected behavior/code**
Query should return win/loss for that purchased item timing.

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [Latest version of chrome.]
- OS: [Windows 10 ]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by howardchung** [comment]
This is likely due to the decrease in auto-parsed matches leading to less available data for scenarios

**Comment by howardchung** [comment]
I also found another reason that data may not have been showing up--the min threshold was set at 200 games to show data. Since the number of parsed games is much lower now I reduced this to 10 matches.
