### ISSUE TITLE
GET/players/{player_id}/heroes?lane_role=1&patch={patch_id} not displaying correct info

### ISSUE THREAD

**Issue by hainej96** [odota/web#3088]
**Current Behavior**
request displaying incorrect information. Tested this out by using my last recent games on patch_id=52 (7.33*), the request is returning all 0's in the strings when it should not.  

**Expected behavior/code**
For example, my last game recorded was with Enchantress in lane_role=1 (safe lane) and I had lost. Therefore the request should display "1" in the games array in the schema but it does not.

**Console Output**
Not needed.

**Environment**
- Browser Version: [Latest Chrome ]
- OS: [Windows 10]

**Comment by howardchung** [comment]
can you share a specific link that repros this issue?

**Comment by hainej96** [comment]
I think i just clocked as to why, recent match data has not been parsed therefore schema data returns 0's. My question is at what rate do recent matches get parsed?

**Comment by howardchung** [comment]
Matches are parsed if they're part of a pro league or if one of the users in it is a subscriber.

**Comment by hainej96** [comment]
Ahhh i see, so id have to manually click parse data for all matches that I have done to get my full history?

**Comment by howardchung** [comment]
Yes, or you can subscribe for automatic parsing.
