### ISSUE TITLE
7.33 map image for warding data

### ISSUE THREAD

**Issue by hainej96** [odota/web#3090]
**Is your feature request related to a problem? Please describe.**
Is there a way to implement the new map png?

**Describe the solution you'd like**
Could we replace the map for patch_id=52 with the updated changes valve has made so that the warding heat map makes sense?

**Teachability, Documentation, Adoption, Migration Strategy**
Here is the 7.33 map
![7 33 Map](https://user-images.githubusercontent.com/132407066/236167500-fdeee808-42de-400e-9c2b-162be9cf7b00.jpg)

**Comment by hainej96** [comment]
If someone could also provide information about how the co-ordinate system in the game for the wards is placed onto the map that would be great.

**Comment by hainej96** [comment]
Showing as closed but still not fixed

**Comment by howardchung** [comment]
Changes need to be shipped to production branch.
