### ISSUE TITLE
Database maintains rows where the dire team is equivalent to the radiant team

### ISSUE THREAD

**Issue by awesomeme** [odota/web#3097]
See The following MatchIds, all of which have "Old G" facing off against "Old G" in the database:

[Closed Qualifier; Old G versus PuckChamp](https://liquipedia.net/dota2/Dota_Pro_Circuit/2023/2/Western_Europe/Closed_Qualifier)
[7069797381](https://www.dotabuff.com/matches/7069797381) 
[7069894558](https://www.dotabuff.com/matches/7069894558)
[7069991877](https://www.dotabuff.com/matches/7069991877)

[Division2; Old G versus PuckChamp](https://liquipedia.net/dota2/Dota_Pro_Circuit/2023/2/Western_Europe/Division_II)
[7110613815](https://www.dotabuff.com/matches/7110613815)
[7110700225](https://www.dotabuff.com/matches/7110700225)
[7110751876](https://www.dotabuff.com/matches/7110751876)

**Comment by howardchung** [comment]
That is strange--possibly some weirdness coming back from the Steam API?

**Comment by howardchung** [comment]
Yeah i just checked the response it just looks incorrect:

{
"result": {
"players": [],
"radiant_win": true,
"duration": 2498,
"pre_game_duration": 90,
"start_time": 1679331272,
"match_id": 7069797381,
"match_seq_num": 5936849327,
"tower_status_radiant": 1846,
"tower_status_dire": 0,
"barracks_status_radiant": 63,
"barracks_status_dire": 48,
"cluster": 271,
"first_blood_time": 245,
"lobby_type": 1,
"human_players": 10,
"leagueid": 15147,
"positive_votes": 0,
"negative_votes": 0,
"game_mode": 2,
"flags": 1,
"engine": 1,
"radiant_score": 21,
"dire_score": 15,
"radiant_team_id": 8944337,
"radiant_name": "Old G",
"radiant_logo": 2051993695241003800,
"radiant_team_complete": 1,
"dire_team_id": 8261648,
"dire_name": "Old G",
"dire_logo": 2057626457212027100,
"dire_team_complete": 1,
"radiant_captain": 88271237,
"dire_captain": 104334048,
"picks_bans": [
{
"is_pick": false,
"hero_id": 114,
"team": 1,
"order": 0
},
{
"is_pick": false,
"hero_id": 61,
"team": 0,
"order": 1
},
{
"is_pick": false,
"hero_id": 32,
"team": 1,
"order": 2
},
{
"is_pick": false,
"hero_id": 91,
"team": 0,
"order": 3
},
{
"is_pick": true,
"hero_id": 72,
"team": 1,
"order": 4
},
{
"is_pick": true,
"hero_id": 53,
"team": 0,
"order": 5
},
{
"is_pick": true,
"hero_id": 128,
"team": 0,
"order": 6
},
{
"is_pick": true,
"hero_id": 106,
"team": 1,
"order": 7
},
{
"is_pick": false,
"hero_id": 74,
"team": 1,
"order": 8
},
{
"is_pick": false,
"hero_id": 137,
"team": 0,
"order": 9
},
{
"is_pick": false,
"hero_id": 76,
"team": 1,
"order": 10
},
{
"is_pick": false,
"hero_id": 90,
"team": 0,
"order": 11
},
{
"is_pick": false,
"hero_id": 93,
"team": 1,
"order": 12
},
{
"is_pick": false,
"hero_id": 98,
"team": 0,
"order": 13
},
{
"is_pick": true,
"hero_id": 86,
"team": 0,
"order": 14
},
{
"is_pick": true,
"hero_id": 135,
"team": 1,
"order": 15
},
{
"is_pick": true,
"hero_id": 75,
"team": 1,
"order": 16
},
{
"is_pick": true,
"hero_id": 35,
"team": 0,
"order": 17
},
{
"is_pick": false,
"hero_id": 54,
"team": 1,
"order": 18
},
{
"is_pick": false,
"hero_id": 4,
"team": 0,
"order": 19
},
{
"is_pick": false,
"hero_id": 43,
"team": 1,
"order": 20
},
{
"is_pick": false,
"hero_id": 67,
"team": 0,
"order": 21
},
{
"is_pick": true,
"hero_id": 46,
"team": 1,
"order": 22
},
{
"is_pick": true,
"hero_id": 38,
"team": 0,
"order": 23
}
]
}
}

**Comment by builder-247** [comment]
From my understanding Old G bought Puck Champ's DPC slot and transferred players, probably related to that?

**Comment by howardchung** [comment]
I think this is just due to an incorrect name in Valve's DB. Closing since it should eventually get fixed
