### ISSUE TITLE
word cloud not working

### ISSUE THREAD

**Issue by asewtuu** [odota/web#3100]
I wanted to see my word cloud, but it does not give out. Instead, an empty field is left behind. What could be the reason for this?
![word cloud](https://github.com/odota/web/assets/136371524/01b1ec55-6013-475e-981e-7da5a66e11e7)

**Comment by howardchung** [comment]
It likely means you don't have any parsed matches to draw data from.

**Comment by howardchung** [comment]
You can manually request parses of individual matches, or subscribe to have your future matches auto-parsed

**Comment by asewtuu** [comment]
> You can manually request parses of individual matches, or subscribe to have your future matches auto-parsed

what should i click to request query the parses of individual matches?

**Comment by builder-247** [comment]
> > You can manually request parses of individual matches, or subscribe to have your future matches auto-parsed
> 
> what should i click to request query the parses of individual matches?

![image](https://github.com/odota/web/assets/14019974/4e8db84d-b466-46a3-8c08-3b456e94be22)

**Comment by asewtuu** [comment]
> > > You can manually request parses of individual matches, or subscribe to have your future matches auto-parsed
> > 
> > 
> > what should i click to request query the parses of individual matches?
> 
> ![image](https://user-images.githubusercontent.com/14019974/245803591-4e8db84d-b466-46a3-8c08-3b456e94be22.png)

thanks a lot

**Comment by asewtuu** [comment]
> > > You can manually request parses of individual matches, or subscribe to have your future matches auto-parsed
> > 
> > 
> > what should i click to request query the parses of individual matches?
> 
> ![image](https://user-images.githubusercontent.com/14019974/245803591-4e8db84d-b466-46a3-8c08-3b456e94be22.png)

one more clarification, I guess only recent matches can be processed?

**Comment by builder-247** [comment]
> > > > You can manually request parses of individual matches, or subscribe to have your future matches auto-parsed
> > > 
> > > 
> > > what should i click to request query the parses of individual matches?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/14019974/245803591-4e8db84d-b466-46a3-8c08-3b456e94be22.png)
> 
> one more clarification, I guess only recent matches can be processed?

Correct, replays expire after around 10 days
