### ISSUE TITLE
Chaos Knight's illusions give additional hero kill to enemies

### ISSUE THREAD

**Issue by RazorEdwards** [odota/web#3111]
**Current Behavior**
A clear and concise description of the behavior.

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by builder-247** [comment]
There is currently a gameplay bug in Dota that causes armlet heroes to give multiple kill credits, see https://github.com/ValveSoftware/Dota2-Gameplay/issues/11139. Closing as this is not an OpenDota bug.
