### ISSUE TITLE
Matches not parsing 

### ISSUE THREAD

**Issue by infamaniac23** [odota/web#3115]
**Current Behavior**
A clear and concise description of the behavior.

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by nightblade9** [comment]
Thank you for the update.

Out of curiousity, when things are working normally, how long does it typically take between requesting a match to be parsed, and the back-end finishing the parsing?

**Comment by howardchung** [comment]
If there's no queue it should only take 15 seconds or so

**Comment by Hunken100** [comment]
Same issue with TI matches. Do you have an ETA for a fix? Thanks!

**Comment by howardchung** [comment]
We're getting lower throughput than expected and are still around 45k matches behind, which should take 1-2 days to clear. I'm looking into adding some code to give TI matches higher priority though

**Comment by Hunken100** [comment]
Thanks for the detailed and prompt reply. Very excited that TI is finally live and looking forward to analyzing the high-quality data you provide. Keep up the great work!

**Comment by anthonyAA11** [comment]
Hello @howardchung,
Is there a way for us to see the parse queue ?
Thanks ;)

**Comment by nightblade9** [comment]
Looks like the parsing is done. Thank you so much! I think you can close this issue now.

**Comment by insanewh** [comment]
matches are still not parsing and hence it is still an issue.

**Comment by howardchung** [comment]
The queue is currently 1.7k which is slightly elevated but within typical levels. We may encounter occasional periods of slightly delayed (minutes) parses if there's a spike in requests, but it should mostly be fine. If you have a specific match ID that is not parsing within a day, please open a new issue

**Comment by Jilly0702** [comment]
I'm wondering why the cosmetics column is empty?

**Comment by Jilly0702** [comment]
I'm wondering why the cosmetics column is empty? Thanks!

**Comment by howardchung** [comment]
Probably because the replay format changed at some point and we never fixed the parser

**Comment by builder-247** [comment]
Might be related to https://github.com/odota/core/issues/2646

**Comment by Jilly0702** [comment]
Will you fix the parser again? The cosmetic tab has no items now and I really need to have a look about them. Thanks!!!

**Comment by Jilly0702** [comment]
<img width="1430" alt="截屏2023-10-18 下午3 33 54" src="https://github.com/odota/web/assets/148155025/4f3f567b-6eda-4ab7-a660-a1de9b7dff89">

**Comment by howardchung** [comment]
Cosmetics have been fixed now!
