### ISSUE TITLE
Official page and api page always loading

### ISSUE THREAD

**Issue by ameame-yzq** [odota/web#3119]
**Current Behavior**
When I click the official page, it always loads. But I can walk into it from another page.
I don't know how to fix it, just very confused.
ANYONE CAN HELP?

I don't know how to fix it, just come up with it. 

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- chrome 118.0.5993.117(official versio
- MacOS 14

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![bugshow2](https://github.com/odota/web/assets/67360422/9c496863-c53b-4e38-8bbc-eee69bb0d6cb)
![bugshow3](https://github.com/odota/web/assets/67360422/4da6595a-2828-46dc-906a-1366677b4c9a)

**Comment by howardchung** [comment]
Looks like an ad code issue, should be fixed
