### ISSUE TITLE
/matches/:id/laning unhandled error in production builds

### ISSUE THREAD

**Issue by prenaissance** [odota/web#3122]
**Current Behavior**
The specified page crashes on production build. The error doesn't seem to slip through on local development. Example: https://www.opendota.com/matches/7440809518/laning

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

**Possible Cause**
Vite upgrade api host variable

```
Uncaught (in promise) undefined
```

**Environment**
- Browser Version: Firefox 119
- OS: Windows 10

**Comment by howardchung** [comment]
Seems to be the same problem with heatmap.js. . . I'll take a look
