### ISSUE TITLE
Parse requests never complete.

### ISSUE THREAD

**Issue by SylvainBoilard** [odota/web#3128]
**Current Behavior**
When requesting a match to be parsed, the process never seems to complete.

**Expected behavior/code**
Match is parsed in about a minute as usual.

**Environment**
- Firefox 120 on Debian GNU/Linux Trixie/sid
- Chrome 119 on Android

Only three out of ten of my recent matches have been parsed, for which I did not have to request a parse as far as I remember. [My player page.](https://www.opendota.com/players/35509678)

**Comment by howardchung** [comment]
A lot of replays have been unavailable lately--you can verify by attempting to download it

**Comment by Jilly0702** [comment]
I also met this problem. The professional matches can be parsed, but the public matches cannot be parsed.

**Comment by howardchung** [comment]
Pro matches and matches with a subscriber in them get higher priority in the queue.

**Comment by SylvainBoilard** [comment]
Apparently the replays have become available again and have been parsed.
