### ISSUE TITLE
Match not parsing

### ISSUE THREAD

**Issue by hly22** [odota/web#3132]
Match not parsing

Match ID: 7499729192

**Comment by howardchung** [comment]
The parse queue is currently backed up as someone has been sending in hundreds of thousands of requests per day. . . we're working through it and your match should be parsed eventually.

**Comment by Jilly0702** [comment]
Same problem here.

**Comment by Kalethars** [comment]
I think the strategy can be designed like: Only logged user can request to parse match, and once one match from a user is parsed, a punishment time is added to lower the priority of other matches requested by the same user.

**Comment by howardchung** [comment]
7499729192 is now parsed. The queue is also draining now, so closing this issue.
