### ISSUE TITLE
Show if a player's matches are being hidden

### ISSUE THREAD

**Issue by howardchung** [odota/web#3133]
Now that we're not displaying data for players with public match data disabled, we should update the UI to show a message if this is the case.

We can check the fh_unavailable property on the player call, and display a message like: "This player has disabled public match history. If this is you, sign in to view your own data."

**Comment by jeyren95** [comment]
hi can i take this too?

**Comment by howardchung** [comment]
Yes

**Comment by jeyren95** [comment]
Are you looking to move towards typescript + hooks?

If yes, i could also do the conversion for the relevant files i will be updating in this issue.

Idt there are many files to change anw, so the conversion will not be too major

**Comment by howardchung** [comment]
Ideally the TS conversion could go in one PR and then feature change in another

**Comment by howardchung** [comment]
Note: We recently re-enabled showing data for pro players. So we also want to check if the player is a pro player and not show the "hidden" message if so

**Comment by jeyren95** [comment]
Have opened a PR, do help to take a quick look whenever you're free, thanks!

**Comment by jeyren95** [comment]
created a PR [https://github.com/odota/web/pull/3156](url), pls help to take a look whenever you're free, thanks!
