### ISSUE TITLE
Eslint Broken in React application 

### ISSUE THREAD

**Issue by jzhao62** [odota/web#3134]
**Current Behavior**
- npm install should install all dependency for eslint 
- you cannot lint the code 

**Expected behavior/code**
- linter should work in npm and in IDE after simply hit npm install

**Console Output**
![image](https://github.com/odota/web/assets/25937657/d9a7271b-b971-4545-a451-4ce435310063)
![image](https://github.com/odota/web/assets/25937657/b5e69934-cb6e-4b81-973b-1d6c3e1aa68e)

**Environment**
- OS: windows 10
- branch: main

**Possible Solution**
- eslint cofigs needs reconfigure, a lot plugin eslint dependencies are missing from npm packages

**Comment by placintaalexandru** [comment]
Hello @jzhao62 
I've just started working on this one. The lint command works, however there are some babel related linting errors
