### ISSUE TITLE
404 images on hero page, https://www.opendota.com/heroes/86

### ISSUE THREAD

**Issue by Geczy** [odota/web#3137]
**Current Behavior**

https://www.opendota.com/heroes/86

404 image

![image](https://github.com/odota/web/assets/1036968/a701bb20-9a11-49b1-8fab-a472e3232147)

**Expected behavior/code**

show image

**Comment by Geczy** [comment]
Rubicks not the only hero. It's a bunch of them so I think we need a different fix. Check batrider too

**Comment by howardchung** [comment]
I think we just have to manually exclude all of these, unless we can identify a pattern

**Comment by Geczy** [comment]
Looking into it, we can fix this by filtering on `"behavior": "Hidden",`

https://github.com/odota/web/pull/3138
