### ISSUE TITLE
Possible error with deciding which players are pro

### ISSUE THREAD

**Issue by TyePie** [odota/web#3142]
**Current Behavior**
I think OpenDota has issues with deciding which players are pro.
I'm not sure how the decision is made, but I have an example.

https://www.opendota.com/players/237477486
The above player is listed in my matches as a pro, but they're somehow confirmed as a pro player in their OpenDota profile

**Expected behavior/code**
Mostly just not for heralds to be pro. I could be wrong, but I doubt.

**Additional context/Screenshots**
![image](https://github.com/odota/web/assets/49835438/9894898b-4245-4c75-a789-a501247d9919)

**Comment by howardchung** [comment]
Interesting, we source the list from https://www.dota2.com/webapi/IDOTA2Fantasy/GetProPlayerInfo/v001 and there are about 321 entries but it looks like there are over 2900 rows in the database. I'll purge it and let it repopulate with only those 321
