### ISSUE TITLE
Not show all statistic

### ISSUE THREAD

**Issue by Nurwaff** [odota/web#3145]
**Current Behavior**
Not show all statistic. Only 400 games from 1400, but profile is open

**Expected behavior/code**
how can I fix it?

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
proxyOverlay.js:1 Uncaught (in promise) TypeError: Cannot destructure property 'country' of '(intermediate value)' as it is null.
    at proxyOverlay.js:1:6311
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**
help(

**Additional context/Screenshots**
![image](https://github.com/odota/web/assets/157517405/d20bcdd5-9651-42e1-9458-f1291b45c092)

**Comment by howardchung** [comment]
Unfortunately we cannot currently fetch old matches played while a user was anonymous.
