### ISSUE TITLE
Clear w/l display on player page switch

### ISSUE THREAD

**Issue by howardchung** [odota/web#3148]
Currently the numbers for the previous player still appear when navigating to a new player page. We should show a spinner or at least clear the old values to avoid confusing users.

**Comment by howardchung** [comment]
Yes!

**Comment by jeyren95** [comment]
could you give me access to the repo? currently unable to push changes to a newly created branch, thanks!

**Comment by howardchung** [comment]
You should be able to make a fork and PR from the fork!
