### ISSUE TITLE
Part of MY RECORD WITH feature doesn't work properly

### ISSUE THREAD

**Issue by Z-M-STA** [odota/web#3159]
**Current Behavior**
After checking my games with wagamma the with/against feels random at some points.  Shows that I was against, but someone can easily disprove that by just checking the game and seeing we were on the same team. Some are correct, others are not.

**Environment**
-Chrome Version 122.0.6261.112 (Official Build) (64-bit)
-Windows 10 Pro  Version 22H2  Build 19045.4046

**Additional context/Screenshots**

![Screenshot_697](https://github.com/odota/web/assets/76900274/1169fceb-5d52-49dc-be14-676554d354db)
![Screenshot_698](https://github.com/odota/web/assets/76900274/a6feae58-7e31-450e-885e-083ca39ac4cb)
![Screenshot_699](https://github.com/odota/web/assets/76900274/660fab34-cfa8-4c38-a795-47db51ae680f)
![Screenshot_700](https://github.com/odota/web/assets/76900274/36b3ff88-26e7-41fe-a2c4-6242f7aca929)

**Comment by howardchung** [comment]
Do you have a link to your profile?

**Comment by howardchung** [comment]
Found the issue, thanks for pointing it out!
