### ISSUE TITLE
502 Internal server error on profile view

### ISSUE THREAD

**Issue by TheHandOfKing** [odota/web#3168]
**Current Behavior**
Accessing my profile https://www.opendota.com/players/148553398 yields a blank page. Here's the network tab:
![image](https://github.com/odota/web/assets/12826399/dbeb9b10-e1b1-495e-9fc7-5dc3925edfae)

Here's the cURL for wl if it helps in any way: 

curl 'https://api.opendota.com/api/players/148553398/heroes?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/counts?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/recentMatches?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/wl?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/peers?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/recentMatches?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/heroes?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/counts?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/wl?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/peers?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/recentMatches?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/heroes?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/counts?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/wl?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36' ;
curl 'https://api.opendota.com/api/players/148553398/peers?' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cookie: session=eyJwYXNzcG9ydCI6eyJ1c2VyIjoxNDg1NTMzOTh9fQ==; session.sig=0dF9LkzOu9kM_A2Gp5KAXDxbsY4' \
  -H 'origin: https://www.opendota.com' \
  -H 'referer: https://www.opendota.com/' \
  -H 'sec-ch-ua: "Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Mobile Safari/537.36'

**Expected behavior/code**
I should be able to view my profile

**Console Output**
500 Internal server error

**Environment**
- Browser Version: Brave latest
- OS: Win 10

**Comment by howardchung** [comment]
Looks like we're back now
