### ISSUE TITLE
Matches are not being parsed after clicking the Parse button

### ISSUE THREAD

**Issue by d-rez** [odota/web#3170]
**Current Behavior**
Matches are not being parsed after clicking the button. The page change to `Request a Parse`, then refreshes after a couple seconds, however the match will still not be parsed even hours after the last parse request (`The replay for this match has not yet been parsed. Not all data may be available.`)

**Expected behavior/code**
Match gets parsed and data gets added to the match page tabs/details

**Console Output**
N/A (nothing relevant in console, seems like a backend issue)

**Environment**
- Browser Version: Firefox 124.0.2
- OS: Win11

I believe the issue started yesterday or maybe around the weekend as I do remember it working last week.

Thanks for taking a look!

**Comment by howardchung** [comment]
What match IDs is this failing for? If the replay is too old it won't be available

**Comment by d-rez** [comment]
Hey, they were all recent matches. Example match that was failing until today: https://www.opendota.com/matches/7687363104

It's parsed now after I clicked parse again, so I'm guessing whatever was causing this over the last couple of days has been fixed :)
