### ISSUE TITLE
Frequent White Blank Screen 

### ISSUE THREAD

**Issue by insanewh** [odota/web#3173]
Whenever I try to view a player's profile it keeps coming up white blank screen

**Comment by JHansen451** [comment]
I'll second this issue. It also seems to break api.opendota.com/api/players<playerid>/heroes

**Comment by howardchung** [comment]
Looks like we had a database outage overnight, restarted and are catching up now (about 9 hours behind)

**Comment by d-rez** [comment]
Issue keeps happening to me, frequently get a white page when visiting my profile but not i.e. main page. So I can't really view stats for any of _my_ games.

Seems to depend on time of day? Sometimes it's fine, sometimes consistently getting white screen

**Comment by builder-247** [comment]
The rate limit seems to be a bit low for normal usage, been experiencing this too

**Comment by insanewh** [comment]
The white screen is happening again whenever I open a match. Seems to be link to the new patch. Pls see if can be fixed. Thanks

**Comment by howardchung** [comment]
Can you share a link where this is happening? Doesn't seem to be all matches

**Comment by insanewh** [comment]
https://www.opendota.com/matches/7875132950
Is one example

**Comment by howardchung** [comment]
Looks like an issue parsing some heroes' facets (e.g. Faceless Void). I put in a patch to fix the crash but we should fix the data issue in dotaconstants

**Comment by builder-247** [comment]
> Looks like an issue parsing some heroes' facets (e.g. Faceless Void). I put in a patch to fix the crash but we should fix the data issue in dotaconstants

I've identified the issue and can push a fix this week or next at the latest.
