### ISSUE TITLE
Absolutely no account statistics

### ISSUE THREAD

**Issue by Maxzillla** [odota/web#3174]
all statistics indicators are at zero, no number of games
no rank, nothing

![Снимок экрана 2024-04-23 091119](https://github.com/odota/web/assets/167847353/f57dcba6-45f9-40ee-a134-34290ef37884)

**Comment by SevenUpiii** [comment]
![изображение](https://github.com/odota/web/assets/168917978/302fc3db-7ca0-41e3-b70c-b68a66870643)
all statistics indicators are at zero, no number of games
no rank, nothing

**Comment by howardchung** [comment]
These issues both look like you need to enable public match data.

**Comment by SevenUpiii** [comment]
> These issues both look like you need to enable public match data. 
Dont work. maybe I should wait or smth
