### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sl0n123** [odota/web#3185]
I went to the opendota website a few days ago, and all these few days my profile has not been updated, the update button does not work, and my dota 2 profile is not updated, given that I have a publicly available history of matches in the game, what should I do?

**Comment by howardchung** [comment]
Expose Public Match Data needs to be toggled on, and we should pick up match data for any matches played while that's the case. Unfortunately we don't have a good way of going back and fetching previously anonymous matches.
