### ISSUE TITLE
Error at the moment of login 

### ISSUE THREAD

**Issue by 1adore1** [odota/web#3188]
**Current Behavior**
Trying to login in steam account, but it returns error. Also doesn't work at phone, and returns same error. 
**Expected behavior/code**
I am expected to log into my steam account correctly.
**Console Output**
```
{"error":"Internal Server Error"}
```

**Environment**
- Browser Version: Chrome 126.0.6478.114 (64bit)
- OS: Windows 11

**Possible Solution**

**Additional context/Screenshots**
It occurs at moment after you click on "sign in" on pic below.
![image](https://github.com/odota/web/assets/85411749/421f8bf1-e166-491c-978e-e973de002d0f)

**Comment by howardchung** [comment]
This should now be fixed, thanks for the report!
