### ISSUE TITLE
Old matches are gone

### ISSUE THREAD

**Issue by gwtjxyz** [odota/web#3189]
If I go back several years to check my dota matches, for example from a page like this, most matches are marked as parsed:
![image](https://github.com/odota/web/assets/20083177/d9feac7d-5790-4d5b-a389-38cb8d4e519e)
However, if I try to click on any one of these matches, [for example the Winter Wyvern game,](https://www.opendota.com/matches/4492903344) I only see this:
![image](https://github.com/odota/web/assets/20083177/2a8ce5cc-28d5-4cd6-9b43-4e00d482192a)
[My records](https://www.opendota.com/players/82941035/records) still seem to be in there but again, trying to click on any match that's over several years old gives me a 404. [Even this match from 8 months ago](https://www.opendota.com/matches/7355765647) gives me a 404, what gives? I've also noticed that historical trend data and word clouds for timelines older than around 4 years is gone, at least for me.

**Comment by howardchung** [comment]
This is due to the Steam API match details outage--I've re-enabled loading archived parsed data for matches that we have parsed in the past.
