### ISSUE TITLE
Consistently wrong heroes being listed

### ISSUE THREAD

**Issue by Gakezfus** [odota/web#3196]
The hero listed for several parts is incorrect. For example, in match https://www.opendota.com/matches/7885057978/ it describes Venomancer as picking up aegis twice even though both times it was WR who picked up aegis. The log page also has Venomancer denying everything in his base. Somehow, it seems like WR's stats are being recorded as Venomancer's for certain parts.

There are also several inconsistencies between the story and the log pages. For example, the log says that Razor killed Tiny for first blood, while the story page says that Razor killed Doom for first blood (not possible, they're allies). The log and story pages are inconsistent, so there seem to be differing reasons why the page is not working.

**Comment by howardchung** [comment]
This looks like an Immortal Draft game, which has a known issue and requires a parser fix: https://github.com/odota/core/issues/2811
