### ISSUE TITLE
Account information is not updated

### ISSUE THREAD

**Issue by Abramon765** [odota/web#3201]
I don't know what this has to do with, but the account information ends for 2019. The account privacy settings are open and for example dotabuff can see everything fine.

**Comment by howardchung** [comment]
We'll need a profile link to investigate.

**Comment by Abramon765** [comment]
> We'll need a profile link to investigate.

https://www.opendota.com/players/356631753/overview

**Comment by howardchung** [comment]
Public match history is not enabled for this account. You'll have to enable it in your Dota settings.

There are alternative ways of gathering match data that do not consider this setting, but we currently do not use them.

**Comment by BountyHanter** [comment]
> Public match history is not enabled for this account. You'll have to enable it in your Dota settings.
> 
> There are alternative ways of gathering match data that do not consider this setting, but we currently do not use them.

I have the same problem, I opened access to my data in the client, dotabuff updated my data and opendota does not update the data, even after an hour

**Comment by howardchung** [comment]
I've clicked "refresh" on your profile to force-update the visibility and your future matches should show up. Normally we'd be able to fetch the last 500 games as well but this is currently unavailable due to a Steam API issue that has been going on for the last few months

**Comment by BountyHanter** [comment]
> I've clicked "refresh" on your profile to force-update the visibility and your future matches should show up. Normally we'd be able to fetch the last 500 games as well but this is currently unavailable due to a Steam API issue that has been going on for the last few months

I also clicked this, on the dotabuff service when I clicked update, it immediately uploaded new games, but for some reason it does not load on opendota....

**Comment by howardchung** [comment]
This is because I suspect Dotabuff uses alternative methods of fetching match data that ignore the privacy setting and store that data for possible future use. They only make it visible to the user though when the setting is enabled. We do not store the ID data at all when the setting is off, which means we cannot currently toggle visibility without re-fetching the individual match data which is not currently possible with the outage.

**Comment by Mirai0987** [comment]
Hi i also have the same problem my matches wont update when I click the Refresh button steam profile is public. whenever I try to refresh nothing happens my recent matches is stuck on 2022. here's my profile https://www.opendota.com/players/111222425
