### ISSUE TITLE
 Issue with Replay Parsing - Unable to Access Match Details

### ISSUE THREAD

**Issue by zNefxly** [odota/web#3202]
Hello,

I’m experiencing an issue with accessing the details of my matches on both the Dota 2 client and third-party sites like OpenDota. Specifically, I keep receiving the error: "The replay for this match has not yet been parsed. Not all data may be available." 

Match replays are either locked or the data isn't fully available even after waiting several days. This happens frequently, especially with older matches, and I’m unable to view the item builds, skill progression, or other key match details.

Could you please assist me in resolving this issue? I would like to know how I can access these replays or if there’s any step I need to take to ensure they are properly parsed and available.

Thank you for your help!

Best regards, zNefxly

![Screenshot_2024-09-02-22-35-11-327_com android chrome](https://github.com/user-attachments/assets/556ffa59-83ae-43dd-aabd-488f44df949f)

**Comment by howardchung** [comment]
Match replays are deleted after 10 days or so, so we cannot parse matches older than that.

**Comment by zNefxly** [comment]
Is there no other way?
I need a cool item build
I want to copy it from players
