### ISSUE TITLE
 Issue with Full Match History Not Displaying

### ISSUE THREAD

**Issue by I-Notoriuos** [odota/web#3208]
Hello OpenDota Support, 

I hope you're doing well. I am experiencing an issue with my match history not displaying properly on OpenDota. Although my Steam profile and game details are set to public, I can only see the last 6 matches I played, despite having over 4,500 matches in total.

Here are a few details about my settings:

My Steam profile is set to public.
My Dota 2 match history is also public.
The "Details of the games" in Steam privacy settings are configured to be visible to everyone.
Within Dota in social settings, check the box for "share game stats"

MY ID: 336403213

I have already tried refreshing my profile on OpenDota, but the issue persists. Could you please help me resolve this or check if there is a problem with syncing my full match history?

Thank you for your time and assistance.

**Comment by howardchung** [comment]
Unfortunately due to a Steam API outage we are currently unable to fetch old matches from while a user was anonymous. Previously we would be able to get the 500 most recent matches.
