### ISSUE TITLE
Matches are not recorded

### ISSUE THREAD

**Issue by MaxMishin1991** [odota/web#3212]
**Current Behavior**
Hello! The problem is the following. Matches are not recorded even though the account is open. We tried updating the page and device, but it didn’t help. What needs to be done?

Case 1: had the match at 17/09 but at OpenData it doesn’t showed at all. The account is opened. But here we have nothing: https://www.opendota.com/players/202126933. What you can advise to do? Attached the screenshot as a prove of the made match

Case 2: also played the match but it didn’t count. Account is opened. https://ru.dotabuff.com/matches/7938885479. But we can see the matches here: http://api.steampowered.com/IDOTA2Match_570/GetMatchHistory/v1/?key=F72B910F69EF897210FC4C18C9AB0426&account_id=297569660. How to count them at opendota? Tried to redownload - didn’t work

**Expected behavior/code*

Case 1: if i play match it counted at opendota
Case2: if i play match it counted at opendota

Matches in Dota2 will be recorded

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by howardchung** [comment]
When was the public match data setting toggled? We currently cannot backfill matches from before the setting was changed.
