### ISSUE TITLE
The match was not counted

### ISSUE THREAD

**Issue by MaxMishin1991** [odota/web#3213]
**Current Behavior**

Please check why the match tel:7975256100 was not taken into account. The match is not displayed in the logs, although the following matches that were played by the client after that are included in the logs

Match 7975300002 was later than 7975256100 and it seems that at that time it was not in the list of games.
Could such a situation exist? When matches are added “in the middle” i.e. with matchId less than the maximum for a given player?

**Expected behavior/code**
I expect everything will work)

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by howardchung** [comment]
This match does appear to be available: https://www.opendota.com/matches/7975256100

Sometimes, the match does not show up in the Steam API until later. We try to account for this by re-checking the same data about an hour later.
