### ISSUE TITLE
The match is not taken into account

### ISSUE THREAD

**Issue by MaxMishin1991** [odota/web#3214]
**Current Behavior**
The match is played and the settings are set correctly (Steam account is open), but the match is not taken into account. Match ID tel:7978607316

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by howardchung** [comment]
https://www.opendota.com/matches/7978607316 appears to be working.
