### ISSUE TITLE
Problem with matches

### ISSUE THREAD

**Issue by MaxMishin1991** [odota/web#3221]
**Current Behavior**
Why do so many errors occur with recording matches? This appears to be a global failure, as this is not an isolated incident. As an example, I attach the following matches that were not taken into account: 7978607316 , 7989547141 , 7989613229 and others

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by MaxMishin1991** [comment]
What should you pay attention to during the game so that our privacy settings are not disabled? And the second question, why are matches displayed in your system, but not ours? Thank you!

**Comment by howardchung** [comment]
You should make sure the Expose Public Match Data setting is toggled on for each player you want to be non-anonymous.

**Comment by MaxMishin1991** [comment]
okey, thanks
