### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by MaxMishin1991** [odota/web#3222]
**Current Behavior**
Those openDota matches in the list of client games appear sequentially only in ascending order of matchId.

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Console Output**
Please provide your browsers console log if possible. Most browsers will open the console via F12.

```
please paste console output in here
```

**Environment**
- Browser Version: [e.g. Chrome 64.0, Firefox 57, Edge 17]
- OS: [e.g. OSX 10.13.4, Windows 10 or Linux Distribution]

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by howardchung** [comment]
I'm not sure what the problem is here--we will return matches in matchID order (assigned when the match is started) which may not correspond to the order in which they finished
