### ISSUE TITLE
error with the profile

### ISSUE THREAD

**Issue by maxqdichz** [odota/web#3223]
hi, I have an error with my profile, everything is open, all information about matches and so on should be shown, but I click on the update button and there are only 60 matches, the word cloud, the wards map and so on does not show

**Comment by maxqdichz** [comment]
nickname: الحمار الثدي نداء
steam id; 1257947758

**Comment by howardchung** [comment]
We only show the advanced data for matches that are parsed. Matches can be requested for parse manually, or automatically for subscribed users.
