### ISSUE TITLE
profile just white screen FLASHBANG and some matches just gone

### ISSUE THREAD

**Issue by poorGeomancer** [odota/web#3227]
When i sign in and push "my profile" sometimes it's just WHITE SCREEN and nothing in the console ( f12 and nothing in the network )

And when i use tab "pros" every game is just gone
only 1 person i remember and this is NS: https://www.opendota.com/players/93712171

Proof my game with him:
![image](https://github.com/user-attachments/assets/34d20ba6-462c-472f-9b5b-921369e6c07f)
![image](https://github.com/user-attachments/assets/167d3ea7-895d-4f65-aabd-7f5d5e6cb722)
![image](https://github.com/user-attachments/assets/50a8eb85-a1a5-46bc-a110-e6c9a68eb930)
![image](https://github.com/user-attachments/assets/f80117ea-ee48-481d-95dc-b9e5f6b855b1)

**Comment by howardchung** [comment]
This issue should be fixed now
