### ISSUE TITLE
Radian/Dire damage columns should be equal width

### ISSUE THREAD

**Issue by dartharaknus** [odota/web#404]
The following looks bad.

![opendota](https://cloud.githubusercontent.com/assets/5713044/20003836/e235a8cc-a288-11e6-93c2-35be6bec1969.png)

**Comment by howardchung** [comment]
This is one of the reasons the current UI doesn't have split tables :)

**Comment by dartharaknus** [comment]
I have looked at a few pages and this table is the only problem for now. Maybe we want to change the UX for the whole widget?

**Comment by CauchyAbel** [comment]
This one doesn't seem to be valid any more?

**Comment by howardchung** [comment]
I am not sure if it is.  @dartharaknus do you have a link to a repro?

**Comment by howardchung** [comment]
Yeah, we never found a good solution to this

**Comment by krazi3** [comment]
I was looking at this issue, what i found is that if we set the width to 1px for the `DEALT` column then for results where the hero count is same for both tables the columns align perfectly

![image](https://user-images.githubusercontent.com/6938697/66266742-703c5b00-e842-11e9-9fc8-7aa5c7499252.png)

But sometimes hero abilities can inflict damage upon allies so in those cases the hero number goes up to 9 and then the columns don't align, like

![image](https://user-images.githubusercontent.com/6938697/66266792-39b31000-e843-11e9-800b-ce59442ac59c.png)

What i propose is if the hero count is more than 5, we can break to next line. @howardchung if you like this solution i can submit a PR for it.

One more thing, i would like to become a regular contributor to this project and also big fan of dota2. :smile:

**Comment by bdbch** [comment]
I could look into it, had several issues like that which were solvable.
