### ISSUE TITLE
Damage dealt/received breakdown per inflictor/hero

### ISSUE THREAD

**Issue by dartharaknus** [odota/web#518]

**Comment by howardchung** [comment]
This was done with #506 ?

**Comment by dartharaknus** [comment]
No, this about the sums in the damage table. not only the crosstable.

**Comment by howardchung** [comment]
But wouldn't those sums essentially be what's already shown in the crosstable?  Not sure if it's useful to have another set of sums that show the same data.

**Comment by dartharaknus** [comment]
I think it can be improved by changing the dealt/recieved to be per hero like how dotabuff does it.

**Comment by howardchung** [comment]
@Argn0 did you do some work toward implementing this?  I recall a discussion about this topic a while ago.

**Comment by Argn0** [comment]
No, I only did the ability targets.

**Comment by howardchung** [comment]
Damage dealt breakdown by hero is now in the API
