### ISSUE TITLE
Add data from parsed matches to benchmarks

### ISSUE THREAD

**Issue by dartharaknus** [odota/web#524]

**Comment by howardchung** [comment]
This requires a backend change.  It's a bit tricky since stun is a parsed data field and currently all benchmarks use unparsed data fields.

**Comment by howardchung** [comment]
Requested:
stuns
lh@10

**Comment by howardchung** [comment]
This can be done by creating a benchmarks dedicated worker that pulls parsed matches and updates benchmarks from the parsed data blobs, similar to what @Argn0 did for scenarios.

Currently benchmarks are updated directly by the scanner process.
