### ISSUE TITLE
Implement uncertainty for MMR estimate

### ISSUE THREAD

**Issue by maaxuy** [odota/web#699]
Now it works really bad cause it use both, ranked and unranked games to estimate the MMR of players, it should only use ranked games, now it works pretty fine with players than only play ranked, but those who plays both (and even unranked with low mmr friends) its really wrong, like it shows 6k in solo mmr and 3k in estimated mmr.

**Comment by howardchung** [comment]
note @blukai you'll have to make a code change to odota/core for this.

Sounds reasonable to me, although it will mean estimation doesn't work on players who never play ranked.

**Comment by maaxuy** [comment]
I am not a programmer, but maybe can make an exception, like only use unranked games if the player never play ranked and it appears in other colour (yellow?) or with a "*" or something and a tooltip that say "estimated mmr is using unranked games, needed ranked games to be more accurate" or something. Thank you for the response.

**Comment by elduryb** [comment]
I am also not a programmer, but looking at this logically - I had always figured "Estimated MMR" was as close to a "Hidden" MMR as you will ever get.
I like it this way - and would ever prefer to see "Estimated MMR" use only UNranked matches to find its value. Does that make sense?

**Comment by maaxuy** [comment]
It doesnt work that way, cause the "Estimated MMR" use the MMR (solo ranked) of the people who played with or against you and they show it in their profile, so you are not getting your "Hidden" MMR, you are getting the real mmr of the players you play with, example, if you play with 4 friends (unranked), and they are like 2k and you are 6k, you are gonna get a "Estimated MMR" of 2.8k, what totally false, thats not your "Hidden MMR" (cause you are playing party with low level friends), and its not even close to your real mmr (6k vs 2.8k), maybe and only maybe if it only use your 5 solo vs 5 solo unranked games (no parties in any side) it will be a more accurate "Hidden MMR" but this way its not even close.

**Comment by howardchung** [comment]
It sounds like what this issue is asking for is a measure of uncertainty in the MMR estimate.  That's probably doable, by assigning scores for each type, like:
* ranked solo: 1
* ranked party: 0.75
* unranked solo: 0.5
* unranked party: 0.22

then average out the scores for the matches used in the estimate and pass that value down.

**Comment by howardchung** [comment]
likely MMR estimation will be removed.  Can revisit if "medal estimation" becomes a thing.
