### ISSUE TITLE
counts summary section on overview

### ISSUE THREAD

**Issue by howardchung** [odota/web#771]
I'm thinking we can display some of the counts data (abbreviated) on the Overview page.  Category data like:
* radiant/dire and winrate on each
* most played gamemode and winrate
* winrate and matches played in most recent patch
* top 3 regions and winrate

We can make the counts API call (like we do for peers, heroes, and matches) and then just display a subset of the data.

**Comment by Luchanso** [comment]
@howardchung, what's need change in pr #756?
Can I'll add this data in second column on the bottom?
